### ISSUE TITLE
end_of_file_fixer allow single blank line at end of file

### ISSUE THREAD

**Issue by ben-elttam** [pre-commit/pre-commit-hooks#1000]
Some times it is nice to allow a file to end in a blank line.

e.g.

| Line | Text |
| ---- | ---- |
| 1 | The quick brown fox jumped over the lazy dog.|
| 2 | There is a blank line after this line.|
| 3| |

I want to be able to keep the blank line at (3).

```asciidoc
The quick brown fox jumped over the lazy dog.
There is a blank line after this line.

```

So that `wc -l` is 3, not 2.

But pre-commit `end-of-file-fixer` will strip this blank line, so that the file is only 2 lines. With the file ending with a `\n` new line character terminating line 2.

It would be nice to be able to pass an option to allow a single blank line, or up to X blank lines at end-of-file. So that a file can end with the byte sequence `\n\n`.

**Comment by asottile** [comment]
you're wrong but you're free to write your own tool which does an incorrect thing
