### ISSUE TITLE
pip package executables do not have the same name as the hook

### ISSUE THREAD

**Issue by DaveRuijter** [pre-commit/pre-commit-hooks#1001]
_Situation/problem:_
In large enterprise it is usually prohibited to consume software/components directly from the internet. The default / advised usage of this wonderful repo is therefore not allowed to limit the risk of supply chain attacks.

With the released [python package](https://pypi.org/project/pre-commit-hooks/) I can apply the exact same way of working as with for instance the ruff hook and allow our package/dependency scanning software do it's thing to prevent the risk mentioned above. Wonderful.

But, I could not directly get it working! It took me a while to find out what was going wrong in my configuration, and I had to go look into the [setup.cfg](https://github.com/pre-commit/pre-commit-hooks/blob/main/setup.cfg) file to notice that the executers don't have the same names as the hooks.

_Solution:_
**Please align the hook names with the executor names, to greatly increase the ease-of-use of the python package.**

_PS. I have seen [this closed issue](https://github.com/pre-commit/pre-commit-hooks/issues/887), but I believe it is missing the point and with the above arguments I hope to make a case for the proposed changes._

**Comment by asottile** [comment]
you found the exact duplicate and still made a new one?

be a better open source participant
