### ISSUE TITLE
trailing-whitespace: Add option to only lint files without fixing them

### ISSUE THREAD

**Issue by dr-1** [pre-commit/pre-commit-hooks#1004]
I would like a `--no-fix` option in the `trailing-whitespace` hook to turn off automatic fixing of the files. In some situations, automatic fixing is not what one wants, for example when files of a repository are sourced from another system (think SQL definition files from a database) and you want to encourage contributors to fix code problems in that source system, not only in the repository.

I can provide a pull request for this.

**Comment by asottile** [comment]
please search for duplicates which include the reason this will not be accepted

**Comment by dr-1** [comment]
@asottile, I have already searched. Can you point me to the issues that you are referring to?

**Comment by dr-1** [comment]
In #108 you mention
"I'd accept PRs to add options to turn off modification, but the default is going to be modifying."

**Comment by asottile** [comment]
that's from 2016, there's much newer ones

**Comment by dr-1** [comment]
I went over the issues again, still not seeing those duplicates :/
