### ISSUE TITLE
```trailing-whitespace```  ```end-of-file-fixer```  ```mixed-line-ending``` Check file before change

### ISSUE THREAD

**Issue by TMDevel89** [pre-commit/pre-commit-hooks#1009]
The modules do not check the files to see if action is required. They are changed every time they are run.

**Comment by asottile** [comment]
please search for duplicates, there's at least one

**Comment by TMDevel89** [comment]
@asottile please link the duplicate

**Comment by asottile** [comment]
sorry I am not a glorified search engine for free
