### ISSUE TITLE
aws_credentials not working properly

### ISSUE THREAD

**Issue by rhoml** [pre-commit/pre-commit-hooks#101]
We have a Puppet manifest with no aws key and the check keeps telling us that the file has aws credentials.

**Comment by asottile** [comment]
Do you have some output?  "not working" isn't really an actionable problem description :(

**Comment by rhoml** [comment]
So the only output that we have is 
``` Detect AWS Credentials..............................................Failed```

don't think it is of any help either...

**Comment by asottile** [comment]
You're probably hitting this case which is not terribly helpful :(

https://github.com/pre-commit/pre-commit-hooks/blob/d740faeded968de3881405d7de09dc6d2e0d7b06/pre_commit_hooks/detect_aws_credentials.py#L50-L52

**Comment by rhoml** [comment]
probably no idea =(

**Comment by asottile** [comment]
I'm improving the error message -- then it should be obvious what needs fixing :)

**Comment by asottile** [comment]
@rhoml if you pull the latest version of the hooks (`pre-commit autoupdate`) the error message should help you out :)

**Comment by arahayrabedian** [comment]
most embarrassing. @asottile lemme know if you'd like me to have a look at anything related to this.
