### ISSUE TITLE
Add option to ignore file(s) in `name-tests-test` 

### ISSUE THREAD

**Issue by Seluj78** [pre-commit/pre-commit-hooks#1011]
I would like to ignore a specific file when running `name-tests-test`, and it isn't currently possible

**Comment by asottile** [comment]
what have you tried so far?

**Comment by Seluj78** [comment]
Honnestly, not much. The setup is, I have a tests/ directory with many files and subfolders.

I also have a `conftest.py` that was ignored by the hook and a `utils.py` file that got flagged as not starting by `tests_`

Ideally I'd like an option like so:


```yaml
      - id: name-tests-test
        args: [--pytest-test-first, --ignore=tests/utils.py]
```

**Comment by asottile** [comment]
have you read the docs for pre-commit?

**Comment by Seluj78** [comment]
OMFG thank you... I feel dumb... I use `exclude` in other pre-commit hooks, I just didn't think it would work on these hooks but it makes sense now...
