### ISSUE TITLE
detect-aws-credentials wrongly failing

### ISSUE THREAD

**Issue by rb-synth** [pre-commit/pre-commit-hooks#1012]
The output of `pre-commit run --all-files detect-aws-credentials` is attached below. All results are `no` and yet it fails. This is happening across a lot of my repos, which makes me think it's a bug. 

```
detect aws credentials...................................................Failed
- hook id: detect-aws-credentials
- exit code: 1

AWS secret found in src/code/file_0.yaml: no**************************
AWS secret found in src/code/file_1.py: no**************************
AWS secret found in src/code/file_2.py: no**************************
AWS secret found in src/code/file_3.py: no**************************
AWS secret found in src/code/file_4.py: no**************************
...
AWS secret found in src/code/file_n.py: no**************************
```

**Comment by asottile** [comment]
check your aws config and you'll find your answer

**Comment by rb-synth** [comment]
That's not a very informative answer. What should I be looking for in the aws config file? If there is something wrong, then why does the test show up as `no******`, which implies that there **isn't** a secret key in all of the files?

**Comment by asottile** [comment]
you probably have something in your aws config that's a common string that starts with "no"
