### ISSUE TITLE
YAML check fails with custom tags

### ISSUE THREAD

**Issue by bdellegrazie** [pre-commit/pre-commit-hooks#103]
Since the YAML loader is just checking syntax it shouldn't fail with custom types, e.g.:

```yaml
---
some_value:
   !some_custom_type: "a string"
```

The pre-commit check fails even though this is legitimate YAML.

**Comment by asottile** [comment]
This is by design for two reasons:
- it can't know every custom tag
- it uses only `safe_load` to ensure cross language loadability

**Comment by bdellegrazie** [comment]
@asottile: it doesn't use safe_load (unless there's an indirection there I'm not seeing):

```python
 yaml.load(open(filename), Loader=Loader)
```

I don't expect it to know *any* custom tags - but since we're only validating *syntax* is there any way of getting the YAML loader to treat custom tags as normal tags (i.e. not special at all)?

**Comment by asottile** [comment]
Ah, well it should be using `safe_load`, created an issue for that: #104

I'm not sure there's a way in python, though I'd be willing to accept a PR that does the following (if it's possible!):
- Adds an `--unsafe` option to `check-yaml` which adds the extra functionality of parsing syntax-only (including custom tags)
