### ISSUE TITLE
Add argument to skip formatting in f-string with `double-string-fixer`

### ISSUE THREAD

**Issue by SachiaLanlus** [pre-commit/pre-commit-hooks#1045]
Thank you for this great project. It saves me so much time for chore stuff.
However there is a thing about `double-string-fixer` annoying me these days.
My team's dev env is set to be Python 3.8.
But my dev env is Python 3.12 for some script to run.
But if I trigger a pre-commit. It will change the quote sign in nested f-string for me.
Which is not allowed in the Python 3.8.
Is there any method to skip this check inside f-string or to specify `python-version` in argument?

I think this issue is related to https://github.com/pre-commit/pre-commit-hooks/issues/971 and https://github.com/pre-commit/pre-commit-hooks/pull/973

**Comment by asottile** [comment]
show your configuration then

**Comment by SachiaLanlus** [comment]
looks like you are right.
update to the latest version fix the issue.
thank you

**Comment by asottile** [comment]
try that before reporting an issue next time
