### ISSUE TITLE
`check-illegal-windows-names` is not present in the repository

### ISSUE THREAD

**Issue by TimeTravelPenguin** [pre-commit/pre-commit-hooks#1046]
I am setting up a new project and thought to add the `check-illegal-windows-names` hook. I am on v4.6.0 of pre-commit, and I don't see the hook in the repo, yet it is documented in [README.md](https://github.com/pre-commit/pre-commit-hooks#check-illegal-windows-names)

When running `pre-commit run -a` in my repo, I get the following error
```
[ERROR] `check-illegal-windows-names` is not present in repository https://github.com/pre-commit/pre-commit-hooks. 
Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.
```

Is the README out of date, or is the hook missing?

**Comment by asottile** [comment]
please search the issue tracker for duplicates before making an issue next time

**Comment by TimeTravelPenguin** [comment]
Ah, apologies, I did not see it in the closed issues.
