### ISSUE TITLE
[Bug] requirements-txt-fixer: Index URLs Should not Sort

### ISSUE THREAD

**Issue by ax3l** [pre-commit/pre-commit-hooks#1054]
Hi,

I have a `requirements.txt` file of the form
```
-r ../requirements.txt

openPMD-validator

# https://pytorch.org/get-started/locally/
-i https://download.pytorch.org/whl/cpu
torch
```

which `requirements-txt-fixer` reformats (and breaks) to
```

# https://pytorch.org/get-started/locally/
-i https://download.pytorch.org/whl/cpu
-r ../requirements.txt

openPMD-validator
torch
```

In this case, I intentionally use `-i` for the index instead of `--extra-index-url` to avoid index confusion attacks. But if `openPMD-validator` gets sorted after the `-i` line, then it cannot be found (because it exists on the regular PyPI index).

As a minor observation, maybe the `-r ../requirements.txt` should also not be moved around?

**Comment by asottile** [comment]
sounds like a bit of a garbage in garbage out scenario.  if you isolate your torch hack to it's own file it should work
