### ISSUE TITLE
[Feature Request] Allow arbitrary file extensions when validating JSON

### ISSUE THREAD

**Issue by matthew-rister** [pre-commit/pre-commit-hooks#1058]
Some file formats such as [glTF](https://github.com/KhronosGroup/glTF-Tutorials/blob/main/gltfTutorial/gltfTutorial_002_BasicGltfStructure.md) internally use JSON to represent data. Unfortunately the `check-json` hook does not provide the ability to validate extensions other than .json. Please consider adding a hook option to enable JSON validation on arbitrary file formats.

**Comment by asottile** [comment]
have you read the pre-commit docs? there are settings you can override on hooks to do exactly what you want
