### ISSUE TITLE
GitHub release v4.6.0 isn't set as latest release

### ISSUE THREAD

**Issue by echoix** [pre-commit/pre-commit-hooks#1064]
Version 4.6.0 of https://github.com/pre-commit/pre-commit-hooks was released in April 2024. Maybe at first, it was meant to be a pre-release or something. But now, the checkbox to set as latest release should be checked, thus allowing to show it on the repo's home page, and also having https://github.com/pre-commit/pre-commit-hooks/releases/latest point to https://github.com/pre-commit/pre-commit-hooks/releases/tag/v4.6.0 instead of https://github.com/pre-commit/pre-commit-hooks/releases/tag/v4.5.0.

Screenshots:
![image](https://github.com/pre-commit/pre-commit-hooks/assets/27212526/27ff5aa6-0c65-47e3-9901-b6322aa3e5e5)
![image](https://github.com/pre-commit/pre-commit-hooks/assets/27212526/c912e81e-0d75-4f33-94d1-74bf26dd32d8)
![image](https://github.com/pre-commit/pre-commit-hooks/assets/27212526/260ed408-e3d7-4d34-a024-676042b26634)

**Comment by asottile** [comment]
nah github's ui just sucks -- too many things to click every time

**Comment by echoix** [comment]
Also, is the `check-illegal-windows-names` hook ready for general usage (as it is still unreleased)? I stumbled upon it when upgrading the pre-commit config for a repo, and tried including it, but wasn't available for the latest 4.6.0 version. I was quite curious and interested, as it was an addons repo where sometimes contributors don't have lots of coding experience or git knowledge, but we all need to start somewhere. ;)
