### ISSUE TITLE
Handling of CR as EOL in trailing-whitespace

### ISSUE THREAD

**Issue by AFulgens** [pre-commit/pre-commit-hooks#1066]
Currently the `trailing-whitespace` hook (`trailing_whitespace_fixer.py`) handles the end-of-line (EOL) combinations of:

- Windows flavor (CRLF)
- Linux, modern MacOS flavor (LF)

However, files that use CR as EOL are handled incorrectly by the hook, and in combanation with EOF-Fixer (`end_of_file_fixer.py`) this makes it impossible to commit the file if both hooks are active, because:

- EOF fixer adds a CR as last byte of the file
- trailing-whitespace fixer removes the last CR

(Or the other way around, depending on order of the hooks.)

Current workarounds:

- Change the EOL of the file (but what if I need it to have CR for testing some crazy edge-case?)
- Ignore the hooks when committing this file (meh)

**Question:** Would it be OK to handle `\r` the same way `\n` and `\r\n` are handled in `trailing_whitespace_fixer.py`? If yes, I'll gladly prepare a PR.

**Comment by asottile** [comment]
it's been decades since anything used cr as wolf.  it is unsupported intentionally

**Comment by AFulgens** [comment]
I guess, we are the only team in the world then working on legacy software, which is generating XMLs with CR as EOL and we must parse it in modern codebase, and thus have tests for it. Nevertheless, I appreciate your answer, onto the `exclude` list with those test XMLs for this hook! 🏴‍☠️

**Comment by asottile** [comment]
if you have generated files you probably don't want to lint them anyway
