### ISSUE TITLE
While Performing Powershell linting using Pre-commit through hook 'PSScriptanalyzer' I am getting below error: Invoke-ScriptAnalyzer : A positional parameter cannot be found that accepts argument

### ISSUE THREAD

**Issue by Shubhij12** [pre-commit/pre-commit-hooks#1070]
I have Installed PSScriptAnalyzer module in my local and while plugin in with precommit i have given below config file:

Please find following Config file

repo: local hooks: - id: PSScriptAnalyzer name: PSScriptAnalyzer description: Run PSScriptAnalyzer on commit language: system entry: powershell -NoProfile -NonInteractive -Command Invoke-ScriptAnalyzer -EnableExit -Path files: ^.*.ps1$ pass_filenames: true
Getting below Error : A positional parameter cannot be found that accepts argument in ___.ps1

**Comment by asottile** [comment]
your configuration doesn't include any hooks from this repo
