### ISSUE TITLE
trailing-whitespace hook leads to different code(potentially creating unintended bugs)

### ISSUE THREAD

**Issue by fdobal** [pre-commit/pre-commit-hooks#1071]
When executing pre-commits hooks on the following code:

`
    from typing import Optional

    RESNNMMTTT_BUCAAA_ABCD = '12345'
    def f(dnda_classfifkqopwr: str, cdruhb: str) -> Optional[str]:
        if dnda_classfifkqopwr == "a":
            return RESNNMMTTT_BUCAAA_ABCD if cdruhb == "hh-lopcxsd-9" else f"{RESNNMMTTT_BUCAAA_ABCD}-{cdruhb}"
        
    return None
`

the file is modified to this file:

`
    from typing import Optional
    
    RESNNMMTTT_BUCAAA_ABCD = '12345'
    
    
    def f(dnda_classfifkqopwr: str, cdruhb: str) -> Optional[str]:
        if dnda_classfifkqopwr == "a":
            return RESNNMMTTT_BUCAAA_ABCD if cdruhb == "hh-lopcxsd-9" else f"{RESNNMMTTT_BUCAAA_ABCD} -{cdruhb} "
    
        return None
`

Particularly take a look at the following part:

ABCD} -{

It adds an extra blank space.
<img width="1192" alt="Screenshot 2024-07-09 at 20 11 00" src="https://github.com/pre-commit/pre-commit-hooks/assets/97089225/743caa8a-81a7-4a4f-80aa-faa8c85abd13">

It can be reproduced on Mac and Linux

Python version is 3.12.

The version used is v4.6.0.

**Comment by asottile** [comment]
I can't reproduce, must be some other tool?
