### ISSUE TITLE
feature request: block adding of TODO lines

### ISSUE THREAD

**Issue by ericfrederich** [pre-commit/pre-commit-hooks#1075]
I don't remember what editor or IDE I was using but it would give a warning when you'd try to commit new code with a TODO in it.

This would be a nice hook to have available.

Obviously there are times where that might be your intention in which case you could do `SKIP="check-todos" git commit -m "rough implementation of feature-xyz"`

**Comment by asottile** [comment]
please search, this has been rejected at least twice before
