### ISSUE TITLE
end-of-file-fixer doesn't work correctly with CRLF endings

### ISSUE THREAD

**Issue by edobez** [pre-commit/pre-commit-hooks#1078]
`end-of-file-fixer` adds a LF before the last empty line, regardless of what are the EOL of the file.
On Windows, where typical EOL are CRFL, leaves the files with mixed endings.

**Comment by edobez** [comment]
I added the following test line in end_of_file_fixer_test.py to reproduce the problem:
`(b'foo\r\nbar', 1, b'foo\r\nbar\r\n')`.

**Comment by asottile** [comment]
please search the issue tracker

**Comment by edobez** [comment]
I guess you mean this https://github.com/pre-commit/pre-commit-hooks/issues/326 issue.
The problem solved by that issue and related PR is to correctly detect CRLF endings, but it doesn't solve the problem stated here: in a  CRLF-ended file, we want that even the **last line** uses CRLF.
