### ISSUE TITLE
feature request: don't modify files unless requested

### ISSUE THREAD

**Issue by insasho** [pre-commit/pre-commit-hooks#108]
This is a feature request.

Hooks that modify the contents can be dangerous and surprising. While some developers will appreciate the auto-fix behavior, others (like me) find it distracting and disconcerting. I'd prefer that none of the hooks perform any mutation and allow the user to take manual action. Allowing each hook to arbitrarily modify files burdens the user (me) with the need to understand what kinds of changes they might make, whether they are configurable or not, etc. It would be more ergonomic to opt-in to each mutation behavior.

Thanks for writing this framework. It is saving me lots of time!

**Comment by asottile** [comment]
Modifying by default is by-design.  Our goal is to have as little developer interaction as possible when committing.  Errors that require manual intervention increasingly encourage developers to `--no-verify` or `SKIP=...` which somewhat defeats the purpose of having the hooks at all.

I'd accept PRs to add options to turn off modification, but the default is going to be modifying.

> Hooks that modify the contents can be dangerous and surprising.
The hooks are very well tested and we use them on many and very large codebases without issue -- I wouldn't call the modification dangerous.

>  It would be more ergonomic to opt-in to each mutation behavior.
You're already opting into the hook by adding it to your config.

**Comment by insasho** [comment]
OK I can understand that reasoning, and can see how it is useful. How about an alternate feature request, then: The ability to disallow *all* plugins from modifying files using a .pre-commit-config.yaml option.

One example of where automatic modification could cause problems is when the pre-push hook is used, because it seems to create a situation where a developer may run application tests using locally modified files and then end up pushing a different (modified) files to the server when `git push` is run. 

Sometimes the modifications made by the pre-commit hooks could have functional side-effects. Example: end-of-file-fixer may break files that are supposed to end with a non-newline. fix-encoding-pragma could break files that are dependent on system encoding. requirements-txt-fixer could break because the order of dependencies in requirements.txt is actually meaningful in cases where the pip packages underspecify dependencies. Fix-by-default also breaks any scenario where checksums are committed as part of a repository (such as you might use for a package manager or verifying the integrity of data files).

**Comment by asottile** [comment]
pre-commit blocks commits / pushes when modifications happen, the example with `pre-push` is invalid.

**Comment by nettrino** [comment]
@asottile +1 on supporting optionally not modifying files - was this closed as won't fix or is it implemented an I've missed it?

**Comment by asottile** [comment]
correct, the answer is no

**Comment by asottile** [comment]
please don't grave dig 6 year old issues
