### ISSUE TITLE
`file-contents-sorter` breaks .gitignore order

### ISSUE THREAD

**Issue by ddeepwell** [pre-commit/pre-commit-hooks#1086]
The `file-contents-sorter` uses the default python [sorter](https://docs.python.org/3/library/functions.html#sorted) which places items with a leading exclamation mark before the equivalent file. When this is used on the `.gitignore` file, it breaks the functionality to include files of a specific name after a more generic name was ignored.

For example, the following `.gitignore` file will ignore `test1-example`
```
!test*-example
test*

```
but this next will _not_ ignore `test1-example`
```
test*
!test*-example
```

Using the file sorter pre-commit hook as is breaks the management of ignored files.

Can an option be added to place leading exclamation mark lines to the end of the file? This could be further generalized to allow any matching regex to be placed at the end of the file.

**Comment by asottile** [comment]
then... simply don't use it on `.gitignore` ?  it's not designed for that
