### ISSUE TITLE
check-yaml has issues with new docker compose annotations

### ISSUE THREAD

**Issue by Matt-STN** [pre-commit/pre-commit-hooks#1090]
Since Docker Compose version `2.24.4`, two new tags allow to choose how the compose files are merged: `!override` and `!reset`. It seems `check-yaml` has issues with these tags, since running it always gets me this error:
```
could not determine a constructor for the tag '!override'
  in "docker/dc.yml", line 28, column 13
```

**Comment by asottile** [comment]
please read the docs before opening an issue next time!

**Comment by roger-duthie-pivotal** [comment]
Where are these docs?  Does it solve the problem?

**Comment by Matt-STN** [comment]
It's referenced here : https://github.com/pre-commit/pre-commit-hooks/issues/273 . Basically you have to add `--unsafe` to have the check only parse the files for syntax check instead of loading them.
So yes, it solves the problem, but I couldn't find any doc other than that and had to look for a while (the README is not clear enough imo, at least when you're not a YAML expert).
