### ISSUE TITLE
check-illegal-windows-names hook does not exist

### ISSUE THREAD

**Issue by madpipeline** [pre-commit/pre-commit-hooks#1091]
```
$ pre-commit autoupdate
[https://github.com/pre-commit/pre-commit-hooks] Cannot update because the update target is missing these hooks: check-illegal-windows-names
```

Running on version `v4.6.0`

**Comment by asottile** [comment]
search the issue tracker next time!

**Comment by madpipeline** [comment]
There are 2 other closed issues on the topic, none of which have an explanation as to why a hook is documented as available but the latest release of pre-commit does not have it, nor is it present in the `main` branch.

While this issue and https://github.com/pre-commit/pre-commit-hooks/issues/1046 are duplicates of https://github.com/pre-commit/pre-commit-hooks/issues/1043 none of them have an explanation about the discrepancy between the documentation and the current release.

If the case is that

> "perhaps it's in a newer version" yes not released yet

then the hook should not be documented as available, until the hook is released.

P.S. While I do understand that it's annoying to have duplicate issues pop up, that is no reason to get aggressive, when after 5 months of reporting, people still try to use a documented hook that is in fact not available.

**Comment by asottile** [comment]
good job you found the answer!  you just don't like it and that's fine but please don't open an issue next time when the answer is right there
