### ISSUE TITLE
Recursive validation of all YAML, JSON, TOML files

### ISSUE THREAD

**Issue by madpipeline** [pre-commit/pre-commit-hooks#1092]
Currently these parsers only check the files given directly to the hooks.

It would be easier to setup if the hooks would have a flag to recursively find all files with the language specific extensions, and scan them.

Also to list these files when the hook is called with `--verbose`.

**Comment by asottile** [comment]
I think you're confused -- show what you've tried and what is not working?

**Comment by madpipeline** [comment]
I don't think I fully know how to use pre-commit properly yet. Still digging into https://pre-commit.com/#filtering-files-with-types and trying to find out how I can generate a list of all files ending with the YAML, JSON and TOML extensions to pass over to the hooks for them.

Closing this.

**Comment by madpipeline** [comment]
I still can't solve it. I have JSON files in a subdirectory of my git repo. When running

```
pre-commit run --all-files check-json
```

with the intent to check all files in the repo, not just the staged ones, I get this output:

```
check json...........................................(no files to check)Skipped
```

The configs that I have tried:

```
      - id: check-json
        types: [json]

      - id: check-json
        files: '\.json$'

      - id: check-json
        files: '.*\.json$'
```

All end up in the same result: `no files to check)`

**Comment by madpipeline** [comment]
I tried this even with only the default:

```
- id: check-json
```

and placed a json file in the root of the repo, and still get the same output: `no files to check`

**Comment by asottile** [comment]
show your full unredacted configuration and the output of `git ls-files` ?

**Comment by madpipeline** [comment]
So if a file is not tracked yet by git, pre-commit hooks will not pick them up, even if they exist in the repository, regardless wether you specify `--all-files` or not.

Thank you for the guidance.
