### ISSUE TITLE
Warning about deprecated stage names (commit, push)

### ISSUE THREAD

**Issue by haukex** [pre-commit/pre-commit-hooks#1096]
[pre-commit v4.0.0](https://github.com/pre-commit/pre-commit/releases/tag/v4.0.0) includes this change:

> Add warnings for deprecated stages (`commit` -> `pre-commit`, `push` -> `pre-push`, `merge-commit` -> `pre-merge-commit`).

Which introduces this warning when using the hooks from this repository:

```
[WARNING] repo `https://github.com/pre-commit/pre-commit-hooks` uses deprecated stage names (commit, push)
which will be removed in a future version.  Hint: often `pre-commit autoupdate --repo https://github.com/pre-commit/pre-commit-hooks`
will fix this.  if it does not -- consider reporting an issue to that repo.
```

**Comment by asottile** [comment]
you didn't do what the hint said

**Comment by haukex** [comment]
Thanks, I see what happened: I missed that there was a v5.0.0 release because https://github.com/pre-commit/pre-commit-hooks still shows v4.6.0 as the "latest" release.
