### ISSUE TITLE
[Suggestion] fix-byte-order-marker could have --fix=no option

### ISSUE THREAD

**Issue by haukex** [pre-commit/pre-commit-hooks#1097]
`check-byte-order-marker` is deprecated, but its replacement `fix-byte-order-marker` doesn't have a `--fix=no` option. This means that I am currently forced to use the deprecated `check-byte-order-marker` if I *only* want to check and not fix the BOM.

I would suggest either adding that option, or perhaps un-deprecating `check-byte-order-marker`?

**Comment by asottile** [comment]
no. the intention is to remove the checker only
