### ISSUE TITLE
end_of_file_fixer.py - how to exclude *.jsonl files for this hook only

### ISSUE THREAD

**Issue by frichtarik** [pre-commit/pre-commit-hooks#1099]
i have and issue with end-of-file-fixer for *.jsonl files 
https://www.atatus.com/glossary/jsonl/ 

new line at the end is considered new (empty) entry

but i want all other hooks (and repos) to process them, so using exclude in the config is not a way 

before i'll have time to create a PR myself, i'd like to asks if you're ok with it

**Comment by asottile** [comment]
I think you're confusing a blank line at the end (\n\n) vs ending in a newline (\n) and there is not actually a problem

you can read the pre-commit docs on how to do what you want either way.  please do not send a pr
