### ISSUE TITLE
Is there any way to use this without downloading github.com/pre-commit/pre-commit-hooks with git?

### ISSUE THREAD

**Issue by grepwood** [pre-commit/pre-commit-hooks#1102]
The only way I can access https://github.com/pre-commit/pre-commit-hooks is if I ask my workplace's local Artifactory instance to reach for a snapshot of the repository, or a tag, or a release. I can't touch the repo as if it were a repo. Commands like `git clone` are not going to work. But `curl -Lu user:token https://artifactory.at.cool.place.to.work/literally_magic/pre-commit/pre-commit-hooks/archive/refs/tags/v5.0.0.tar.gz` will work fine.

Is there any way I can use pre-commit-hooks in a .pre-commit-hooks.yaml file without involving the git command then?

**Comment by asottile** [comment]
there is an unsupported escape hatch documented on pre-commit.com but I'm sorry I can't help you for free for self inflicted corporate support
