### ISSUE TITLE
Check file name format by regex

### ISSUE THREAD

**Issue by christophehenry** [pre-commit/pre-commit-hooks#1103]
Unless I'm wrong, there's not `pre-commit` hook that check file names match against an authorized regexes. Would that interest you that I develop one?

**Comment by christophehenry** [comment]
I'm sorry, but…Where is it documented?

**Comment by asottile** [comment]
have you searched at all? there's a bunch of duplicates and examples you can follow

**Comment by christophehenry** [comment]
Well maybe I didn't do the research with the correct words but right now I'd say we're not talking about the same thing. I'm not talking about [the files](https://pre-commit.com/#config-files) option. I want a check that validates committed files have a correct naming scheme.

**Comment by asottile** [comment]
what have you searched?

**Comment by christophehenry** [comment]
Ok, I'm not sure what's going on here… If you're saying it's documented, can you just point me to the documentation or relevant check?

**Comment by asottile** [comment]
I'm trying to get you to do that for me.  I am not a glorified search engine and if you put in a little effort I think you'll find there are lots of answers

but if you're not going to put in any effort to answer your own question I'm not going to put in effort to help you
