### ISSUE TITLE
check-yaml doesn't recognise !override tag

### ISSUE THREAD

**Issue by roger-duthie-pivotal** [pre-commit/pre-commit-hooks#1108]
Since docker compose 2.24.4, docker-compose.yml files may have `!override` tags.

There is a minimal example on the docker website via this link: https://docs.docker.com/reference/compose-file/merge/#replace-value

## Expected Behaviour

A valid docker-compose.yml is passes formatting verification.

## Actual Behaviour

```
check yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

could not determine a constructor for the tag '!override'
  in "docker-compose.minimal-example.yml", line 3, column 12
```

**Comment by asottile** [comment]
sorry but if you're not going to put any effort into reading the docs or searching the issue tracker I'm not going to put in any effort on your issue

there are tens of duplicates if you put in an ounce of effort to find them

**Comment by roger-duthie-pivotal** [comment]
Don't be sorry, it's not for you to be sorry!  I should say sorry!  I did check the issues and docs.

Searching for "override" I get 9 hits. Only one looks relevant, I didn't see it when opened the ticket. I think there's not really any good clues to what to do, just some pithy comment that boils down to RTFM.  Which part of the manual are do you think helps with this? Here: https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#check-yaml ?

I guess you're too busy to link to the conclusion here, then.  I'll make the effort for the next person.  

Is the answer that you use `--unsafe`?  Are these standard docker annotations to be considered "unsafe"?

I guess you have no time for this.  So perhaps I don't bother you with it and use a third-party yaml checker.

**Comment by roger-duthie-pivotal** [comment]
Here's a reference to an issue where you answered the question: https://github.com/pre-commit/pre-commit-hooks/issues/273

You're welcome.
