### ISSUE TITLE
`trailing-whitespace`: exclude `tsv` files by default.

### ISSUE THREAD

**Issue by randolf-scholz** [pre-commit/pre-commit-hooks#1110]
[Tab separated values](https://en.wikipedia.org/wiki/Tab-separated_values) is a common data-format similar to `.csv`, but [by definition](https://www.iana.org/assignments/media-types/text/tab-separated-values) uses tabs as the separator.

Trailing tab stops naturally occur when missing values are present, because each row needs to contain the same number of tabs. Hence, the `trailing-whitespace` hook can corrupt `.tsv` files. I propose to add `exclude_types: [tsv]` to the default configuration of the hook.

**Comment by asottile** [comment]
you can always`exclude_types` in your own config

it's more surprising to make this choice for everyone here
