### ISSUE TITLE
`no-commit-to-branch` does not set the `stages` property

### ISSUE THREAD

**Issue by jakob-keller** [pre-commit/pre-commit-hooks#1114]
Hello and thanks for providing such essential tooling to the world!

I want to report possibly undesired behavior in the `no-commit-to-branch` hook: It does not set the `stages` property. Yet, according to [pre-commit documentation](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages):
> [...], it is usually a good idea to provide an appropriate `stages` property.

As a result, the special `manual` stage is implicitly included, which may lead to false positive results e.g. when running all hooks in freshly checked out repos or the main branch in general.

I believe this behavior might be unintended and might have contributed to previous issues, including #265, #653, and #954. The recommended workaround is to use the `SKIP` environment variable.

While using `SKIP` certainly addresses the false positive, I believe a more robust solution would be to declare the stages property for `no-commit-to-branch` and exclude at least the `manual` stage. That way, users would not need to be concerned by this and no `SKIP` would be required for many more use cases.

I'm curious about your thoughts and thanks again!

EDIT: I am a bit confused as to how the `manual` stage works. I thought it was the stage that applies when I manually run `pre-commit run`. Instead, manually running `pre-commit run` without the `--hook-stage` argument will result in the `pre-commit` stage. If that "default stage" changed from `pre-commit` to `manual`, my suggestion above would still make sense, but that is way beyond this issue. Feel free to close, but I would be very keen to learn your opinion on those topics.

**Comment by asottile** [comment]
I believe you're confused about what the manual stage is and I believe the stages are set correctly for this hook and setting them to something else would not have changed anything about the linked issues

it's also very easy for you to just try your ideas first instead of opening an issue!
