### ISSUE TITLE
Unsigned binary executables

### ISSUE THREAD

**Issue by IansGithubAcc** [pre-commit/pre-commit-hooks#1121]
This might be the wrong place for this, but I'm a bit lost.
I'm not sure how it works, but many of these hooks seem to be installed as executable binaries on my machine.

This would not be a problem normally, but the binaries are unsigned.
And due to some new company policy I can no longer run unsigned executables.
Is there some way that I could run the python code directly without using binaries like `end-of-file-fixer.EXE`?
Or would it be possible to install packages using conda (I don't understand why, but if I install with conda the executables are signed).

Any help would be greatly appreciated.

**Comment by asottile** [comment]
I assume you're on windows?  there's nothing particularly special about these -- they're just the result of `pip install` 

not really much I can do about your company policy but if your company wants to set up a support contract I could potentially build a custom solution

**Comment by IansGithubAcc** [comment]
Thanks for the input! Sadly, the userbase within the company is too small to warrant the expense. And it is unlikely to grow much further with this issue in place. I'll look into forking myself.
