### ISSUE TITLE
pretty-format-json: allow specifying tab indentation 

### ISSUE THREAD

**Issue by sanmai-NL** [pre-commit/pre-commit-hooks#119]
[`pretty-format-json` has an integer `indent` parameter](https://github.com/pre-commit/pre-commit-hooks/blob/6b1aa19425b35f8c34f43ada8f1045b028dc19a5/pre_commit_hooks/pretty_format_json.py#L37) that specifies the number of spaces to use (i.e., indentation width). This is an enhancement proposal, with the aim that tabs can be specified as indentation delimiter.

[Since CPython 3.2](https://docs.python.org/3.5/library/json.html#basic-usage) one can use strings instead of integers as `indent` argument. The main use for that is to specify tabs as indentation. This has some advantages and proponents ([1](http://lea.verou.me/2012/01/why-tabs-are-clearly-superior/), [2](http://nickgravgaard.com/elastic-tabstops/)). For JSON, vertical alignment makes less sense than for programming language source code (e.g., long lists of parameter names), so a TAB-only indentation is feasible and advantageous, since it compresses the data (useful for webdev) and allows for configurable indentation width (useful for hard-to-read JSON).

This seems easy to implement by me or you, I'm just looking for feedback on this.

**Comment by asottile** [comment]
I mean, if you make a PR I'll merge it.  I'm a bit -0.5 on tabs though :P

**Comment by sanmai-NL** [comment]
See PR #120.

Why do you depend on [`simplejson`](https://simplejson.readthedocs.io/en/latest/), by the way? Is the extra compatibility with very old Python 2 versions worth the extra dependency outside the standard library?

**Comment by asottile** [comment]
it was needed to properly support the object pairs hook

**Comment by asottile** [comment]
via #120
