### ISSUE TITLE
new hook for nonstrict-json, simplify existing hooks for check-json/pretty-json as a bonus

### ISSUE THREAD

**Issue by mattvonrocketstein** [pre-commit/pre-commit-hooks#130]
I was considering writing a hook for syntax-checking of nonstrict JSON when I realized
- 1 by adding the [demjson](https://pypi.python.org/pypi/demjson) module to setup.py's requirements, we'd get the [jsonlint](http://deron.meranda.us/python/demjson/demjson-2.2.4/docs/jsonlint.txt) command line tool in virtualenv's automatically.
- 2 by (1), only a "system" language item with an appropriate entry needs to be added to hooks.yml.  that is,

```
-   id: check-json-nonstrict
    name: 'Check JSON (nonstrict)'
    description: This hook checks json files for parseable (nonstrict) syntax.
    entry: jsonlint -S
    language: system
```
- 3 by (2),  and the other magic command line options of jsonlint.. you can probably kill off check_json.py and pretty_format_json.py in favor of "system" entries and reduce your  maintenance burden by 100+ SLOC.

For a small new dependency, seems like a pretty good deal.  Let me know if you're interested in a PR.

**Comment by asottile** [comment]
`system` hooks defeat the purpose of pre-commit.  The point is to isolate hook executables from the user's environment to allow for repeatable, no-installation execution.  That said, I think mirroring `demjson` sounds like a good idea to enable running of its tools! (or seeing if they'd be amenable to adding the necessary metadata to their repository to enable usage under pre-commit).

**Comment by mattvonrocketstein** [comment]
> system hooks defeat the purpose of pre-commit. The point is to isolate hook executables from the user's environment to allow for repeatable, no-installation execution. 

Not sure I see your point.  In this case isolation is still accomplished because demjson in setup.py is all that it takes to guarantee the jsonlint tool is available in (and only in) the virtualenv.  It's repeatable insofar as the demjson requirement would be pinned to a version or hash in setup.py's install_requires.  I assume that pre-commit "system" hooks are already taking advantage of what virtualenv changes about $PATH right, because I don't have jsonlint installed at the system level.

I'm not sure what you mean about mirroring and metadata.

**Comment by asottile** [comment]
The `pre-commit` framework takes `language: python` hooks and creates an isolated virtualenv for them.  This virtualenv is available during the execution of `language: python` hooks configured for that repository.  A `language: system` hook requires the user of `pre-commit` to install / set up / maintain requirements external to the configured hooks requiring the committer to have specific things on the path.  These sorts of hooks are not extremely portable to other committers to the repository and increase the barrier to entry to running pre-commit hooks.  If the installation is maintained entirely through pre-commit (as is done with `language:` `{ruby,node,python}`) the committer requires zero setup other than having pre-commit installed.

An example metadata needed for pre-commit to run: https://github.com/pre-commit/pre-commit-hooks/blob/3fa02652357ff0dbb42b5bc78c673b7bc105fcf3/hooks.yaml. You can find more about the format of this in the documentation: http://pre-commit.com/#new-hooks.  Take note that none of the hooks provided by this repository are `language: system` :)

An example of a repository we mirror (to enable pre-commit for a tool): https://github.com/pre-commit/mirrors-yapf

The tool we use to set up / update mirrors: https://github.com/pre-commit/pre-commit-mirror-maker

**Comment by mattvonrocketstein** [comment]
As I understand it, the main point of the yapf mirror is to pin the version [here](https://github.com/pre-commit/mirrors-yapf/blob/master/setup.py#L7) without adding that (potentially unnecessary) dependency to the setup.py inside pre-commit-hooks.git. 

If demjson were used to reimplement strict [check-json](https://github.com/pre-commit/pre-commit-hooks/blob/master/setup.py#L45) and json-pretty, then the version would be pinned [here where simplejson is mentioned](https://github.com/pre-commit/pre-commit-hooks/blob/master/setup.py#L34).  The metadata goes [here](https://github.com/pre-commit/pre-commit-hooks/blob/master/hooks.yaml).  So what would the point of a separate repo/mirror?

**Comment by asottile** [comment]
That seems fine as well.  I'd prefer a mirror if we're using it as an application and not as a library (to avoid growing the scope of this repository).  Do you forsee using it as a library or more as an application?

**Comment by hoshsadiq** [comment]
Any update on this?

**Comment by asottile** [comment]
None as far as I know -- might be a good idea to make a github issue suggesting `pre-commit` integration in the `demjson` project: https://github.com/dmeranda/demjson

They'd add a `.pre-commit-hooks.yaml` to their repository similar to this:

```yaml
-   id: jsonlint
    name: jsonlint
    description: Run demjson's jsonlint across json files
    entry: jsonlint
    language: python
    types: [json]
```

**Comment by hoshsadiq** [comment]
>  might be a good idea to make a github issue suggesting pre-commit integration in the demjson project: https://github.com/dmeranda/demjson


Afaik the developer sees it as feature complete and does not develop it any more nor does he accept PR any more.

Hence why perhaps better if pre-commit maintains a mirror.

**Comment by asottile** [comment]
Let's at least try a PR first -- maybe I'm not looking in the right place but it doesn't seem like PRs _aren't_ being accepted

**Comment by asottile** [comment]
I don't think this is moving forward so I'm closing it

**Comment by maresb** [comment]
For anyone who lands here searching for a pre-commit hook to handle non-strict JSON, I just put together a very simple hook called [check-json5](https://gitlab.com/bmares/check-json5). It's a drop-in replacement for `check-json`, so unfortunately it does no linting.

(I don't use the seemingly very dead demjson library proposed here.)
