### ISSUE TITLE
Non-utf8 file will cause trailing-whitespace to truncate the file contents

### ISSUE THREAD

**Issue by Lucas-C** [pre-commit/pre-commit-hooks#134]
Hi,

(I started investigating this in https://github.com/pre-commit/pre-commit/issues/397)

Bug reproductions steps, after setting up a git repository with the "trailing-whitespace" pre-commit hook installed (with the latest sha: 775a7906cd6004bec2401a85ed16d5b3540d2f94):
```
echo -en '\x3c\x61\x3e\xe9\x20\x0a\x3c\x2f\x61\x3e' > minimal_crasher.xml
git add minimal_crasher.xml
pre-commit run trailing-whitespace --files minimal_crasher.xml
```

Results in:
````
Trim Trailing Whitespace...............................................................................................................................................................Failed
hookid: trailing-whitespace

Files were modified by this hook. Additional output:

Fixing minimal_crasher.xml
Traceback (most recent call last):
  File "/home/lucas_cimon/.pre-commit/repok3wjweh4/py_env-default/bin/trailing-whitespace-fixer", line 9, in <module>
    load_entry_point('pre-commit-hooks==0.6.0', 'console_scripts', 'trailing-whitespace-fixer')()
  File "/home/lucas_cimon/.pre-commit/repok3wjweh4/py_env-default/lib/python3.4/site-packages/pre_commit_hooks/trailing_whitespace_fixer.py", line 71, in fix_trailing_whitespace
    _fix_file(bad_whitespace_file, all_markdown or extension in md_exts)
  File "/home/lucas_cimon/.pre-commit/repok3wjweh4/py_env-default/lib/python3.4/site-packages/pre_commit_hooks/trailing_whitespace_fixer.py", line 12, in _fix_file
    for line in fileinput.input([filename], inplace=True):
  File "/usr/lib/python3.4/fileinput.py", line 263, in __next__
    line = self.readline()
  File "/usr/lib/python3.4/fileinput.py", line 363, in readline
    self._buffer = self._file.readlines(self._bufsize)
  File "/home/lucas_cimon/.pre-commit/repok3wjweh4/py_env-default/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 3: invalid continuation byte
```

And **all the content of `minimal_crasher.xml` lost** !!

In this test the xml file is very small, but it can happen with any file size nor number of staged modifications !

**Comment by asottile** [comment]
I believe this to be unrelated to the other bug (I can't get the other bug to reproduce with this alone).

That said, this should somehow attempt to handle non-utf8 files, but the question is how?

### Ignore them
If we ignore non-utf8 files they'll silently remain unchanged

### Process them as bytes
We may mangle binary files

What tradeoff should we take?

**Comment by asottile** [comment]
For this specific bug, you can recover the original contents with `git checkout -- thatfile`

When coupled with pre-commit/pre-commit#397 you'll need `git checkout -- thatfile` and then you'll need to manually apply the patch file in ~/.pre-commit/patch... (whatever the last one is)

**Comment by Lucas-C** [comment]
I just uploaded a PR to fix the current bug: the file truncation.

About the tradeoffs, I would opt for a third solution: adding a a list of Python-supported file encoding as parameter to the trailing-whitespace hook.
The hook would try to open the files with each of those encoding sequentially, as long as it gets an exception.
Hence we could support popular file formats like UTF8 & Latin1, without any risk to mangle binary files, and full control over this behaviour given to the user.

**Comment by asottile** [comment]
To be frank, it's almost always a bug if a file does not have a utf-8 encoding.  I'm not sure I would want to add complexity to support that.

**Comment by asottile** [comment]
I actually think the second option is reasonably safe, the list of extensions that this repository provides are all text files (and if someone was running this hook against non-utf8 files they'd already be hitting this bug) so I think it's a safe change as well.

Then we wouldn't need any exception handling code since it'd just handle it gracefully.

**Comment by Lucas-C** [comment]
I'm actually a user with non-UTF8 files in its git repo :)
They are fixture files especially useful to have tests ensuring our product is robust enough to handle non UTF8 encodings.

If this hooks only handle UTF8 files, I would have to use a `exclude` rule in `.pre-commit-config.yaml` for each non UTF8 file in my repo :(
If you prefer option 1, then please at least rename that hook `trailing-whitespace-utf8` !

I'm ok for option 2, even if it is less safe IMHO.

I updated the PR with some slight changes by the way.

**Comment by asottile** [comment]
Yeah let's go with option 2, want to take a first stab at it?

**Comment by Lucas-C** [comment]
Ok.
I'm going to do this tomorrow, and I'll wait for the 1st PR to get tour approval.
