### ISSUE TITLE
IOError with git submodules: in Detect AWS credentials and private key

### ISSUE THREAD

**Issue by manquer** [pre-commit/pre-commit-hooks#140]
Throwing a error on git submodules . 
Likely because it is file from git perspective actually is directory on drive ?
```
Traceback (most recent call last):
  File "~/.pre-commit/repoDZTjYO/py_env-default/bin/detect-aws-credentials", line 9, in <module>
    load_entry_point('pre-commit-hooks==0.6.0', 'console_scripts', 'detect-aws-credentials')()
  File "~/.pre-commit/repoDZTjYO/py_env-default/lib/python2.7/site-packages/pre_commit_hooks/detect_aws_credentials.py", line 62, in main
    bad_filenames = check_file_for_aws_keys(args.filenames, keys)
  File "~/.pre-commit/repoDZTjYO/py_env-default/lib/python2.7/site-packages/pre_commit_hooks/detect_aws_credentials.py", line 31, in check_file_for_aws_keys
    with open(filename, 'r') as content:
IOError: [Errno 21] Is a directory: 'console/data/report'
```

**Comment by chriskuehl** [comment]
Thanks for the issue! I also know those hooks have this same problem with symlinks.

I started a branch a while ago which adds support for usefully targeting the different types of git objects and would solve this: https://github.com/pre-commit/pre-commit/pull/329

...but it's not really ready to ship.

In the mean-time, fixing these hooks to work around it seems pretty reasonable.

Alternatively, you can also avoid on a per-project basis by excluding submodules via the `.pre-commit-config.yaml` file in your project.

**Comment by asottile** [comment]
Here's the issue to follow as well: https://github.com/pre-commit/pre-commit/issues/191

I think it's probably not worth adding special code to every single hook which acts on files?  We've been working around this by adding:

```yaml
exclude: ^(submodule/path|symlink/path)$
```

to these specific hooks.

@manquer does that work for you?  Is enough to close this issue in favor of the other issue + PR?

**Comment by manquer** [comment]
@asottile thx ! yeah this works for me..  
it is only a problem if a special file is staged not on every commit,
