### ISSUE TITLE
Documenation for pretty-format-json

### ISSUE THREAD

**Issue by awebdeveloper** [pre-commit/pre-commit-hooks#156]
where is the documention for pretty-format-json

what linting do i have to confirm to

**Comment by asottile** [comment]
By default, it will sort keys and indent by `--indent` spaces (defaults to 4).  There's additional options for controlling key order https://github.com/pre-commit/pre-commit-hooks/blob/52582865ab7ed8f41734253190844c854ddd9a9e/pre_commit_hooks/pretty_format_json.py#L60-L85

I think the README mentions this but perhaps it could be elaborated on?

**Comment by awebdeveloper** [comment]
ys the docs needs to say how do i make my code confirm to this linter.

eg:- keys needs to sorted alphabetically unless disabled
        default indentation is 4 unless overridden
