### ISSUE TITLE
Shell script file arguments with spaces doesn't work perfectly

### ISSUE THREAD

**Issue by anuragagarwal561994** [pre-commit/pre-commit-hooks#171]
If we are writing a shell script that takes in file paths as arguments, there can be a possibility that a path might be having spaces in between which will break the script as from the space it will become a new argument.

**Comment by asottile** [comment]
This is probably supposed to be an issue on pre-commit/pre-commit?

You'll need to be more specific and provide an example -- there's tests that ensure files with spaces are handled correctly.

**Comment by asottile** [comment]
Please reopen this issue against pre-commit/pre-commit with an example -- thanks!

**Comment by anuragagarwal561994** [comment]
Sorry I think it was false positive earlier and I should have reported it in right repository.
