### ISSUE TITLE
Explain why some of these are needed

### ISSUE THREAD

**Issue by awebdeveloper** [pre-commit/pre-commit-hooks#178]
Why is `check-byte-order-marker` needed or `end-of-file-fixer` needed

**Comment by asottile** [comment]
check-byte-order-marker: UTF-8 encoded files do not (and generally should not) have the UTF-8 byte order marker, this hook ensures that they do not
end-of-file-fixer: commonly people either 1. forget to end files in newlines or 2. end the file in many newlines, this hook ensures that the file only ends in a single newline.

**Comment by awebdeveloper** [comment]
why is it a issue with byte code marker being there

**Comment by asottile** [comment]
Here's what I usually link to with regards to the UTF-8 byte order marker: http://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom/2223926#2223926

> Normally, the BOM is used to signal the endianness of an encoding, but since endianness is irrelevant to UTF-8, the BOM is unnecessary. 

Notably the UTF-8 BOM is *not recommended*.

It can also cause problems with tools which do not expect the BOM (most of them).

**Comment by awebdeveloper** [comment]
Could one line be added explaining why some of these are needed.

**Comment by asottile** [comment]
Sure!  Feel free to open a pull request adding information that you believe is missing :)

**Comment by awebdeveloper** [comment]
sure will give it a shot
