### ISSUE TITLE
django tests.py is not handled properly

### ISSUE THREAD

**Issue by oliver-zhou** [pre-commit/pre-commit-hooks#181]
Issue in #88 introduced a minor bug.

Django creates "tests.py" as the default test file name when you run `./manage.py startapp` and now pre-commit-hooks doesn't handle it properly, seeking only files with test_*.py

Since the last fix added os.path.basename, we're always working with the filename, and should return to using test.*.py

Additionally - readme.md still references test*.py as well, and not test_*.py

The ultra-best-right way to handle this would be to handle it how python does it. unittest.TestLoader.discover does it by allowing any pattern, defaulting to test.py when no argument is provided.

https://github.com/python/cpython/blob/master/Lib/unittest/loader.py 
    def discover(self, start_dir, pattern='test*.py', top_level_dir=None):

**Comment by asottile** [comment]
via #182
