### ISSUE TITLE
Allow pre-push interaction with git-lfs

### ISSUE THREAD

**Issue by chbndrhnns** [pre-commit/pre-commit-hooks#183]
If I have `pre-push` checks in place and install git-lfs before precommit, I receive the message

```
Running in migration mode with existing hooks at /Users/****/.git/hooks/pre-push.legacy
Use -f to use only pre-commit.
```

If I do git lfs update after precommit is installed, i receive

```
Hook already exists: pre-push

#!/usr/bin/env bash
# This is a randomish md5 to identify this script
# 138fd403232d2ddd5efb44317e38bf03

pushd `dirname $0` > /dev/null
HERE=`pwd`
popd > /dev/null

retv=0
args=""

ENV_PYTHON='/Users/****in/python2.7'
SKIP_ON_MISSING_CONF=false

which pre-commit >& /dev/null
WHICH_RETV=$?
"$ENV_PYTHON" -c 'import pre_commit.main' >& /dev/null
ENV_PYTHON_RETV=$?
python -c 'import pre_commit.main' >& /dev/null
PYTHON_RETV=$?


if ((
        (WHICH_RETV != 0) &&
        (ENV_PYTHON_RETV != 0) &&
        (PYTHON_RETV != 0)
)); then
    echo '`pre-push` not found.  Did you forget to activate your virtualenv?'
    exit 1
fi


# Run the legacy pre-commit if it exists
if [ -x "$HERE"/pre-push.legacy ]; then
    "$HERE"/pre-push.legacy
    if [ $? -ne 0 ]; then
        retv=1
    fi
fi

CONF_FILE=$(git rev-parse --show-toplevel)"/.pre-commit-config.yaml"
if [ ! -f $CONF_FILE  ]; then
    if [ $SKIP_ON_MISSING_CONF = true ] || [ ! -z $PRE_COMMIT_ALLOW_NO_CONFIG ]; then
        echo '

To resolve this, either:
  1: run `git lfs update --manual` for instructions on how to merge hooks.
  2: run `git lfs update --force` to overwrite your hook.
```

Is there any solution to this behavior?

**Comment by asottile** [comment]
`git-lfs` functions by (ab)using the `pre-push` hook.  I don't think there's a way to resolve this conflict *and* use pre-commit's `pre-push` hook without modifications from the `git-lfs` side.  I believe the problem is on `git-lfs`'s side as pre-commit will still run `git-lfs`'s pre-push hook (as `pre-push.legacy`) and the pre-push hook will still function.

**Comment by asottile** [comment]
This issue is probably also on the wrong project.  This project is a set of out-of-the-box hooks for the pre-commit framework.  The framework itself (and its issues) live at https://github.com/pre-commit/pre-commit

**Comment by chbndrhnns** [comment]
Yeah, sorry for posting it in the wrong project. I will post it on the other project and have few hope to get it fixed because of your (valid) explanation.
