### ISSUE TITLE
Report exact python version in case of check-ast parse error

### ISSUE THREAD

**Issue by ulope** [pre-commit/pre-commit-hooks#191]
The `check-ast` hook only reports the executable name in case of a parse error. That is however sometimes not very helpful since it's mostly `python2` and `python3`.

I propose to use `sys.version.partition(" ")[0]` instead of `interpreter` in https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_ast.py#L26

**Comment by asottile** [comment]
Sounds good to me!  Let's just do all of `sys.version` for the pypy folks -- want to make a PR?

**Comment by ulope** [comment]
Sure I'll create a PR. 
Are you sure about using the whole of `sys.version`? That's quite long and also possibly multiline.

I'd suggest to use `"{} {}".format(platform.python_implementation(), sys.version.partition(" ")[0])` instead. Example output:
* CPython 2.7.11
* CPython 3.3.6
* CPython 3.6.1
* PyPy 3.2.5
* Jython 2.7.0

**Comment by asottile** [comment]
That works too!
