### ISSUE TITLE
Argument for ignoring certain files with the detect-private-key hook

### ISSUE THREAD

**Issue by bsbates** [pre-commit/pre-commit-hooks#192]
It would be great if the pre-commit hook for detecting private keys could be passed an argument for files to ignore, something like `--ignored-files`.  My use case is having private keys in my testing code, in particular, testing asymmetric jwt decryption.

I can skip individual rules on a per-commit basis (using `SKIP`), but parts of my build pipeline run all files through the pre-commit hooks to check for errors. As far as I know, there is no way in pre-commit to specify files that are globally ignored. 

It would be a bonus if the hook trimmed the whitespace of the args after splitting them, so they can be pretty printed in a yml file:
```
hooks:
-   id: detect-private-key
    args:
    - --ignored-files
    - __tests__/my-test.secret.key,
      __tests__/my-other-test.secret.key
```

**Comment by asottile** [comment]
pre-commit supports `exclude:` I think that's what you're looking for :) http://pre-commit.com/#install

**Comment by bsbates** [comment]
Thanks! I must have missed that in the documentation. I will try that out.
