### ISSUE TITLE
no-commit-to-branch is not present

### ISSUE THREAD

**Issue by elaichi** [pre-commit/pre-commit-hooks#197]
My `.pre-commit-config.yaml` looks like this:
```
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.7.1
    hooks:
    -   id: no-commit-to-branch
```

and I'm getting this:
```
❯ pre-commit run
[ERROR] `no-commit-to-branch` is not present in repository 
https://github.com/pre-commit/pre-commit-hooks.git.  Typo? 
Perhaps it is introduced in a newer version? 
Often `pre-commit autoupdate` fixes this.
```

According to `pre-commit autoupdate` I'm already on the latest release.
Any ideas what could be going on here?
Thanks!

**Comment by asottile** [comment]
Looks like a new release hasn't been made yet in pre-commit-hooks, I'll go ahead and do that right now.

You can use `pre-commit autoupdate --bleeding-edge` to get a newer-than-tagged version btw

**Comment by asottile** [comment]
I've made `v0.8.0` available (`autoupdate` will now choose that tag over `v0.7.1`)
