### ISSUE TITLE
Isolate test environment

### ISSUE THREAD

**Issue by nagromc** [pre-commit/pre-commit-hooks#198]
```shell-session
$ sudo apt install python-tox
$ cd pre-commit-hooks
$ pip install -r requirements-dev.txt
$ make test
```

gives the following output: https://gist.github.com/nagromc/8d44fa7c3fcddcc0af35fe5d9f789c70#file-make-test-output-txt

After some investigation, I found out my Git configuration was interfering with the tests.

I think the tests should be independent from the environment either by:
- running `env HOME=/tmp make test` (to change temporarily the `HOME` and then ignore my existing Git configuration `~/.gitconfig`);
- or doing a (Python|Docker|Vagrant) trick to isolate the test environment.

**Comment by asottile** [comment]
Actually, I think we should just add the other case to this test -- it _is_ a valid way that a user space git could end up in a merge conflict (if you look, we already have two different formats of git conflict output already).

docker / vagrant would be _super_ overkill for this (and making debugging an absolute nightmare).

**Comment by asottile** [comment]
What specifically is in your `.gitconfig` (I'm trying to reproduce this locally so I can improve the testsuite!)

**Comment by nagromc** [comment]
Here is my [`~/.gitconfig`](https://github.com/nagromc/dotfiles/blob/master/git/gitconfig).

**Comment by asottile** [comment]
fwiw, this is the bit that causes the different behaviour:

```ini
[pull]
    rebase = preserve
```

I'll fix up the test suite so it also allows this :)

**Comment by asottile** [comment]
Actually, hmm this may require more thought since it is no longer a merge conflict but now a *rebase* conflict. (Fixing the assertion in the testsuite causes the test to fail as it is not detected as a merge conflict)

**Comment by nagromc** [comment]
The [tests failed](https://gist.github.com/nagromc/8d44fa7c3fcddcc0af35fe5d9f789c70#file-make-test-gpgsign-output-txt) as well with [`git config --global commit.gpgSign true`](https://github.com/nagromc/dotfiles/blob/b32d7ca594f94c79dc54e9d6b4e4c8445d693b8d/git/gitconfig#L150) without my USB smartcard inserted.

pre-commit-hooks v0.9.1

**Comment by asottile** [comment]
This should fix that: https://github.com/pre-commit/pre-commit-hooks/pull/212

**Comment by nagromc** [comment]
Bug fixed in 10 minutes. Wow :+1:
