### ISSUE TITLE
flake8 hook and python3

### ISSUE THREAD

**Issue by elaichi** [pre-commit/pre-commit-hooks#208]
Hi there,
some of our repos use python3 and we just realized that the `flake8` pre-commit hook doesn't seem to be aware of it. In brief, we're experiencing this issue:
https://gitlab.com/pycqa/flake8/issues/294

Here's the relevant section of our `.pre-commit-config.yaml`:
```
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.8.0
    hooks:
    -   id: flake8
        args:
        - '--config=.flake8'
```

Running `flake8` (after `pip install`) directly on the files works fine.
 
Any suggestions? Thanks!

**Comment by asottile** [comment]
I believe you'll be interested in [this option] (http://pre-commit.com/#overriding-language-version) :D

**Comment by asottile** [comment]
@elaichi did `language_version: python3` (or a more specific version) work for you?

**Comment by elaichi** [comment]
@asottile yes it did, thanks!
