### ISSUE TITLE
Hook to reject or warn about case changes in filenames

### ISSUE THREAD

**Issue by guykisel** [pre-commit/pre-commit-hooks#21]
In case sensitive filesystems, you could commit two files that have the same name but with different case (`myfile.txt` vs `MyFile.txt`), but then if these are checked out into a case insensitive filesystem, the results are unpredictable. A hook to warn or reject commits that result in these sorts of filenames would be nice.

**Comment by asottile** [comment]
+1 this is a great idea

lmk if you want me to take a stab at this :)

**Comment by guykisel** [comment]
I was going to give it a try when I have time, but it won't hurt my feelings if you do it instead!

**Comment by guykisel** [comment]
This was implemented in #22
