### ISSUE TITLE
New hook to reject commit if a specific file has changed and user not in group

### ISSUE THREAD

**Issue by dirkharrington** [pre-commit/pre-commit-hooks#214]
An example use case would be:

- Jenkinsfile is in the commit
- The author of the commit is not in group "JenkinsfileModifiers"

**Comment by asottile** [comment]
While this is possible with `pre-commit`, access control is probably best achieved through `pre-receive` (though the pre-commit tool *can* be used to implement pre-receive hooks as well!).  Just a small reminder that pre-commit is easy to bypass (either by disabling hooks, or running with `SKIP=...` or `--no-verify`).

**Comment by asottile** [comment]
That said: thanks for the hook idea! :tada:

**Comment by dirkharrington** [comment]
Ah yes! Sorry - certainly wasn't trying to imply pre-commit is the specific hook where this is desired ... just the end result is a rejection. 😄 

Keep up the awesome work!

**Comment by asottile** [comment]
This is probably too-specific for pre-commit/pre-commit-hooks but if you want to hack on this in a separate repository that'd be cool
