### ISSUE TITLE
trailing-whitespace doesn't seem to affect .yaml files

### ISSUE THREAD

**Issue by patrick-bohan** [pre-commit/pre-commit-hooks#220]
I noticed that in v0.7.1 (and v0.9.1) `trailing-whitespace` doesn't seem to work on .yaml files.

**Comment by asottile** [comment]
Here's some debugging I did on this:

```
$ python -m identify.cli .pre-commit-config.yaml 
["file", "non-executable", "text", "yaml"]
```

Ok, so identify thinks that the `.yaml` file is indeed yaml, now let's try with pre-commit itself:

## pre-commit 0.15.3 + pre-commit-hooks 0.7.1 (too old to utilize `identify`)
```
$ grep -C1 pre-commit-hooks .pre-commit-config.yaml 
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
$ nano .pre-commit.config.yaml  # add trailing whitespace somewhere
$ pre-commit run trailing-whitespace --all-files
Trim Trailing Whitespace.................................................Failed
hookid: trailing-whitespace

Files were modified by this hook. Additional output:

Fixing .pre-commit-config.yaml
```

## pre-commit 0.15.3 + pre-commit-hooks 0.9.1

```
$ grep -C1 pre-commit-hooks .pre-commit-config.yaml 
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
$ nano .pre-commit-config.yaml  # add trailing whitespace somewhere
$ pre-commit run trailing-whitespace --all-files
Trim Trailing Whitespace.................................................Failed
hookid: trailing-whitespace

Files were modified by this hook. Additional output:

Fixing .pre-commit-config.yaml

```

So I'm having a difficult time reproducing this!  Can you provide some steps to reproduce what you're seeing?  The following will be useful: `pre-commit --version`, the contents of your `.pre-commit-config.yaml` and `git status`.

**Comment by asottile** [comment]
@patrick-bohan  any updates?

**Comment by patrick-bohan** [comment]
I did check this out again and couldn't reproduce, so I'm going to close. Sorry for the noise!
