### ISSUE TITLE
debug-statements ast syntax hiccup

### ISSUE THREAD

**Issue by arahayrabedian** [pre-commit/pre-commit-hooks#226]
So I was doing an awkward code thing and had the `debug-statements` hook choke, the code in question:

```python
def done(self, form_list, **kwargs):
        survey = ShoppingSurvey(
            user=self.request.user,
            **self.get_all_cleaned_data(),
            # ask yourself, is this a safe thing to do?
        )
        survey.save()
        return HttpResponseRedirect('/experiment?donezies=true')
```
as part of a django CBV

`debug-statements` failed with:

```
formulator/predictiforms/views.py - Could not parse ast

	Traceback (most recent call last):
	  File "/home/ara/.pre-commit/repoFmfBTu/py_env-default/local/lib/python2.7/site-packages/pre_commit_hooks/debug_statement_hook.py", line 38, in check_file_for_debug_statements
	    ast_obj = ast.parse(open(filename).read(), filename=filename)
	  File "/usr/lib/python2.7/ast.py", line 37, in parse
	    return compile(source, filename, mode, PyCF_ONLY_AST)
	  File "formulator/predictiforms/views.py", line 23
	    **self.get_all_cleaned_data(),
	                                 ^
	SyntaxError: invalid syntax
```

whereas this code executes just fine in the view, I tried shuffling a few things around and equivalent code then commits just fine (move `self.get_all_cleaned_data()` to a variable and ** that variable in)

**Comment by arahayrabedian** [comment]
should this be raised with `ast` or somewhere else instead?

**Comment by asottile** [comment]
You'll want to use `language_version: python 3.6` if you have python 3.6 code that needs linting (or upgrade to the latest version of pre-commit might help as there was smarter language detection added recently)

**Comment by arahayrabedian** [comment]
wow, i learnt something today... was not aware there were enhancements to dictionary unpacking...

for anybody else facing similar issues - [PEP448](https://www.python.org/dev/peps/pep-0448/)

@asottile please correct me if I learnt the wrong lesson ^^

**Comment by asottile** [comment]
Indeed you are correct :D
