### ISSUE TITLE
Use pre-commit from local repo

### ISSUE THREAD

**Issue by YordanBorisov** [pre-commit/pre-commit-hooks#248]
Hi,

If I have a local repo defined with developed by me hook how can I use it
in the command pre-commit run <my-hook-id>?

**Comment by asottile** [comment]
Are you perhaps looking for [developing hooks interactively](http://pre-commit.com/#developing-hooks-interactively)?

**Comment by YordanBorisov** [comment]
Thanks for the information I will try.

**Comment by YordanBorisov** [comment]
For that test how I can install package additional?

**Comment by asottile** [comment]
You'll want to either add them to your setup.py or use [`additional_dependencies`](http://pre-commit.com/#pre-commit-configyaml---hooks)
