### ISSUE TITLE
Hook to run pip-review on requirements.txt

### ISSUE THREAD

**Issue by guykisel** [pre-commit/pre-commit-hooks#26]
https://github.com/nvie/pip-tools includes a utility called pip-review that compares currently installed python packages to the latest versions available online (and optionally automatically updates them). I'm thinking it might be handy to have a hook that runs this (and updates requirements.txt?) automatically. Then again, pinned versions are often intentional due to compatibility issues with newer releases of packages. I'm opening this ticket to get opinions on whether something along these lines could possibly be a good idea.

**Comment by struys** [comment]
Historically we've always only made hooks that have no side effects on the executing code, people should be able to run tests and commit without having to test over again. Also people would get into the habit of constantly skipping this hook. It seems like a cool tool to have in a project, I just don't think it would be a great pre-commit hook.

**Comment by guykisel** [comment]
Makes sense. Thanks for the feedback!
