### ISSUE TITLE
no-commit-to-branch on CI

### ISSUE THREAD

**Issue by hectorv** [pre-commit/pre-commit-hooks#265]
As a safety net, we've started running pre-commit on CI, e.g.
```
git diff --name-only "$GIT_COMMIT"^..."$GIT_COMMIT" | xargs pre-commit run --files
```

one of our projects uses `no-commit-to-branch` and we just noticed this behavior on CI:
```
Don't commit to branch...................................................Failed
hookid: no-commit-to-branch

Traceback (most recent call last):
  File "/var/lib/jenkins/.cache/pre-commit/repoVUdrA6/py_env-python2.7/bin/no-commit-to-branch", line 11, in <module>
    load_entry_point('pre-commit-hooks==1.1.0', 'console_scripts', 'no-commit-to-branch')()
  File "/var/lib/jenkins/.cache/pre-commit/repoVUdrA6/py_env-python2.7/local/lib/python2.7/site-packages/pre_commit_hooks/no_commit_to_branch.py", line 22, in main
    return int(is_on_branch(args.branch))
  File "/var/lib/jenkins/.cache/pre-commit/repoVUdrA6/py_env-python2.7/local/lib/python2.7/site-packages/pre_commit_hooks/no_commit_to_branch.py", line 10, in is_on_branch
    branch = cmd_output('git', 'symbolic-ref', 'HEAD')
  File "/var/lib/jenkins/.cache/pre-commit/repoVUdrA6/py_env-python2.7/local/lib/python2.7/site-packages/pre_commit_hooks/util.py", line 28, in cmd_output
    raise CalledProcessError(cmd, retcode, proc.returncode, stdout, stderr)
pre_commit_hooks.util.CalledProcessError: (('git', 'symbolic-ref', 'HEAD'), 0, 128, u'', u'fatal: ref HEAD is not a symbolic ref\n')
```

most likely this is not really an issue with `pre-commit` but with the way our Jenkins jobs are set up (?). I worked around this by using `SKIP=no-commit-to-branch pre-commit run` but just thought I would let you know.

**Comment by asottile** [comment]
Thanks for the report!  Looks like this hook false-positives when not on a branch (as is likely in CI).

I'll add a quick check for that :)

**Comment by asottile** [comment]
This has been released as part of [v1.2.1](https://github.com/pre-commit/pre-commit-hooks/releases/tag/v1.2.1)!

**Comment by JulianVolodia** [comment]
Hi @asottile I try to understand how no-commit-to-branch should work duing CI on BitBucket.

I have 2 pipelines. Test and deploy.
For any PR - test is running.
For merges to develop - test and then deploy.

I struggle when have `no-commit-to-branch` hook on test pipeline. It blocking commits to develop/master but likely dislike this too.

https://github.com/pre-commit/pre-commit-hooks#no-commit-to-branch says only about branches but --no-ff merges are commits and pipelines think they are.

Do You have any thoughts about how this workflow with specific hook should be done?

Thanks in advance for any response.

**Comment by asottile** [comment]
@JulianVolodia your question is unrelated to this issue -- in the future I'd encourage you to create a new issue for unrelated things

if it doesn't apply in some scenario you can always utilize [`SKIP`](https://pre-commit.com/#temporarily-disabling-hooks)

(locking because off-topic)
