### ISSUE TITLE
trailing-whitespace fixer getting false positive

### ISSUE THREAD

**Issue by fractos** [pre-commit/pre-commit-hooks#270]
While bringing some Terraform files under pre-commit control, I've noticed an issue with files that do not have trailing whitespace but which are being flagged as needing fixing by the `trailing-whitespace` hook, which is causing a Travis CI build to fail unexpectedly. The files in question seem to trigger because they do not end in a newline, and I believe this to be incorrect behaviour for this hook.

Example repo: https://github.com/digirati-co-uk/pre-commit-hooks-test

This is using v1.2.1 of the pre-commit-hooks repo.

![pre-commit-hooks-test-screenshot](https://user-images.githubusercontent.com/657772/36797780-c2a0343a-1ca0-11e8-8ae3-2e3f4a53e8a0.PNG)

**Comment by asottile** [comment]
👍 thanks for the great report.

This is indeed a problem with the hook, I'll see if I can't get a fix out for it :)

Fixing end-of-file is the job of `end-of-file-fixer` so this hook shouldn't be doing that!

**Comment by fractos** [comment]
Awesome! Thanks for the quick turnaround!

**Comment by asottile** [comment]
This is available in [v1.2.2](https://github.com/pre-commit/pre-commit-hooks/releases/tag/v1.2.2)!

Thanks again for the issue :)

**Comment by asottile** [comment]
Oops 1.2.2 is broken -- use 1.2.3 instead :D

**Comment by fractos** [comment]
Roger that! Thanks again :D

**Comment by fractos** [comment]
Nice one!
![trailing-whitespace-hook-fixed](https://user-images.githubusercontent.com/657772/36840609-7e81c366-1d3d-11e8-85d5-f24eb8eceb3c.PNG)
