### ISSUE TITLE
Check-yaml exception for Ansible Vault

### ISSUE THREAD

**Issue by blackillzone** [pre-commit/pre-commit-hooks#273]
Hi,

I've recently used the [embed encrypt variables](https://docs.ansible.com/ansible/latest/vault.html#encrypt-string-for-use-in-yaml) in my Ansible repos, and the check-yaml hook is failing because of the specific `!vault` usage.

```
Check Yaml...............................................................Failed
hookid: check-yaml

could not determine a constructor for the tag '!vault'
  in "inventories/group_vars/all.yml", line 62, column 13
```

Do you think it's possible to add this as an exception inside the hook (and make it pass for everyone who's using encypted variables in their playbooks) ?

Or should I add explicit exception inside my `.pre-commit-config.yaml`, for each files where I use those encrypted variables ?

**Comment by asottile** [comment]
Might be with adding a "check-yaml-unsafe" which just attempts to validate syntax (and thus allowing extensions and unsafe constructs) instead of loading. Wouldn't be able to do some of the more advanced ideas I have for check-yaml such as duplicate key checking but it would enable this use case.

Thoughts?

**Comment by asottile** [comment]
Made a patch for this, please try it out!  #274 (via `args: [--unsafe]`)

**Comment by blackillzone** [comment]
Working like a charm for me and this use case ! Thank you for this quick patch :).

Looking at the PR, there is a small type error on line 55 in the `README.md`, and on line 45 in `pre_commit_hooks/check_yaml.py` : 
```
--unsafe` - Instaed of loading the files, simply parse them for syntax.
```

**Comment by asottile** [comment]
This has been (finally!) released as part of [v1.3.0](https://github.com/pre-commit/pre-commit-hooks/releases/tag/v1.3.0)! 🎉

**Comment by ssbarnea** [comment]
I am not sure that is the best approach but thanks for implementig that workaround.

**Comment by asottile** [comment]
@ssbarnea do you have any suggestions?

**Comment by ViViDboarder** [comment]
This is old, but the ability to ignore a single line would be one way to handle this and is a fairly common feature for linters.

**Comment by asottile** [comment]
@ViViDboarder did you try the solution that's been released above in 2018?

**Comment by ViViDboarder** [comment]
Yes, that works but it apparently prevents the other handy features such as checking for duplicate keys, no?

**Comment by asottile** [comment]
yeah, yaml loading is all-or-nothing
