### ISSUE TITLE
requirements-txt-fixer: auto fix = to ==

### ISSUE THREAD

**Issue by vcajes** [pre-commit/pre-commit-hooks#284]
Currently, the **requirements-txt-fixer** is not fixing this kind of entries: **libraryname=1.0**
The problem is quite simple and happens very often when people forget to add the second **=** sign. Do you think that fixing this **libraryname=1.0** to **libraryname==1.0** would be a great idea? From time to time we have CI tests failing because we didn't catch this typo.

**Comment by asottile** [comment]
:+1: should be an easy patch. There's a bit of an edge case with `git+...#egg=foo` that you'll want to look out for

**Comment by asottile** [comment]
see https://github.com/pre-commit/pre-commit-hooks/pull/330#issuecomment-517927115
