### ISSUE TITLE
Unexpect behavior with flake8 hook?

### ISSUE THREAD

**Issue by abravalheri** [pre-commit/pre-commit-hooks#295]
Considering a python package repository using `setup.cfg` and with the `flake8` pre-commit hook installed, when a person adds a `[flake8]` section to the `setup.cfg` file, with an `exclude` option, this person would naturally expects that the commit hook ignores the files/directories listed...

However, since pre-commit sends as arguments a list of changed files, this configuration is somehow neglected, and flake8 lints the excluded files anyway...

So if we run `pre-commit run flake8 -a`, we end up with a different result then just running `flake8`.

Is this behavior expected/documented somewhere?

I have create an example repository to make it easy to reproduce:

```bash
git clone https://github.com/abravalheri/dummy-pre-commit-example-for-issue
cd dummy-pre-commit-example-for-issue
grep "\[flake8\]" setup.cfg -A 9  # --> Check the configuration
pre-commit install
flake8  # --> results more or less expected by the user
pre-commit run flake8 -a  # --> different from the previous results
```

Any tips about this?

**Comment by asottile** [comment]
This is documented in flake8 itself, let me find the specifics -- generally I remove the `setup.cfg` setting and only invoke flake8 through pre-commit (and configure `exclude` there).

**Comment by asottile** [comment]
Actually, there's a direct duplicate in our project which links the context in flake8 itself: https://github.com/pre-commit/pre-commit-hooks/issues/112

**Comment by abravalheri** [comment]
Thank you very much @asottile !

(Sorry for not looking at the closed issues first :( My bad )

**Comment by asottile** [comment]
No problem! thanks for the issue 🎉
