### ISSUE TITLE
file corruption detection?

### ISSUE THREAD

**Issue by dvolgyes** [pre-commit/pre-commit-hooks#298]
Hi,

I have quite a lot of ideas for detecting corrupt files before committing. 
E.g. image files could be automatically detected with imagemagick convert,
video/audio with ffmpeg, most compressors can detect file errors, etc.
(And there are specific tools, e.g. mp3check, etc.)
But these are a bit platform specific, and require external softwares.

On the other hand, I also often find files which have wrong extensions.
E.g. the program saves jpeg, even when you give .png extension.
Using python-magic and mimetypes, it is not too hard to check
if the file content matches with the extension or not.
(But sometimes it is tricky, many files are detected as text,
but for text, mimetypes do not enumerate this extension, 
so a blacklist/whitelist would be needed.)

The question is: would these kind of corruption detector codes interesting
for merging back, or because they are a bit platform dependent, it
would be easier to maintain a separate repository?

For my experiments, I made a fork, I discarded most existing codes, 
and generated a quick and dirty example here: https://github.com/dvolgyes/pre-commit-hooks 

So the question is: is it interesting idea to get it polished, and merged back,
or should I keep it in my own repository after polishing?

**Comment by asottile** [comment]
Probably a separate repository.  I've even been meaning to split out the python-specific bits from this repository as well and keep this as the platform-agnostic, language-agnostic hooks.

**Comment by dvolgyes** [comment]
Thanks for the explanation. 
It would be nice to have a section somewhere about the available repositories. 
I mean I could search for the forks, but some of them are just forked for experiments,
or for a pull request, etc., and some of them, like your future separated python parts, are actually meant as a separate repository to keep things clear.
I am not sure about the format, e.g. could be a wiki, or a markdown file in the repository, or a section
somewhere on pre-commit.com in the contribution section, or a separate "awesome-.." repository, 
see https://github.com/sindresorhus/awesome

Anyway, i have quite specific ideas (linux+python), so i will polish my own version.

**Comment by asottile** [comment]
There is https://pre-commit.com/hooks.html 🎉 source: https://github.com/pre-commit/pre-commit.github.io

**Comment by dvolgyes** [comment]
You are absolutely right, I just somehow missed it. Thanks for the link.
