### ISSUE TITLE
pre-commit should have at least one spell-checker

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit-hooks#302]
Spellchecking in commit message, comments and source code is more than a trivial issue as git history cannot be realistically be changed and because spelling errors slipping into API do become the "norm" and they are very hard to fix later due to the need to avoid breaking the API.

I have not special speller in mind but I wanted to share with you experience about two of them:

* [cspell](https://www.npmjs.com/package/cspell) - nodejs based and official speller of vscode, proved to be easy to customize and easy to keep an in-repo dictionary. Only downside is that I would have preferred a python one, especially for CI purposes. 
* [topy](https://github.com/intgr/topy) - is python based and easy to use but is very hard to customize, due to https://github.com/intgr/topy/issues/19 I would advise not using it.

Update: https://github.com/Jason3S/cspell/issues/56 ticket would track adding the hook definition on cspell.

**Comment by rpdelaney** [comment]
Why not just use GNU `aspell`?

**Comment by ssbarnea** [comment]
I would prefer a tool that can easily be installed by pre-commit at runtime on most platforms, which means: python, nodejs or ruby based. Other approaches would make harder to assure succesfuly precommit installation. 

Currently I am using cpell on few projects but not as hook yet.

**Comment by peternewman** [comment]
I think we tick those boxes, and someone added a hook, although I see it's not listed and I get the feeling there's a step missing to run it from the pre-commit config: https://github.com/codespell-project/codespell/pull/1117

**Comment by ssbarnea** [comment]
I used cspell on a couple of projects and it proved to be a real PITA, issues with installation and also usage. I am going to five codespell a chance and see how it goes. Lets not close the ticket yet as there is a real need to spell code and also commit messages.

**Comment by asottile** [comment]
ah I'll add it to the website -- thanks @peternewman (that's handled through https://github.com/pre-commit/pre-commit.github.io)

**Comment by peternewman** [comment]
Thanks @asottile, yeah I'd seen that site, I was assuming people would need to do a bit more work to codespell, but I see the system essentially just calls the existing library/executable by default.

**Comment by asottile** [comment]
yep!  all that's needed is the little metadata file and `pre-commit` does the rest of the heavy lifting :)
