### ISSUE TITLE
can we prevent github UI merges?

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit-hooks#303]
While I love pre-commit I found one specific issue that I have no idea how to address which is unique to projects using github pull-requests:

how can I run pre-commit on merges done on PRs? 

When you merge using github web interface, you have the option to edit the commit message.... pre-commit not running on the message so an opportunity to merge a garbage message that was not linted.

Is there a way to avoid this on github? some hooks, services, project configuration?

On Gerrit there is no such problem because you do not have the option to edit message when is merged, so it should have already being validated.

**Comment by ssbarnea** [comment]
Sounds like a PITA. I hope someone will find and easier to use solution to this challenge. I don't mind using a bot but I don't like having to use magic comments to trigger it, is not obvious, especially for occasional contributors.

**Comment by asottile** [comment]
the magic comment was just an example, my ideal solution would be "maintainer approves => auto merge" -- this is doable with webhooks too as far as I know :)

**Comment by asottile** [comment]
closing: configuring github is a bit out of scope for `pre-commit` / `pre-commit-hooks` -- though hopefully I've nudged in the right direction with disabling merges via branch protection and checks :)
