### ISSUE TITLE
New pre-commit hooks for Java, Kotlin, Golang and YAML formatting

### ISSUE THREAD

**Issue by macisamuele** [pre-commit/pre-commit-hooks#307]
Hello maintainers,
I'm currently working on some projects Java/Kotlin based and I'd love to use pre-commit to ensure that the code respects a pre-determined code style, more or less what pep8 and autopep8-wrapper pre-commit hooks are doing for python.

I did create a temporary repository to test the potential new pre-commit hooks and I was wondering if it could make sense to integrate them here or if you rather prefer having a separate repository for it.

The current WIP repo is available on http://github.com/macisamuele/maci-pre-commit-hooks.

**Comment by asottile** [comment]
Would prefer separate repository.  Here's some of my thoughts on the future of this repo: https://github.com/pre-commit/pre-commit-hooks/issues/81#issuecomment-404858094

It would also be nice to add first class language support for jvm languages at some point in the framework

**Comment by macisamuele** [comment]
@asottile thanks a lot for your feedback. I didn’t noticed the comment on the previous issue.

I'll productionize the current WIP repo then. 
About having JVM support would be nice.
