### ISSUE TITLE
Flake8 detecting a type hint as a multiple statements line

### ISSUE THREAD

**Issue by maylonpedroso** [pre-commit/pre-commit-hooks#313]
I am getting "E701 multiple statements on one line (colon)" in this line with flake8:

**forecast: List[Forecast] = list()**

Seems like it is detecting "forecast:" as a for loop.

**Comment by asottile** [comment]
This is due to `pycodestyle`: https://github.com/PyCQA/pycodestyle/pull/640

A fix has been released for that but flake8 has not made a release in a long time: https://gitlab.com/pycqa/flake8/issues

**Comment by ssbarnea** [comment]
Was ok to close this ticket as I am not aware of a way to use the modern pycodestyle as pre-commit hook? #319
