### ISSUE TITLE
How about adding a flag as should run hook ?

### ISSUE THREAD

**Issue by splnanthakumar** [pre-commit/pre-commit-hooks#314]
Label: enhancement

Hi pre-commit team,
   
    As part of the requirement can we have one more flag to run a specific hook in pre-coomit.
the way SKIP is working, we can introduce one more environment variable something like "RUNWITH=hookname"

    can you guys please do this ?

**Comment by asottile** [comment]
This is the wrong place for such an issue, you want `pre-commit/pre-commit` -- also I'm not sure what your specific environment variable would do? what is your usecase here and how would it work?
