### ISSUE TITLE
end-of-file-fixer fails against a ".git/MERGE_MSG" file

### ISSUE THREAD

**Issue by revolter** [pre-commit/pre-commit-hooks#315]
I'm running `git merge --no-ff release-7.1.2 -m "Merge branch 'release-7.1.2' into master"` and it fails because it's incorrectly checking files inside the `.git` directory:

```
Fix End of Files.........................................................Failed
hookid: end-of-file-fixer

Fixing .git/MERGE_MSG
```

```
pre-commit 1.11.1
git version 2.19.0
macOS 10.14 (18A391)
```

**Comment by asottile** [comment]
ah, probably want to `stages: [commit, push]` for that hook since it doesn't really make sense during `commit-msg`?

**Comment by revolter** [comment]
Is it enabled for `commit-msg` by default? Do you know why it worked before? Is it because of Mojave?

**Comment by asottile** [comment]
yeah it's always been enabled for all of the stages (or, more specifically it takes the [default value](https://github.com/pre-commit/pre-commit/blob/08319101f4e0cd0f1dfa53ac353111329e260ffb/pre_commit/clientlib.py#L59) which is then later treated as [any stage](https://github.com/pre-commit/pre-commit/blob/08319101f4e0cd0f1dfa53ac353111329e260ffb/pre_commit/commands/run.py#L259))

I wonder if the git version caused this file to be written differently :thinking:

**Comment by revolter** [comment]
It contains:

```
1. Merge branch 'release-7.1.2' into master
2.
3.
```

**Comment by revolter** [comment]
But why is the hook receiving this file as an input?

**Comment by asottile** [comment]
`trailing-whitespace` matches all files that are ["text'](https://github.com/pre-commit/pre-commit-hooks/blob/219c70a9c1e8a946d3835974369d08f3ff5a00ec/.pre-commit-hooks.yaml#L262) (considered "non binary")

The `commit-msg` pre-commit implementation uses the commit message filename as the ["files"](https://github.com/pre-commit/pre-commit/blob/08319101f4e0cd0f1dfa53ac353111329e260ffb/pre_commit/commands/run.py#L179-L180) considered for hooks.  Since that file is text it gets fed through.

Question: are you intending to use the `commit-msg` hooks? (via `pre-commit install --hook-type commit-msg` / `pre-commit uninstall --hook-type commit-msg`?)

**Comment by asottile** [comment]
for what it's worth, I can also reproduce your findings on git 2.17.1 (ubuntu bionic):

```console
$ git merge origin/wat --no-ff -m 'Merge into master'
Already up to date!
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Failed
hookid: end-of-file-fixer

Fixing .git/MERGE_MSG

Not committing merge; use 'git commit' to complete the merge.
```

```console
$ cat .git/MERGE_MSG 
Merge into master

$
```

**Comment by asottile** [comment]
This diff "fixes" it but I imagine this isn't quite satisfactory :laughing: 

```diff
diff --cc .pre-commit-config.yaml
index 9c5d7e5,9c5d7e5..04191b2
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@@ -4,3 -4,3 +4,4 @@@ repos
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
++        stages: [commit, push]
```

**Comment by revolter** [comment]
I'm using `commit-msg` for a private hook from a private repo.

**Comment by revolter** [comment]
But I think that diff is quite correct, as it doesn't make sense for `end-of-file-fixer` to run against the commit message, that's not a file in the project.

**Comment by asottile** [comment]
I've been meaning to make a top level `default_stages: [...]` setting for pre-commit that makes this work ~better.  I wonder if the default stages should just be `[commit, push]` (though it seems weird to special case :S)

**Comment by revolter** [comment]
We could only default the `end-of-file-fixer` hook to the `commit` and `push` stages, not for every hook. So the question is, is there any reason *not* to do it, and keep the `commit-msg` enabled for this hook?

**Comment by asottile** [comment]
I say let's do it! Probably all the hooks in this repo should have that setup

**Comment by asottile** [comment]
Released this as [v1.4.0-1](https://github.com/pre-commit/pre-commit-hooks/releases/tag/v1.4.0-1)

**Comment by asottile** [comment]
Thanks again for the issue and fix :tada:

**Comment by revolter** [comment]
And thank you for the release ❤️
