### ISSUE TITLE
adding flag to run a specific hook

### ISSUE THREAD

**Issue by splnanthakumar** [pre-commit/pre-commit-hooks#316]
Hi Team,
     My use-case is, i have more than 10 hooks to run as part of pre -commit. i have made changes to few files where i want to check only specific hooks at the time of commit (because i know it is not needed to run other hooks /due to time consuming process )

     To implement this usecase, can we have another environmental variable to run specific hooks at the time of commit?

**Comment by asottile** [comment]
From https://github.com/pre-commit/pre-commit-hooks/issues/314#issuecomment-424745657

> This is the wrong place for such an issue, you want `pre-commit/pre-commit`

By this I mean, you are opening this issue against the incorrect project.  This project is for the implementation of some hooks.  You want to open your issue against [_the framework_](https://github.com/pre-commit/pre-commit)

I do not want to introduce an environment variable, and I still don't quite understand your usecase.

The general best practice with pre-commit is to *not* have time consuming hooks in the `pre-commit` hook phase -- if you want automated hooks that are time consuming `pre-push` is usually a better option (both can be installed at the same time side-by-side).  For example, running tests as a pre-commit hook is usually a bad idea (if pre-commit checks are time consuming, they're much much much more likely to be skipped -- defeating the purpose of checks in the first place!).

It also sounds like you're not taking advantage of `files:` to properly select what would run based on your changes -- you might want to look into that!
