### ISSUE TITLE
flake8 hook checks all python files in the repo, not just the staged ones

### ISSUE THREAD

**Issue by rpdelaney** [pre-commit/pre-commit-hooks#335]
pre-commit rejects any commit containing python files if _unstaged_ python files in the repo fail flake8. This is pretty much insufferable when the hook has been enabled on an old repo and cleanup is taking place over multiple commits. 

We either have to fix every python file simultaneously in a single commit, or else not enable the hook at all until everything is already PEP8 compliant. But the purpose of the hook is to prevent _additional_ linting errors from being introduced while we're doing the cleanup, so this cuts us in both directions.

**Comment by rpdelaney** [comment]
I'll check out an old commit where we observed the problem and get you a typescript log. Unfortunately the code is proprietary so I will have to either obfuscate data (which will probably obscure the linting errors)  -OR- recreate this in a test repo from scratch. In either case I'll need some time to recreate it. I'll get back to you.

**Comment by asottile** [comment]
Sounds good 👍 -- please create a new issue when you've got that!

Thanks again :)

**Comment by asottile** [comment]
oh I see, it's open source

You have this:

```yaml
https://github.com/rpdelaney/python-chess-annotator/blob/fcfc6f5f0a6a11d5737ebd04e7b6c74991a58527/.pre-commit-config.yaml#L49-L50
```

When pre-commit [passes filenames](https://pre-commit.com/#passing-arguments-to-hooks) to the hook, it will invoke like this:

```
flake8 --ignore annotator/__main__.py
```

Which tells flake8 (nonsensically) to `--ignore` the error code named "annotator/__main__.py".  After that, flake8 has no file arguments so it defaults to the flake8 default of recursing everything.

**Comment by rpdelaney** [comment]
Ah. `flake8` unfortunately ignores some PEP8 style guidelines by default; `--ignore` clears the default ignorelist, which is even more unfortunate and counter-intuitive. It looks like this fixed it: https://github.com/rpdelaney/python-chess-annotator/commit/69ef21ec249723e092cf566b3cd5f21d3f02edb3

Thanks.

**Comment by asottile** [comment]
:tada: quite the head scratcher -- glad we got to the bottom of it
