### ISSUE TITLE
end-of-file-fixer hook does not handle permission errors well

### ISSUE THREAD

**Issue by hartwork** [pre-commit/pre-commit-hooks#338]
I saw this traceback from during execution of pre-commit today:

```
Traceback (most recent call last):
  File "/home/someuser/.cache/pre-commit/repolz82qqa4/py_env-python3/bin/end-of-file-fixer", line 11, in <module>
    sys.exit(end_of_file_fixer())
  File "/home/someuser/.cache/pre-commit/repolz82qqa4/py_env-python3/lib/python3.5/site-packages/pre_commit_hooks/end_of_file_fixer.py", line 58, in end_of_file_fixer
    with open(filename, 'rb+') as file_obj:
PermissionError: [Errno 13] Permission denied: 'some_django_project/migrations/0023_auto_20181120_1541.py'
```

That file was created from inside a container... Would be nice to not have the backtrace, just an error.

Thanks!

**Comment by asottile** [comment]
This is a truly exceptional case, I think a stacktrace is appropriate. Feel free to comment with a convincing case and I'll reopen and reconsider. Thanks fur the issue anyway! :tada:

**Comment by hartwork** [comment]
For the record, I don't agree with you on a backtrace being appropriate. It might be a rare case but (simplified) a tool that handles files should handle file access exceptions and not show backtraces for anything except with maybe `--debug` in my book. Just my 2 cents.

**Comment by hartwork** [comment]
Hi Anthony,

I agree that message `IOError [Errno 13] Permission denied` is not as helpful as it should be, but that's C world, Python does a lot better by default, see:

```console
# cd "$(mktemp -d)"
# touch not-writable
# chmod a-w not-writable 
# python -c 'open("not-writable", "w")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
PermissionError: [Errno 13] Permission denied: 'not-writable'
```

We have two distinct questions here that are worth to untangle:

- Should backtracing case X be handled properly

- Should backtraces be hidden and just the last line displayed.

My point is about former (and I digressed into the later but should not have). I had that backtrace more than once.

If we were in C, the app would have died with segfault or something.
Do we agree that every segfault for a C program is a bug that should be fixed?

Best, Sebastian

**Comment by asottile** [comment]
In c it's undefined behavior. I also don't see how what c does is relevant here. I'm not writing c for a good reason.  You got the useful error message you needed and no code complexity was necessary to handle it explicitly (and you're a developer using a tool targeted at developers)

Also python does not always produce the filename in OSErrors, and certainly not in other hnadleable but exceedingly unlikely exceptions such as MemoryError.  MemoryError would be a segfault too -- would you wrap every call that could cause that (which is basically every function call or attribute access)?

The point is, this isn't C, the stacktrace is often the most useful information possible, removing that is both complex, boilerplate, and frankly a waste of time to think about

**Comment by hartwork** [comment]
We're digressing to the second case (of hiding backtraces or not) again. Let's get back to handling permission errors or not.

I was hoping to make a point with C that backtraces in Python are just the self-explaining version of (things like) segfaults in C. My hope was that we'd agree that all of them need fixes in C and that the conclusion would be to fix every "self-explaining segfault" in Python as well.

Is that permission error above really pathological enough not to fix, in general?

**Comment by asottile** [comment]
What fix are you suggesting if not to hide the back trace and have a custom message equivalent to the back trace printed?

**Comment by asottile** [comment]
Why though? The trace gives you all that and more with zero code

**Comment by hartwork** [comment]
Well, if you consider showing backtraces cool and I don't we have hit the bottom here. Let's close this as wont-fix then?
