### ISSUE TITLE
The check-executables-have-shebangs hook fails for the COMMIT_EDITMSG file

### ISSUE THREAD

**Issue by revolter** [pre-commit/pre-commit-hooks#361]
Using the latest `1.14.2` version, it fails with this error:

```
Check that executables have shebangs.....................................Failed
hookid: check-executables-have-shebangs
.git/COMMIT_EDITMSG: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: chmod -x .git/COMMIT_EDITMSG
  If it is supposed to be executable, double-check its shebang.
```

I don't know how it got to be executable, but I definitely didn't do it myself. Nonetheless, it shouldn't check the files inside the `.git` directory, should it?

**Comment by asottile** [comment]
hmm! This might be a good application for the new [`default_stages`](https://pre-commit.com/#pre-commit-configyaml---top-level) configuration option -- just to prevent this hook from running unintentionally:

```yaml
default_stages: [commit]
# ... rest of the config as normal
```

(generally I've found that when using `commit-msg` that I end up setting `default_stages: [commit]` anyway -- or prior to 1.14.0 I'd put `stages: [commit]` manually on every entry)

The other option is we configure `stages: [commit, push, manual]` in this repo -- though that'll have to be updated every time `pre-commit` learns a new stage :thinking: -- so I'd prefer the `default_stages` solution if at all possible.

**Comment by asottile** [comment]
lol we did :man_facepalming:  -- yeah that patch is probably fine for other hooks as well.  For the most part a lot won't apply just by default

-- probably just apply it to `trailing-whitespace`, `end-of-file-fixer`, and this one
