### ISSUE TITLE
Issues with requirements-txt-fixer

### ISSUE THREAD

**Issue by nikolay** [pre-commit/pre-commit-hooks#37]
My other hooks work, but this one always give:
```
$ pre-commit clean
Cleaned /Users/name/.pre-commit.
$ pre-commit install
pre-commit installed at /Users/name/Projects/name/.git/hooks/pre-commit
$ pre-commit run --all-files
An unexpected error has occurred: KeyError: 'requirements-txt-fixer'
```

My `.pre-commit-config.yaml`:
```yaml
- repo: git@github.com:pre-commit/pre-commit-hooks.git
  sha: v0.3.0
  hooks:
  - id: check-json
  - id: check-yaml
  - id: flake8
  - id: requirements-txt-fixer
  - id: trailing-whitespace
```

**Comment by asottile** [comment]
Ah I should cut a new release and then you can use a later version in `sha`, for now you can use the latest until I tag a new release by running `pre-commit autoupdate`. I should also really improve that error message.  I'll make an issue for that when in not on my phone :)

**Comment by asottile** [comment]
Update the `sha` in your .pre-commit-config.yaml to `v0.4.0` and the `requirements-txt-fixer` hook should work :)

Thanks for the issue!

**Comment by nikolay** [comment]
@asottile Works, thank you very much! Any plans to implement other type of hooks ala [Overcommit](https://github.com/causes/overcommit)?

**Comment by asottile** [comment]
Technically anything that is installable and in one of the currently supported languages (python, ruby, js) can be used as a pre-commit hook (and I guess technically you can use any system installed things (overcommit style) as well).  You can read more about writing hooks here: http://pre-commit.com/#new-hooks and see our list of ones people have implemented here: http://pre-commit.com/hooks.html
