### ISSUE TITLE
check-byte-order-marker hook only runs on Python files, not all text files

### ISSUE THREAD

**Issue by tobywf** [pre-commit/pre-commit-hooks#371]
`check-byte-order-marker` always said "skipped" in our repo. Turns out while for many text hooks, the default is `types: [text]` ([end-of-file-fixer](https://github.com/pre-commit/pre-commit-hooks/blob/f8ae0aab7baa05663903e539e05590630ec54465/.pre-commit-hooks.yaml#L120), [mixed-line-ending](https://github.com/pre-commit/pre-commit-hooks/blob/f8ae0aab7baa05663903e539e05590630ec54465/.pre-commit-hooks.yaml#L151), and [trailing-whitespace](https://github.com/pre-commit/pre-commit-hooks/blob/f8ae0aab7baa05663903e539e05590630ec54465/.pre-commit-hooks.yaml#L187)), but it's `types: [python]` [for check-byte-order-marker](https://github.com/pre-commit/pre-commit-hooks/blob/master/.pre-commit-hooks.yaml#L24).

I'm not sure if it's a copy and paste error, or intended, but it's a bit counter-intuitive. Might be worth changing, but simply pointing it out in the documentation for the hook would also help.

**Comment by asottile** [comment]
That's definitely a mistake heh, want to send a PR to fix it?

**Comment by tobywf** [comment]
Sure thing, should be easy enough :)
