### ISSUE TITLE
Allow no-commit-to-branch to block commits based on regex matching

### ISSUE THREAD

**Issue by marcjay** [pre-commit/pre-commit-hooks#375]
Hopefully not alone in wanting this functionality - our use case is we have multiple release branches (e.g. `release/1.0.0`, `release/2.0.0`) and no commits should be made to these branches directly, only via pull requests.

This would be to add wildcard matching, so that with `args: [--branch, master, --branch, release/*]` it would cause pre-commit to fail if a commit is attempted on any of: `master`, `release/1.0.0` or `release/2.0.0`

**Comment by asottile** [comment]
Seems fine, let's use `--pattern` as a separate argument and use regular expressions instead of glob / fnmatch

**Comment by marcjay** [comment]
Sure, I'll re-work the PR. Just want to double check - do you see the example above becoming:
```
args: [--branch, master, --pattern, release/.*]
```
i.e. the branch and pattern args would become an OR match, as opposed to the two args being mutually exclusive and needing to do:
```
args: [--pattern, master|(release/.*)]
```

**Comment by asottile** [comment]
the first one sounds good 👍

**Comment by asottile** [comment]
via #376
