### ISSUE TITLE
Autopep8 doesn't respect pep8 section in setup.cfg

### ISSUE THREAD

**Issue by jpulec** [pre-commit/pre-commit-hooks#38]
Since https://github.com/hhatto/autopep8/pull/167 autopep8 has started reading the ```pep8``` section from ```tox.ini``` or ```setup.cfg``` of a project. However, the autopep8 hook ignores this as it calls ```autopep8.parse_args()``` and ```autopep8.fix_code()``` without a second value (which defaults to ```False```).

Any way we could get this to work?

**Comment by asottile** [comment]
There should be a way to get this to work :)

Would you like me to take a look at it or do you want to take a crack at a PR?

**Comment by asottile** [comment]
Nevermind I've got it :) was a simple one-argument change
