### ISSUE TITLE
double-quote-string-fixer change linebreak on windows

### ISSUE THREAD

**Issue by Trim21** [pre-commit/pre-commit-hooks#385]
I'm using `mixed-line-ending` and  `double-quote-string-fixer` on windows'
If `double-quote-string-fixer` changes file content, origin `LF` ending will be convert to `CRLF` ending.

**Comment by asottile** [comment]
indeed, this is due to use of `io.open` -- should be an easy fix though

**Comment by asottile** [comment]
released as part of 2.2.3 -- thanks again for the issue 🎉

**Comment by Trim21** [comment]
thanks for your work.
