### ISSUE TITLE
Allow files to be ignored from hooks

### ISSUE THREAD

**Issue by jadchaar** [pre-commit/pre-commit-hooks#391]
I recent had to make some tests for a package of mine to do file comparisons with "expected output files" stored in my repo, but some of them have training whitespace, for example, and I need this to be preserved. But, I would like the ability to remove trailing whitespace in my other files.

Would it be possible to add a `--ignore` flag to hooks such as trim trailing whitespace?

**Comment by asottile** [comment]
You're looking for `exclude` I believe?

**Comment by jadchaar** [comment]
Thanks @asottile, I will play around with that pre-commit setting :).

**Comment by jadchaar** [comment]
Is it possible to match an entire directory rather than single files?

**Comment by asottile** [comment]
yep, it's a regex so you have full control

something like this will probably work for you?

```yaml
        exclude: ^examples/
```
