### ISSUE TITLE
trailing-whitespace failing to support markdown and running in spite of errors

### ISSUE THREAD

**Issue by eedwards-sk** [pre-commit/pre-commit-hooks#392]
If I try to specify multiple extensions, it fails:

```
repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md,markdown]
```

```
(spice) → pre-commit run --verbose trailing-whitespace
[trailing-whitespace] Trim Trailing Whitespace...........................Failed
hookid: trailing-whitespace

Traceback (most recent call last):
  File "/Users/eedwards/.cache/pre-commit/reporo4_9zb8/py_env-python3.6/bin/trailing-whitespace-fixer", line 11, in <module>
    sys.exit(main())
  File "/Users/eedwards/.cache/pre-commit/reporo4_9zb8/py_env-python3.6/lib/python3.6/site-packages/pre_commit_hooks/trailing_whitespace_fixer.py", line 81, in main
    if _fix_file(filename, md):
  File "/Users/eedwards/.cache/pre-commit/reporo4_9zb8/py_env-python3.6/lib/python3.6/site-packages/pre_commit_hooks/trailing_whitespace_fixer.py", line 11, in _fix_file
    with open(filename, mode='rb') as file_processed:
FileNotFoundError: [Errno 2] No such file or directory: 'markdown'
```

**Comment by asottile** [comment]
Your output looks like you have trailing-whitespace configured twice, can you paste your actual and full configuration?

**Comment by eedwards-sk** [comment]
I totally do have it listed twice. Or, at least the dev who did this project listed it twice ;D

That explains... quite a lot.

So, that resolves 1) and 2)

Looks like the remaining issue, which may be a usage issue, as well, is 3) specifying multiple comma-separated values for the extension generates an error message

**Comment by eedwards-sk** [comment]
okay, must be a yaml parsing issue

```
        args:
        - --markdown-linebreak-ext=md,markdown
```

works fine

so when specified as an inline array, I need to quote the entire value:

```
    -   id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md,markdown"]
```

closing as PEBKAC

**Comment by asottile** [comment]
Ah yeah you're getting bit by yaml bare strings, `['--foo=bar,baz'] `  (quote it to fix)

**Comment by daviewales** [comment]
For other poor souls getting this error, it might also be because you omitted the `=`:

    args: ["--markdown-linebreak-ext md,markdown"] # wrong
    args: ["--markdown-linebreak-ext=md,markdown"] # right
