### ISSUE TITLE
Specify Whitelist Of Files To Avoid Checking In check-json Hook

### ISSUE THREAD

**Issue by ndibari-sp** [pre-commit/pre-commit-hooks#394]
I have some unit tests in a codebase that test the behavior of the functions when they receive an invalid JSON file as an argument. Unfortunately, the `check-json` hook prevents me from adding these files to my codebase, as they are (intentionally!) invalid JSON. I got around this by changing the file extension of the bad fixture file to .txt to avoid the hook, but I think it would be better to optionally specify a whitelist of files to avoid linting in this hook configuration.

This would allow a user to optionally set some files to avoid linting in the hook to allow for purposefully invalid JSON files to be committed to a codebase.

**Comment by asottile** [comment]
You're looking for [`exclude:`](https://pre-commit.com/#pre-commit-configyaml---hooks) (also available at the top level)

**Comment by ndibari-sp** [comment]
Outstanding, thanks for pointing me to this
