### ISSUE TITLE
Increase json to bypass the option of comment error

### ISSUE THREAD

**Issue by fbigun** [pre-commit/pre-commit-hooks#395]
https://github.com/pre-commit/pre-commit-hooks/blob/9ce6b9facb1a8b392c7fd2e89d6f89a661a41d83/pre_commit_hooks/check_json.py#L17-L23

When json file check, json can ignore comments with comments when it is used as a configuration file. Increase options to bypass errors

**Comment by asottile** [comment]
[json](http://json.org/) does not contain comments so this is invalid

if you have specific files which are not json and are intentionally not json, you can use [`exclude: `](https://pre-commit.com/#pre-commit-configyaml---hooks) to exclude them

**Comment by bristea** [comment]
While @asottile is right about JSON not allowing comments at all, these being deliberately excluded from the specification the OP question is still valid.

It seems that a considerable number of tools use config files using an alternative format `json-with-comments` that sadly happens to use the same `.json` extension, making impossible to determine which should be one or another.

I am curious if someone wrote an alternative hook that can lint the new format, one that can ignore comments in json files. Apparently the number of config files using that makeshift format is growing. Not doing any linting on those files is still dangerous as other critical errors may fail to be identified.

**Comment by maresb** [comment]
> I am curious if someone wrote an alternative hook that can lint the new format, one that can ignore comments in json files.

I just did this, it's called [check-json5](https://gitlab.com/bmares/check-json5).

**Comment by asottile** [comment]
just because lots of people are poor open source users and contributors doesn't mean I should have to do extra work to accommodate them
