### ISSUE TITLE
check-added-large-files --maxkb not obeyed

### ISSUE THREAD

**Issue by scottschreckengaust** [pre-commit/pre-commit-hooks#396]
Sorry for the poor title, my <TAB> too quickly made an <ENTER>:
The `check-added-large-files` configuration is not taking the documented `--maxkb=123`:

> https://github.com/pre-commit/pre-commit-hooks

```
-   id: check-added-large-files
    name: Check for added large files
    description: Prevent giant files from being committed
    entry: check-added-large-files
    language: python
    types: [file]
    args: ['--maxkb=150']
```

It is still using the default 500kb though.  Any way you can point me to the issue?  I am using the `identity` meta item, and it is detecting the changed files, and when too large is failing the above hook.

Are they being read? 

https://github.com/pre-commit/pre-commit-hooks/blob/9ce6b9facb1a8b392c7fd2e89d6f89a661a41d83/pre_commit_hooks/check_added_large_files.py#L53

**Comment by asottile** [comment]
do you have a workable example or something I can clone and poke around with?  posting your `.pre-commit-config.yaml` would help a lot

**Comment by scottschreckengaust** [comment]
I forked [this](https://github.com/scottschreckengaust/pre-commit-hooks) -> one commit adding the documented `args` [9d4a9cc6a27969f4cfb4477b762bcfea4aa4fa64](https://github.com/scottschreckengaust/pre-commit-hooks/blob/9d4a9cc6a27969f4cfb4477b762bcfea4aa4fa64/.pre-commit-hooks.yaml#L13)

Here is how I replicated:
```bash
git clone git@github.com:scottschreckengaust/pre-commit-hooks.git
pip install pre-commit
pre-commit install
pre-commit run --all-files  # see everything pass
printf '123456789\n%.0s' {1..12700} > 124kb.txt # create a file >123K
git commit -am "successful file greater than 123Kb"
printf '123456789\n%.0s' {1..51201} > 501kb.txt # create a file >500K
git commit -am "failed file greater than 500Kb"
```

**Comment by asottile** [comment]
there's two separate files, `.pre-commit-hooks.yaml` this is the "producer" and then `.pre-commit-config.yaml` this is the "consumer"

The consumer specifies an upstream repository to use and then selects hooks from there, in this case that repo you linked above is still linking to `pre-commit/pre-commit-hooks@v2.2.3` and not your fork (so changes are not reflected)

~generally you don't need to modify `.pre-commit-hooks.yaml` unless you're authoring your own hooks -- the `.pre-commit-config.yaml` file allows you to override any of the settings necessary

**Comment by scottschreckengaust** [comment]
Makes sense.
