### ISSUE TITLE
what's the state of pyflakes?

### ISSUE THREAD

**Issue by brutus** [pre-commit/pre-commit-hooks#398]
Between `flake8` and `autopep8` I only find `check_ast` and a deprecation note on `pyflakes`… What's the current state here? Any recommendations or suggestion, if I only want to check with _pyflakes_ - without all the extras of the other tools?

**Comment by asottile** [comment]
The suggestion is to use `flake8` with `--select=F` if you only want pyflakes things

**Comment by asottile** [comment]
fwiw, in this repository `flake8` is also deprecated and should be used from https://gitlab.com/pycqa/flake8

**Comment by ssbarnea** [comment]
Good to close AFAIK? @asottile
