### ISSUE TITLE
Python 3.10 / 4 checker?

### ISSUE THREAD

**Issue by hugovk** [pre-commit/pre-commit-hooks#409]
We don't yet know if 3.10 or 4.0 will follow Python 3.9, but great to see your tests with https://github.com/asottile/python3.10 and the related fixes!

* https://github.com/pypa/setuptools/pull/1824
* https://github.com/tox-dev/tox/pull/1398
* https://github.com/python/cpython/pull/14831
* https://github.com/tox-dev/tox/pull/1398

How about a pre-commit hook to detect, and possibly fix, some potential 3.10 errors?

```diff
-sys.version[:3]
+'{}.{}'.format(*sys.version_info)
```

And also any possible Python 4 errors?

```diff
-if sys.version_info.major == 3:
+if sys.version_info.major >= 3:
    # Python 3+ stuff
else:
    # Python 2 stuff
```

Maybe this might not be something for pre-commit, but I think it could be a useful tool of some sort.

Thanks!

**Comment by asottile** [comment]
probably makes the most sense as a `flake8` plugin? should be pretty easy to detect the various cases that are problematic:

- slice / index of `sys.version`
- usage of `six.PY3`
- usage of `sys.version_info[0] ==`
- etc.

**Comment by asottile** [comment]
I made [flake8-2020](https://github.com/asottile/flake8-2020) on [stream](https://twitch.tv/anthonywritescode) today 🎉

**Comment by hugovk** [comment]
Brilliant, thanks!
