### ISSUE TITLE
yaml check complains about valid use of multiple anchors & aliases  `<<`

### ISSUE THREAD

**Issue by kowalcj0** [pre-commit/pre-commit-hooks#412]
Hi,

We do use anchors & aliases  `<<: *` quite extensively in our [CircleCI yaml config](https://github.com/uktrade/directory-tests/blob/master/.circleci/config.yml).
Unfortunately `check-yaml` (or rather `ruamel.yaml`) complains about duplicated `<<` keys, which actually aren't duplicated. 
Let's take this job definition as an example:
```yaml
jobs:
  setup_env_for_smoke_tests:
    <<: *machine_python3
    working_directory: ~/directory-tests
    <<: *steps_setup_env_for_smoke_tests
```

When I run `pre-commit run --all-files` without `args: [--unsafe]`, I'm going to get this error:
```python
    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in ".circleci/config.yml", line 254, column 5
found duplicate key "<<"
  in ".circleci/config.yml", line 256, column 5
To suppress this check see:
   http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
```

I had a look at recommended doc page https://yaml.readthedocs.io/en/latest/api.html#duplicate-keys and `ruamel.yaml` has an option to allow `allow_duplicate_keys`, unfortunately [check_yaml.py](https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_yaml.py#L39) does not support it.

As a workaround I allowed `unsafe` constructs, but it doesn't look good:
```yaml
    -   id: check-yaml
        args: [--unsafe]
```

In theory we can "merge keys" but it's rather an ugly solution:
* https://bitbucket.org/ruamel/yaml/issues/130/anchor-references-broken-beginning-at
* https://bitbucket.org/ruamel/yaml/issues/313/duplicate-merge-key-throws-duplicate-key

Further reading:
* Looks like it's partially related with #81 
* `ruamel.yaml` does support anchors https://yaml.readthedocs.io/en/latest/detail.html?highlight=anchors#details
* https://yaml.org/spec/1.2/spec.html#id2765878 official spec on `Anchors and Aliases`
* https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/#yaml-anchors--aliases

Thanks

**Comment by asottile** [comment]
I think you mean to use:

```yaml
    <<: [*machine_py3, *steps_setup_env_for_smoke_tests]
```

`--unsafe` seems like the correct workaround for actual duplicate keys as #81 suggests

**Comment by asottile** [comment]
either that or it's a bug with `ruamel.yaml` -- I'd suggest opening an issue there

**Comment by kowalcj0** [comment]
:+1:
