### ISSUE TITLE
requirements-txt-fixer corrupts file if no new line at end

### ISSUE THREAD

**Issue by barakreif** [pre-commit/pre-commit-hooks#414]
a file with
```
a
b
c
```
(no new line)
will get "fixed" to:
```
a
bc

```

I was able to debug and identify the issue, I'll be happy to also PR a fix but I was wondering if there is really a use for it? I've not seen any input without a new line at the end in the tests cases and as a work around I can add `end-of-file-fixer` before it.

**Comment by asottile** [comment]
sounds worth fixing (and probably pretty easy to fix) -- would you like to submit a PR :D

**Comment by barakreif** [comment]
lets give it  a go

**Comment by barakreif** [comment]
@asottile  I saw in one of the unit test this test case:
`(b'\nbar\nfoo\n', PASS, b'\nbar\nfoo\n'),`
is it intentional to maintain the leading new line?

**Comment by asottile** [comment]
> 
> 
> @asottile I saw the unit test this test case:
> 
> https://github.com/pre-commit/pre-commit-hooks/blob/277f875bc517bbde5f767dcb0919e762c33759a9/tests/requirements_txt_fixer_test.py#L31
> 
> is it intentional to maintain the leading new line?

it's certainly a little weird -- it's meant to demonstrate the different "header lines" that can appear -- the intention being that something like this is maintained:

```
# header comment

first-req
second-rec
```

it's definitely debatable whether a blank line by itself should be considered a header without any comments

**Comment by asottile** [comment]
I'd be fine if a `.lstrip()` was added and that testcase changed 👍
