### ISSUE TITLE
debug-statements issue with f-string

### ISSUE THREAD

**Issue by Sebastiencreoff** [pre-commit/pre-commit-hooks#418]
Hello,
I am issuing pre-commit module inside one of my personnal project which is in Python 3.6.
It works pretty well but I still have an issue about file which have f-string formating.

```
hookid: debug-statements
...
            error = f'code={self.code_}, message={self.message_}'
                                                                ^
        SyntaxError: invalid syntax
```

My project is in Python 3.6.4
pre-commit used is v2.3.0

Thanks

**Comment by asottile** [comment]
you probably installed pre-commit using python 2 (it will default to that interpreter) -- I would suggest python 3 always

otherwise, use [`language_version`](https://pre-commit.com/#overriding-language-version)

**Comment by Sebastiencreoff** [comment]
yes, it was it... Sorry. I will close it.

**Comment by asottile** [comment]
cheers! thanks for the issue :tada:
