### ISSUE TITLE
private key hook

### ISSUE THREAD

**Issue by wenzowski** [pre-commit/pre-commit-hooks#42]
Not sure if right place for this, but here goes.

It is [unfortunately easy](http://arstechnica.com/security/2015/03/in-major-goof-uber-stored-sensitive-database-key-on-public-github-page/) to accidentally check in secrets.

Has someone in the community already written a hook to watch out for private keys?

**Comment by guykisel** [comment]
I feel like there must be a tool out there that automatically scans repos/projects for ssh keys and other secrets (AWS credentials, for example). If you can find such a tool it would probably be easy to wrap it in a hook.

**Comment by guykisel** [comment]
I just found this: https://github.com/michenriksen/gitrob/issues/28

**Comment by asottile** [comment]
+1 this sounds like a great opportunity for a hook.  I don't believe we have anything that checks this yet.  Shouldn't be too hard to implement with either something existing or from scratch.

**Comment by asottile** [comment]
Shame blueflower is gpl (doesn't play nicely with our licensing), might be easy to implement these ourselves.

**Comment by wenzowski** [comment]
Yeah, shame about blueflower.

Can we assume grep is installed, and do say `grep -i -r 'private[ -_]key\|begin certificate' .` or should this be pure py?

**Comment by asottile** [comment]
Ideally pure python (`re.match` is a good fit) since we attempt to support windows

**Comment by guykisel** [comment]
You could probably save a lot of time using gitrob's patterns - https://github.com/michenriksen/gitrob/blob/master/patterns.json

Fortunately, gitrob is MIT licensed.

**Comment by asottile** [comment]
#43 starts work on this.  We could use gitrob for filename matching as well

**Comment by wenzowski** [comment]
sweetness!

**Comment by asottile** [comment]
going to close this since it's at least started via the `detect-private-key` hook.  Thanks again for the issue @wenzowski !
