### ISSUE TITLE
Merge conflict string "======= fails on README.rst

### ISSUE THREAD

**Issue by rven** [pre-commit/pre-commit-hooks#426]
When The working tree is in merging-state and the README.rst file contains the following text:

Credits
=======

see as example: https://raw.githubusercontent.com/OCA/web/13.0/web_responsive/README.rst

The following pre-commit check fails

Check for merge conflicts................................................Failed
hookid: check-merge-conflict

Merge conflict string "=======
" found in README.rst:38

**Comment by asottile** [comment]
dupe #100
