### ISSUE TITLE
Mitigate Trojan Horses

### ISSUE THREAD

**Issue by ericfrederich** [pre-commit/pre-commit-hooks#428]
In the `.pre-commit-config.yaml` you specify a `repo` and a `rev`.

Using a tag as the rev is useful for humans to look at.  Also useful to detect new updates.  Unfortunately tags can be moved.  For example, if projects have `https://github.com/pre-commit/pre-commit-hooks` at rev `v2.4.0` in their config file, the maintainer can decide to force push the `v2.4.0` tag to a malicious commit.  Now their malicious code will run on newly initialized repos.

I would look at is as though the trojan horses are already installed anywhere pre-commit is being used.

# Suggestion

- Utilize both `rev` and `sha` at the same time.
- `pre-commit autoupdate` should update both the `rev` and the `sha`.
- `pre-commit install-hooks` should validate that the `rev` is the same commit as `sha`

## Example config

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    sha: 0161422b4e09b47536ea13f49e786eb3616fe0d7
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
```

**Comment by asottile** [comment]
please be a little less alarmist <3 -- see also https://github.com/pre-commit/pre-commit/issues/1068
