### ISSUE TITLE
Check and format json files with a different file extension than *.json

### ISSUE THREAD

**Issue by kekscode** [pre-commit/pre-commit-hooks#432]
Maybe i'm overlooking something here, but i don't get how i can force the:

- check-json
- pretty-format-json

linter and formatters to work on files which do not have the `.json` suffix in their filename.  
I have files called `.template` which are valid json files and tried several things like:

```
- id: pretty-format-json
   files: '^.+\.json$|^.+\.template$'
   args: ["--autofix"]
```

and various other (more or less strict) regular expressions, like these:

```
files: '^(.+\.json$|^.+\.template)$'
files: ^(\.json|\.template)$
files: '^.+\.json$|^.+\.template$'
files: \.(json|template)$
```

I also tried specifying a single file with:'

```
- id: pretty-format-json
   #files: '^.+\.json$|^.+\.template$'
   files: 'json_test.template'
   args: ["--autofix"]

```

but even that does not force pre-commit to pretty-format/autofix the `json_test.template` file. It just gets skipped.

I also tried identify, but `identify-cli` gives me for the files `["file", "non-executable", "text"]`.  
I think this means i cannot use identify and have to stick to the `files:` way, right?

What am i doing wrong?

**Comment by asottile** [comment]
Those hooks set `types: [json]` which is [ANDed with `files`](https://pre-commit.com/#filtering-files-with-types) -- you'll need to reset `files` back to something less restrictive, such as:

```yaml
   types: [text]
   files: \.(json|template)$
```

**Comment by asottile** [comment]
I've added a little bit to the docs -- thanks again for the issue!

**Comment by kekscode** [comment]
Awesome, thanks for clarifying and updating the docs. Appreciated!
