### ISSUE TITLE
mixed-line-ending false positive failure on Windows

### ISSUE THREAD

**Issue by mkbel** [pre-commit/pre-commit-hooks#436]
### Steps to reproduce:
create git repository on Windows platform
add file .gitattributes with content:
`* text=auto`
setup pre-commit hook with:
```
mixed-line-ending
      args: ['--fix=lf']
```
Create text file yourfile.c with CRLF line endigs.
Add it to git repository.
Stage it.
Commit it.

### Expected result:
`Mixed line ending........................................................Passed`
as git automatically converts CRLF to LF when commiting
### Actual result:
```
Mixed line ending........................................................Failed
- hook id: mixed-line-ending
- exit code: 1
- files were modified by this hook
```
stage modified file, git warns you:
```
Stage 1 files
warning: LF will be replaced by CRLF in yourfile.c.
The file will have its original line endings in your working directory
Done
```
Commit:
`Mixed line ending........................................................Passed`

At this point, I am not sure which line endings end up committed in repository. Probably LF, as this test passes on server running Linux which checks pull requests.

**Comment by asottile** [comment]
the hook reads the file contents from disk -- on disk that file has crlf (git may smudge it later, but that's the truth that the hook sees)

you'll probably have better mileage not using autocrlf with git and this hook

**Comment by mkbel** [comment]
Thank you for quick response. So if this is technical limitation, I would propose to document it. https://github.com/pre-commit/pre-commit-hooks/pull/437

**Comment by asottile** [comment]
we may also be able to detect this mode and skip or something (or warn) but I think for now this documentation helps clear up the issue

**Comment by asottile** [comment]
(for what it's worth, when I work on windows I choose to "check out as-is commit as-is" and at least with most modern text editors it works out fine)

**Comment by mkbel** [comment]
For example Visual Studio Code in default setup saves edited file with CRLF. Of course we can ship setup for such editor with our project, but I prefer to stick with platform default. Check-out CRLF check-in LF is recommended default for multi-platform git project under Windows.

**Comment by asottile** [comment]
that recommendation (afaik) is only due to older tools defaulting to crlf on windows -- though most tools on windows work fine with just lf endings now-a-days
