### ISSUE TITLE
name-tests-test isn't Django-friendly

### ISSUE THREAD

**Issue by guykisel** [pre-commit/pre-commit-hooks#44]
https://docs.djangoproject.com/en/1.7/topics/testing/advanced/#using-different-testing-frameworks

Django's built-in test runner defaults to searching for `test*.py`. It would be nice if `name-tests-test` either allowed both the `test*.py` and `*_test.py` patterns or if there was a separate hook for the Django-style test naming pattern.

I'd be happy to submit a PR for the preferred solution/implementation.

**Comment by asottile** [comment]
Maybe a `--django` option?

**Comment by guykisel** [comment]
That seems like a reasonable workaround.

**Comment by oladhari** [comment]
in fact, it would be better to add a PR if you do not mind, what do you think? I will be happy to do it

**Comment by asottile** [comment]
For what exactly? `*_tests.py` doesn't match the pytest or django conventions

**Comment by oladhari** [comment]
@asottile yes it doesn't match, I was pushed to rename my files to `*_test.py`
sorry for my late reply

**Comment by oladhari** [comment]
and here I got this error even after updating ny test files name:
![Screenshot from 2019-09-17 11-16-44](https://user-images.githubusercontent.com/13581057/65006013-cf423a80-d93c-11e9-9208-189952e84d5d.png)

**Comment by asottile** [comment]
that output makes sense if you're using the `--django` flag

**Comment by oladhari** [comment]
yes it is true, I deleted the `--django` flag from `pytest.ini` and error disappeared
