### ISSUE TITLE
trailing-whitespace extension doesn't allow for md.j2

### ISSUE THREAD

**Issue by Natim** [pre-commit/pre-commit-hooks#445]
```
error: bad --markdown-linebreak-ext extension '.md.j2' (has . / \ :)
  (probably filename; use '--markdown-linebreak-ext=EXT')```

**Comment by asottile** [comment]
~technically there's no such thing as a double-extension:

```pycon
>>> import os
>>> os.path.splitext('foo.md.j2')
('foo.md', '.j2')
```

**Comment by asottile** [comment]
you're probably best to use `exclude: \.md\.j2$` instead

**Comment by Natim** [comment]
> ~technically there's no such thing as a double-extension:
> 
> ```
> >>> import os
> >>> os.path.splitext('foo.md.j2')
> ('foo.md', '.j2')
> ```

If that's a usecase we want to support, we could also use:

```python
>>> filename = 'foo.md.j2'
>>> filename.endswith('.md.j2')
True
```

**Comment by asottile** [comment]
that would be incorrect for current use cases which require `--markdown-linebreak-ext=md` -- which would silently do the wrong thing for `foo.fnd`

**Comment by Natim** [comment]
> would silently do the wrong thing for foo.fnd

Actually `foo.fmd` doesn't match `.md`

**Comment by Lin-Buo-Ren** [comment]
> that would be incorrect for current use cases which require `--markdown-linebreak-ext=md` \-\- which would silently do the wrong thing for `foo.fnd`

Could you elaborate?  I like to specify Markdown jinja templates to be special-cased as well.

**Comment by asottile** [comment]
https://github.com/pre-commit/pre-commit-hooks/issues/445#issuecomment-582511865
