### ISSUE TITLE
How to skip a line for debug_statement_hook?

### ISSUE THREAD

**Issue by uriva** [pre-commit/pre-commit-hooks#458]
What's the syntax for skipping a line in the `debug_statement_hook`?

**Comment by asottile** [comment]
there is no inline opt-out, however you can trick the tool using `__import__` instead of `import`

**Comment by uriva** [comment]
I'm using `breakpoint` so there is no `import` statement.

Can this be a feature request then?

**Comment by asottile** [comment]
`builtins.breakpoint()` will work

if you need to exclude a file use [`exclude:`](https://pre-commit.com/#pre-commit-configyaml---hooks)

**Comment by uriva** [comment]
Thanks that works (although a bit hacky).

Also excluding the entire file would defeat the purpose...

I think a general mechanism to skip rows might be useful.

**Comment by asottile** [comment]
having debug statements in live code is a bit hacky ;)

**Comment by uriva** [comment]
The use case is a util in a functional programming library, used for debugging.

`do_breakpoint = curried.do(lambda x: breakpoint())`

(using `toolz.curried`)

**Comment by asottile** [comment]
why not `curried.do(breakpoint)`

**Comment by uriva** [comment]
imagine this situation: `toolz.pipe(x, some_func, do_breakpoint, some_other_func)`

`breakpoint` does not get an input, so this would throw an exception if I follow your suggestion.

In addition I want to be able to evaluate the incoming `x` in the debug prompt.
