### ISSUE TITLE
Feature Request: Vagrant validate & puppet-lint

### ISSUE THREAD

**Issue by patchshorts** [pre-commit/pre-commit-hooks#463]
I am highly interested in these hooks but do not know how to implement or write them. I am filing this here as a place to discuss interest so someone might.

**Comment by asottile** [comment]
I'd suggest checking the "official" list, there's probably already someone who has implemented one (or something you can look at to implement them): https://pre-commit.com/hooks.html

this repository isn't quite the right place to implement those hooks as they're very language specific and moving forward this repository is aiming to be as language-agnostic as possible
