### ISSUE TITLE
linting dotenv files

### ISSUE THREAD

**Issue by barakreif** [pre-commit/pre-commit-hooks#464]
Hi guys, how would you feel about and `.env` files linter such as this:
https://lib.rs/crates/dotenv-linter ?

my main concern about spending time on making this in python is that these type of files are almost always in `.gitignore`.

**Comment by asottile** [comment]
why not just use the rust one?  pre-commit supports rust :)

**Comment by barakreif** [comment]
> why not just use the rust one? pre-commit supports rust :)

don't we all :), but how do you go about deploying a multi-architecture executable?, regardless, some research (which should have been more extensive in the first go, I blame COVID-19)  has unraveled  [this](https://github.com/wemake-services/dotenv-linter/issues/205).
