### ISSUE TITLE
Requirements.txt fixer doesn't sort correctly without empty line

### ISSUE THREAD

**Issue by Baschdl** [pre-commit/pre-commit-hooks#473]
The requirements.txt fixer is not working correctly if there is no empty line after the last requirement.

```
a
c
b
```
is sorted as
```
a
bc
```
but
```
a
c
b

```
works fine.

**Comment by asottile** [comment]
could you try the latest version? this was fixed at some point I believe

**Comment by asottile** [comment]
the [2.4.0](https://github.com/pre-commit/pre-commit-hooks/blob/master/CHANGELOG.md#240---2019-10-28) changelog mentions this was fixed:

> Fix requirements-txt-fixer when file does not end in a newline.
>
>    #414 issue by `@barakreif`.
>    #415 PR by `@barakreif`.

**Comment by Baschdl** [comment]
Yes sorry, it works with `2.5.0`
