### ISSUE TITLE
Idea: check ansible-vault files not commited unencrypted *vault.yml *vault.yaml

### ISSUE THREAD

**Issue by jifox** [pre-commit/pre-commit-hooks#475]
It would be nice to have a check that prevents to commiting unencrypted ansible-vault files.

In my applications I use the file naming convention *vault.yml or *vault.yaml to mark ansible-vault files.

They should contain the string '$ANSIBLE_VAULT' in top line when being encrypted.

```yaml
$ANSIBLE_VAULT;1.1;AES256
61653561323038376533663939623239626464623034656239303465373463383139363434633936
3961646165636637626431333365376665323630303430350a383331393530613234653062373935
33333736336438626266346331333866366662656337626666316565646337333361633231336439
3162313330633034370a356464323031323765643038623264333962396661623033336163626237
63316331393864613036323830623839353334333564643939326439326139653265313030636538
38313332306330643665366166313031333637616534396463653130663938383035616436333264
66663236636133336131623330336264373863386163643631666661393165333736376439326565
39303335383764653866636233663638326466663831383331393538346237666633383233353535
33386463646364623639643037616231363334623765336339376634383733376466336663346265
3833356436386262363164393737356435353538346461653131

```

**Comment by asottile** [comment]
this is far too specific for `pre-commit/pre-commit-hooks` but you can easily write a hook for yourself to do this!  [creating new hooks](https://pre-commit.com/#new-hooks) has some guidance and you can follow many of the examples here or on [pre-commit's hooks list](https://pre-commit.com/hooks.html)

**Comment by asottile** [comment]
or contribute such a check to `ansible-lint`
