### ISSUE TITLE
Allow requirements-txt-fixer keep git+ sorted first

### ISSUE THREAD

**Issue by luiscoms** [pre-commit/pre-commit-hooks#490]
I propose an option to allow keep these require like this.

Expected:
```
git+https://github.com/ateliedocodigo/py-healthcheck.git@1.10.1
ddt<2
flake8
freezegun<1
pytest-cov<3
```

**Comment by palfrey** [comment]
Also the variant where you've got "-e git+https..." as well. I'm getting the fun result where the pip-tools header is being assumed as a comment on the git include, and so it gets moved part way down the results, which is kinda weird!

**Comment by asottile** [comment]
piptools already does sorting so you don't need this hook

**Comment by luiscoms** [comment]
And how piptools do this sort?

**Comment by asottile** [comment]
iirc different and with some comments 🤷

**Comment by luiscoms** [comment]
Can you give more information? A link reference

**Comment by asottile** [comment]
no I can't, just run piptools and observe or read its documentation
