### ISSUE TITLE
end-of-file-fixer should have exclude_files option too

### ISSUE THREAD

**Issue by rambo** [pre-commit/pre-commit-hooks#496]
it since the simple binary checker does not recognize `.hdf5` files as something that should not be messed with and it's tedious to list everything else adding an option for excluding would make things simpler.

**Comment by asottile** [comment]
I think you're confused, it's spelled [`exclude`](https://pre-commit.com/#pre-commit-configyaml---hooks) and that's a _framework_ option that every hook has (nothing special is needed to add this option to individual hooks, just do it!)

you may also consider adding direct support to [identify](https://github.com/chriskuehl/identify) hinting that hdf5 is a binary format

though as far as I can tell, the canonical spelling of the extension is `.h5` and `identify` already recognizes it as a binary file:

```
$ ~/opt/venv/bin/identify-cli h5ex_t_cmpdatt.h5 
["binary", "file", "non-executable"]
```

**Comment by rambo** [comment]
ah true. Thanks.
