### ISSUE TITLE
end-of-file changes UTF-8 to UTF-16LE on requirements.txt

### ISSUE THREAD

**Issue by Corfucinas** [pre-commit/pre-commit-hooks#504]
For some reasons the `trailing-whitespace`  is inserting a character at the end of the requirements.txt.
This is causing `dependabot` to fail since it cannot parse it => **character** '�'

File can be downloaded here:
[requirements.txt](https://github.com/pre-commit/pre-commit-hooks/files/4936432/requirements.txt)

**Comment by asottile** [comment]
what version are you using? the `trailing-whitespace` hook doesn't involve encodings at all

when I download that file it performs no action:

```console
$ trailing-whitespace-fixer requirements.txt
$ 
```

**Comment by Corfucinas** [comment]
Hi @asottile you are right, I got the wrong hook
It is actually `end-of-file`

Here are the screenshots

![image](https://user-images.githubusercontent.com/53630064/87896469-eb41cb80-ca7a-11ea-94e9-323a58ee92b5.png)
![image](https://user-images.githubusercontent.com/53630064/87896490-f72d8d80-ca7a-11ea-9411-02ee798d91cf.png)
![image](https://user-images.githubusercontent.com/53630064/87896510-0280b900-ca7b-11ea-82e0-5175bbbb1d11.png)

**Comment by asottile** [comment]
you still haven't shared the version information, end-of-file-fixer also doesn't deal with encodings and makes no changes locally against that file

**Comment by Corfucinas** [comment]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: check-yaml
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-toml
    -   id: double-quote-string-fixer
    -   id: fix-encoding-pragma
    -   id: debug-statements
    -   id: check-executables-have-shebangs


That is my .pre-commit-config.yml, version is `pre-commit = "^2.6.0"`, I'm using `Poetry` as my package manager. 
This is happening when I run pre-commit it adds a new line under the file, when it is is uploaded to Github, it renders the line as �

**Comment by asottile** [comment]
what is the encoding of the file locally? I suspect it is not the same as the one you've uploaded (which looks like UTF-8+BOM)

**Comment by Corfucinas** [comment]
`requirements.txt:      UTF-8 Unicode (with BOM) text, with CRLF line terminators`

**Comment by asottile** [comment]
oops, was running against a different file -- now I can see what you're seeing

your file seems to end with some junk bytes that are different from what I've seen with UTF-8-BOM --

```pycon
>>> open('requirements.txt', 'rb').read()[-10:]
b'84698\r\n\xef\xbf\xbd'
```

that byte sequence is the UTF-8 replacement sequence -- unclear why it's there but it appears to be from the source file and not from anything that the fixer is doing
