### ISSUE TITLE
[requirements-txt-fixer] Should editable installs of the local project be listed at the end?

### ISSUE THREAD

**Issue by dougthor42** [pre-commit/pre-commit-hooks#505]
As of v3.1.0, `requirements-txt-fixer` will put editable installs of local packages `-e .` at the beginning of the file like so:

```
# requirements-dev.txt
--extra-index-url http://my-local-server.contoso.local/pyp
--trusted-host my-local-server.contoso.local

-e .

pytest == 5.2.1
```

I'm wondering if this is expected behavior.

Typically, I have seen people put the `-e .` at the end of the file:

```
# requirements-dev.txt
--extra-index-url http://my-local-server.contoso.local/pyp
--trusted-host my-local-server.contoso.local

pytest == 5.2.1

-e .
```

I also do this and I end up passing `-n` when committing changes to my requirements files so that the `-e .` stays at the end of the file. Do I just have observation bias and really my way is the less common option?

**Comment by asottile** [comment]
it just sorts it, and yeah you've got some observation bias (I've only ever seen it at the top)
