### ISSUE TITLE
EOF fixer and trailing whitespace fixer fail on ipynb

### ISSUE THREAD

**Issue by mpariente** [pre-commit/pre-commit-hooks#513]
Both end-of-file-fixer and trailing-whitespace-fixer fail on ipynb but are not successful in fixing them, so the commit always fails. 
How can I fix this? 
Thanks!

**Comment by asottile** [comment]
can you share an example file and output from the `pre-commit run --files ...` command you're running?  there's nothing special about how it works for specific file types (it's generic for any text file)

**Comment by mpariente** [comment]
I never ran the pre-commit like that, I let it happen when committing and this specific file was not changed. 
Now, I ran as you suggested and it worked (failed first but modified, and then passed). 

Thanks for your answer and sorry for the stupid question

**Comment by asottile** [comment]
pre-commit will only run on files changed as part of the commit, probably why it was being skipped when you committed
