### ISSUE TITLE
add exclude folder arg to name-tests-test

### ISSUE THREAD

**Issue by christian-steinmeyer** [pre-commit/pre-commit-hooks#517]
I've followed this [gist](https://gist.github.com/peterhurford/09f7dcda0ab04b95c026c60fa49c2a68) to achieve modularized fixtures within pytest. Unfortunately, now my pre-commit hook *name-tests-test* fails, because it finds the files under the `fixtures` folder (see below) and they indeed don't fulfill the test naming convention, precisely because they don't contain tests. 

My project structure looks like this:
```
./
├── src
├── tests
│   ├── conftest.py
│   ├── fixtures
│   │   ├── my_fixture.py
```

and my `conftest.py` looks like this:
```py
from glob import glob


def refactor(string: str) -> str:
    return (
        string.replace("../", "")
        .replace("/", ".")
        .replace("\\", ".")
        .replace(".py", "")
    )


pytest_plugins = [
    refactor(fixture)
    for fixture in glob("../tests/fixtures/*.py")
    if "__" not in fixture
]

```

I feel like this this setup is a power- and useful one and I would very much enjoy continuing to use this pre-commit hook. My suggestion is to add an argument to exclude a certain folder (in my case the `fixture` folder). What do you think?

**Comment by asottile** [comment]
I put mine in a `./testing` directory personally

but there's nothing stopping you from adding `exclude: ^tests/fixtures/` to your `.pre-commit-config.yaml`

**Comment by christian-steinmeyer** [comment]
Can I somehow restrict that to only the name-tests-test hook? Or do you mean on a level of all pre-commit hooks? That wouldn't really be a solution to the use case I described, since I do want to use all other pre-commit hooks on those fixtures.

**Comment by asottile** [comment]
Here's [the docs](https://pre-commit.com/#config-exclude) -- part of the point of `pre-commit` is it implements inclusion / exclusion such that every tool doesn't need to.

here's an example: https://github.com/pre-commit/pre-commit/blob/8f32c5b929ca99e4d396d27b993017f821f6670a/.pre-commit-config.yaml#L50

**Comment by christian-steinmeyer** [comment]
Cool thanks! I unfortunately didn't find that. Sorry for the hassle.

**Comment by andru1236** [comment]
If you are using the yaml file, you can use the following:
```
exclude: |
            (?x)^(
                path/to/file1.py|
                path/to/file2.py|
                path/to/file3.py
            )$
```

reference: https://stackoverflow.com/questions/75178854/how-do-i-exclude-multiple-folders-and-or-file-patterns-from-pre-commit-analysis
