### ISSUE TITLE
check-added-large-files does not check files when run in a CI loop

### ISSUE THREAD

**Issue by mshawcroft** [pre-commit/pre-commit-hooks#518]
check-added-large-files works as expected when executed as a pre-commit hook, but when executed in a CI loop via run --all-files it does not diagnose over size files.  This appears to be because the list of files provided on the command line is filtered to remove files that are not reported as staged for addition by git diff.  Hence if a developer chooses not to install pre-commit as a git hook and adds an over size file, this will not subsequently be picked up by pre-commit running in CI.

**Comment by asottile** [comment]
this is by design, it's intended to allow existing things to exist but error on anything moving forward

**Comment by asottile** [comment]
@mshawcroft one idea would be to add an option to check everything regardless (not sure what it would be called) -- would you be interested in contributing something like that?

**Comment by mshawcroft** [comment]
@asottile Im happy to propose a patch.

I don't have any great suggestion for an option name, but note that some of the other commands in the repo appear to adopt a convention of --xxx and --no-xxx,  so how about --no-check-only-staged ? 

There is one other command, check_case_conflict, that also has the implicit filter for staged files. I propose to add the same option to that command.

**Comment by asottile** [comment]
maybe `--enforce-all`? like "enforce all files"?
