### ISSUE TITLE
Pep8 Conflict - version 1.6.2 is automatically installed, breaks many plugins.

### ISSUE THREAD

**Issue by paul-oreilly** [pre-commit/pre-commit-hooks#52]
Currently pep8 version 1.6.2 is installed into the virtual env's created for each repo. However, many of the plugins give a "DistributionNotFound: pep8<1.6,>=1.5.7" error and refuse to run.

This is after a "pre-commit clean" and "precommit autoupdate", and the SHA for the repo is 15b678e9c67c42765c3d579e40672a332f4366d7 (the latest commit)

**Comment by asottile** [comment]
I'm pretty sure you're falling victim to this: https://github.com/pre-commit/pre-commit/issues/157

I've fixed this version conflict here: https://github.com/pre-commit/pre-commit-hooks/commit/4078cbedf0360dce2b7cd02cb2812fc50b76b98d

The stdout of your pre-commit run would be the most useful information. (fwiw I've ran it locally and get this:

```
$ pre-commit clean && pre-commit run --all-files
Cleaned /home/anthony/.pre-commit.
[INFO] Initializing environment for git@github.com:pre-commit/pre-commit-hooks.
[INFO] Installing environment for git@github.com:pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
autopep8 wrapper.........................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for added large files..............................................Passed
Check Yaml...............................................................Passed
Debug Statements (Python)................................................Passed
Tests should end in _test.py.............................................Passed
Fix requirements.txt.....................................................Passed
Flake8...................................................................Passed
```

**Comment by paul-oreilly** [comment]
You are absolutely right. 

Either adding the .pre-commit-config.yaml file to the commit, or using '--no-stash' resolve the issue entirely.

Many thanks!

**Comment by asottile** [comment]
<3
