### ISSUE TITLE
Force rebase on remote branch to keep a cleaner history

### ISSUE THREAD

**Issue by flniu** [pre-commit/pre-commit-hooks#520]
In many projects, we want to avoid merge upstream branch into local branch, instead, we want rebase local branch changes on remote branch to keep a cleaner history. Can we add this checking as a hook?

### avoid merge upstream branch

```
* 0004 (HEAD -> develop) Merge branch 'develop' of github.com:foo/bar into develop
|\
| * 0003 (origin/develop) others commit 2
| * 0002 others commit 1
* | 0001 my commit
|/
* 0000 common ancestor
```

### expected commit history

```
* 0001 (HEAD -> develop) my commit
* 0003 (origin/develop) others commit 2
* 0002 others commit 1
* 0000 common ancestor
```

**Comment by asottile** [comment]
I'm not sure how this would fit into a client hook framework (especially because they can be bypassed).  you probably want to do this in either a CI task or a pre-receive task

do you have an idea on how this would be implemented?

**Comment by flniu** [comment]
I thought this rule was similar with `no-commit-to-branch`, like kind of invention or policy for a project.

I wrote a `commit-msg` hook to check specific patterns:
* `"^Merge branch .* of github\.com:"`
* `"^Merge remote-tracking branch"`
if any of them matched, then reject the commit.

But this morning I found git config `pull.ff=only` and `pull.rebase=true` may solve this problem, on client side. If I want to enforce this policy, I could use a server-side hook.

**Comment by asottile** [comment]
it's a little different, since `pre-commit` doesn't fire for merges (though there is a brand-new `pre-merge-commit` which does) -- but I think you could probably just use `language: fail` for `pre-merge-commit` if you wanted to prevent it (and/or the settings you've suggested)

**Comment by flniu** [comment]
Thank you for your reply.
