### ISSUE TITLE
Pretty-Format-JSON is overenthusiastic about breaking up arrays

### ISSUE THREAD

**Issue by Skylion007** [pre-commit/pre-commit-hooks#521]
I decided to try run pretty-format-JSON on some JSONs in my repo, but unfortunately, it actually made them much, much more unreadable.

As this commit shows: https://github.com/facebookresearch/habitat-sim/pull/813/commits/bfb82fbe1108e26482fb0637292da53bf95818b7

Basically, if I want to represents a 2D or 3D point in a JSON (a common use case), it will split that array so that each number is on a new line which actually makes the JSON much, much harder to read:

For example:
```
{ 
point: [0, 0, 0]
}
```
should not be converted to:
```{ 
point: [
          0, 
          0, 
          0
]
}
```
At the very least, there should be some minimum length / array length before wrapping around the JSON formatter or the optional to configure such behavior.

**Comment by asottile** [comment]
nothing we can do about it, it just calls [json.dumps](https://docs.python.org/3/library/json.html#json.dumps)

**Comment by Skylion007** [comment]
@asottile Can't we just add a call to the builtin python prettyprint moudle to solve this issue?

**Comment by Skylion007** [comment]
Link to the module: https://docs.python.org/3.6/library/pprint.html

**Comment by asottile** [comment]
no, that's not json

**Comment by Skylion007** [comment]
It can be used to reformat JSONs as well though.

**Comment by asottile** [comment]
It cannot, it prints python dictionaries which are not valid json (maybe what you're thinking of?)
