### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by jgowdy** [pre-commit/pre-commit-hooks#523]
Is there going to be or can there be a tagged release of the hooks with the recent additions to make them available for use?  Thank you!  :)

**Comment by asottile** [comment]
just some advice for open source in general: 

**asking for a release is one of the least useful and annoying things you can do**

this software is provided for free -- if you want, consider [sponsoring](https://github.com/sponsors/asottile) to show some support

also note that [you don't need a release to use the latest version](https://pre-commit.com/#pre-commit-autoupdate)

**Comment by jgowdy** [comment]
I apologize for annoying you.  I am now financially sponsoring the project.

**Comment by asottile** [comment]
3.3.0 has been released -- thanks again for your contribution to it 🎉
