### ISSUE TITLE
Remote tracking branch has new changes

### ISSUE THREAD

**Issue by IlyasYOY** [pre-commit/pre-commit-hooks#526]
Sometime happens that here are some changes someone else made before you.

A few times I had a problem that I've merged without any conflicts, but the state of the file was not correct. It'd be nice to be able to prohibit it.

**Comment by asottile** [comment]
there's a setting on github for this ("PR must be up to date" or something like that), but this is outside of the scope of a pre-commit hook (which is intended to be fast and local)
