### ISSUE TITLE
YAML anchors false-positive in check-yaml

### ISSUE THREAD

**Issue by wyfo** [pre-commit/pre-commit-hooks#534]
*check-yaml* hook doesn't support anchors.
With the following file *example.yaml*:
```yaml
.a: &a
  k1: 0
.b: &b
  k2: 1
c:
  <<: *a
  <<: *b
```

I get the following error (i've omitted the stack trace):
```
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "example.yaml", line 6, column 3
found duplicate key "<<"
  in "example.yaml", line 7, column 3
```

However, the yaml is valid; the anchor merging token `<<` seems to be processed as a key instead.

**Comment by asottile** [comment]
#468 and #527 -- your yaml is actually invalid
