### ISSUE TITLE
Is it possible to exclude files for the check-executables-have-shebangs check?

### ISSUE THREAD

**Issue by rquadling** [pre-commit/pre-commit-hooks#535]
Terraform 0.14.0 introduces a dependency control lock file, but creates the file with the executable bit set.

It is NOT executable, and does not have a shebang.

Is there a way to exclude a file (specifically `.terraform.lock.hcl`) from the files being examined.

**Comment by asottile** [comment]
you can use [`exclude:` at the hook level](https://pre-commit.com/#config-exclude) or [`exclude` at the global level](https://pre-commit.com/#top_level-exclude)

**Comment by asottile** [comment]
I think the core issue is here though, and hopefully that'll be resolved at some point: https://github.com/hashicorp/terraform/issues/27116
