### ISSUE TITLE
ENH environment-yml-fixer sorter

### ISSUE THREAD

**Issue by MarcoGorelli** [pre-commit/pre-commit-hooks#537]
I have a local hook which sorts dependencies in conda `environment.yml` files (analogous to this repo's `requirements-txt-fixer`) - would that be a welcome addition to `pre-commit-hooks`?

**Comment by asottile** [comment]
dupe #507

**Comment by asottile** [comment]
hmm that doesn't answer it -- anyway the vision for this repository is to move to be language agnostic so I won't be accepting any new python-specific hooks in it

**Comment by MarcoGorelli** [comment]
makes sense, thanks for your quick response! I'll make my own repo for it then

**Comment by MarcoGorelli** [comment]
Hey @RoyalTS - sure, here you go! https://github.com/MarcoGorelli/madforhooks

Any issues please let me know there so we don't spam this repo's issue tracker
