### ISSUE TITLE
check-vcs-permalinks is a misleading name

### ISSUE THREAD

**Issue by l0b0** [pre-commit/pre-commit-hooks#547]
The regex in pre_commit_hooks/check_vcs_permalinks.py only checks for permalinks in case of linking to line numbers. Based on the name I would expect the test case `b'https://github.com/asottile/test/blob/master/foo%20bar\n'` to be considered a non-permalink, since the file or relevant lines within the file (even if not directly linked) could easily have moved. This should be documented if it's the wanted behaviour.

This plugin also does not have any provision for checking links to providers other than GitHub. Renaming it to something like "check-github-file-line-permalinks" or something similar would avoid confusion. Even better, if you're interested I could change the way it works to not be GitHub-specific, by not hardcoding anything other than maybe the `https://` prefix. At that point, though, the plugin would suddenly be *much* more generic, and might need to be renamed to something like "check-unsafe-links".

**Comment by asottile** [comment]
I'd encourage you to read the history of that file, it has the answers you seek

if you're too lazy to check though here's the tl;dr:
- it's named generically to allow future expansion
- linking directly to a file unversioned is rarely a problem as bad as linking to an unversioned line
- it would false-positive on links to readmes
