### ISSUE TITLE
requirements-txt-fixer doesn't support comments with indent

### ISSUE THREAD

**Issue by greshilov** [pre-commit/pre-commit-hooks#548]
Consider following example `requirements.txt` file:

```
# This comment is fine
a==0.0.1
    #   This comment is not fine
b==0.0.2
# This comment is fine too
```
Script `requirements_txt_fixer.py` will fail with `AssertionError` on line `    #   This comment is not fine`.

**Comment by asottile** [comment]
I kind of agree with the assertion error -- why is that indented?

**Comment by greshilov** [comment]
> I kind of agree with the assertion error -- why is that indented?

it doesn't violate the rules. For example `pip-compile` tool from `pip-tools` package generates files with following structure:

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --allow-unsafe requirements/dev.in
#
aiodns==2.0.0 ; sys_platform == "linux" or sys_platform == "darwin" and python_version >= "3.7"
    # via -r requirements/base.txt
aiohttp-theme==0.1.6
    # via -r requirements/doc.txt
...
```

**Comment by asottile** [comment]
if you're using pip-tools there's no reason to use this hook (as it sorts)

**Comment by greshilov** [comment]
> if you're using pip-tools there's no reason to use this hook (as it sorts)

Agree.  
But it shows that some developers may use indents before comments (it's just a matter of taste).

`pip` itself is ok with indented comments, so why this tool is not?

**Comment by asottile** [comment]
> `pip` itself is ok with indented comments, so why this tool is not?

pip is also ok with unsorted requirements files -- this tool implements a very specific style decision
