### ISSUE TITLE
check-json doesn't detect duplicate keys

### ISSUE THREAD

**Issue by adamchainz** [pre-commit/pre-commit-hooks#554]
The YAML check does this since #351 but since the `json` module's default behaviour is to ignore duplicates, duplicates are still possible in JSON. I think a small `object_pairs_hook` can be used to detect duplicates?

**Comment by MiHarsh** [comment]
Hello Sir, I didn't understand exactly what we have to do. Do we need to add something to check for duplicates? If duplicate values found then we need to raise error? or something else? Please help !!

**Comment by AdityaKhursale** [comment]
Hi @asottile 

I opened PR https://github.com/pre-commit/pre-commit-hooks/pull/558 for this issue. Did local verification for +ve/-ve test scenarios.

However, CI is failing. Could you please help review and let me know what need to be changed?

This is my first contribution in this repo. I am not very familiar with CI checks here and also, fairly new to open source.
Would appreciate your help. 

Following is the local verification -

![image](https://user-images.githubusercontent.com/6341336/108121061-35019b80-70c8-11eb-9f4a-f5a911bdef33.png)

**Comment by asottile** [comment]
I commented on the PR 👍

**Comment by adamchainz** [comment]
Thanks @AdityaKhursale @asottile 👍

**Comment by marcindulak** [comment]
Can this check be made optional, so there is an option to restore the original `check-json` behavior where duplicate keys are allowed? @asottile

**Comment by asottile** [comment]
I don't think so, no -- duplicate keys are a mistake
