### ISSUE TITLE
Fix package names in requirements files (hyphen vs underscore)

### ISSUE THREAD

**Issue by peterdemin** [pre-commit/pre-commit-hooks#559]
pip allows requirements to use hyphen `-` and underscore `_` interchangeably in requirements.txt files.
But when `pip-compile` generates locked files, the convention is transiently broken if the package is also an indirect dependency.
To fix the issue, we currently manually change all package names to have a hyphen `-` in requirements.in files.
This job can be done better by `requirements-txt-fixer` fixer.

**Comment by asottile** [comment]
I believe this has been proposed before -- it's not easy to do correctly because of environment specifiers (`;sys_platform = ...`), git urls (can contain underscores), pip options (values can contain underscores), comments (can contain underscores), and other edge cases that must be handled safely

**Comment by peterdemin** [comment]
I see, thanks for the explanation! I'll think about adding this feature to [pip-compile-multi](https://github.com/peterdemin/pip-compile-multi/blob/master/pipcompilemulti/dependency.py#L48-L54) post-processing step.
