### ISSUE TITLE
check-added-large-files should have an option to exclude files by pattern 

### ISSUE THREAD

**Issue by deebhatia** [pre-commit/pre-commit-hooks#563]
We have a certain use case where we keep sql, json dumps in code base which is mainly autogenerated. I see two possible solutions:
1. Exclude a list of file patterns to allow such big files instead of requiring it to be applied mandatorily to all files.
2. Allow different sizes for different file patterns.

I prefer solution 1.

**Comment by asottile** [comment]
no it should not, that's kinda the point of `pre-commit` so every tool does not need such an option

you're looking for [`exclude`](https://pre-commit.com/#config-exclude)
