### ISSUE TITLE
check-yaml error on '!vault'

### ISSUE THREAD

**Issue by leos** [pre-commit/pre-commit-hooks#564]
In an Ansible yaml file, we're using the `vault` tag - similar to: https://docs.ansible.com/ansible/latest/user_guide/vault.html#managing-multiple-passwords-with-vault-ids

Running `check-yaml` on that file gives an error: `could not determine a constructor for the tag '!vault'`

Looks like the way around this is to use a specific loader class, which seems messy from the `pre-commit` side - https://www.reddit.com/r/ansible/comments/8ihtey/how_do_you_do_yaml_syntax_checks_with_ansible/ - any suggestions on best practice here? Should we just exclude this file? or is there a better way to handle this situation?

**Comment by asottile** [comment]
you're looking for the [`--unsafe`](https://github.com/pre-commit/pre-commit-hooks#check-yaml) option
