### ISSUE TITLE
How to run no-commit-to-branch with CI when merges are tested against pre-commit hooks during CI (BitBucket Pipelines)?

### ISSUE THREAD

**Issue by JulianVolodia** [pre-commit/pre-commit-hooks#568]
Hi,

I had question [here](https://github.com/pre-commit/pre-commit-hooks/issues/265#issuecomment-792526199) but issue was blocked as offtopic/unrelated to issue.
Author of issue was onsidering that no-commit-to-branch was not working on HEAD ref during their CI.

I got issue when my CI runs on merge commit to destination branch i.e. develop.
This is not allowed to make commits on develop branch but still - merges should be allowed.

Now no-commit-to-branch could make assumptions only on refs names. 
I don't see the option to allow some authors to make that (i.e. some merge bot) or do not check some commits (like with commit msg starting with "Merge" i.e...)

I want indeed to check them as ppl are allowed to push to develop. After testing with pre-commit during CI and having success I would likely hit the issue that no-commit-to-branch would.

Why I am asking? I have many hooks listed in pre-commit conf. So, if I want all of them to run but not one.

Still, I want to be able to run this hook always (not use suggested by @asottile SKIP afaik from [here](https://pre-commit.com/#temporarily-disabling-hooks) ) because I have one testing pipeline and want to fail testing on non merge-commits, not on every commit in testing pipeline.

This is BitBucket pipeline.

Appreciate any thoughts, thanks :)

**Comment by JulianVolodia** [comment]
PS sorry @asottile for mentioning there, I thought (from subject and listing) that it was kinda related
PPS maybe there is a way to find out how the merge was done, I would look at it but this would not be responsibility of this commit hook ofc...

**Comment by asottile** [comment]
yeah I agree this isn't the responsibility of this hook

and "kinda related" does not mean you should comment on a 3 year old resolved bug

**Comment by JulianVolodia** [comment]
Thanks for response. Sorry for asking here @asottile are You on some IRC chan or somewhere I want to help and learn in pre-commit and black (anything python related), do You have anything where I could look besides issue trackers?

**Comment by JulianVolodia** [comment]
I swear it is last comment!

**Comment by asottile** [comment]
[yep](https://pre-commit.com/#getting-help)
