### ISSUE TITLE
trailing-whitespace-fixer vs. Markdown

### ISSUE THREAD

**Issue by dupuy** [pre-commit/pre-commit-hooks#57]
The trailing-whitespace hook strips all trailing whitespace, and will match files with a `.md` extension commonly used for Markdown.

While GitHub flavored Markdown (and other common variants) will ignore trailing whitespace, the original Markdown specification at [Daring Fireball](http://daringfireball.net/projects/markdown/syntax#p) says:
> When you *do* want to insert a `<br />` break tag using Markdown, you **end a line with two or more spaces**, then type return.

*emphasis mine*

You could argue that this is a design/spec failure on the level of Make requiring TAB characters and not spaces for rule commands, but the reality is that there are Markdown files that use this feature, and at the very least there ought to be a flag for the trailing-whitespace-fixer that controls whether you want fix Markdown files (in addition to `.md` it is common to see `.markdown` extensions) by normalizing multiple spaces at the end of a non-blank line to 2 spaces or to remove them entirely (a single space at the end of a non-blank line, or any number of spaces on a line that contains only spaces, should always be removed).

I would suggest (and might even implement as a PR) something like `--markdown-linebreak-ext=md,markdown` as the default, indicating that files with `.md` or `.markdown` extensions would have multiple spaces at the end of a line normalized to two trailing spaces.  If you wanted the trailing spaces stripped in all cases, you would use `--markdown-linebreak-ext` or `--markdown-linebreak-ext=` (or maybe `--no-markdown-linebreak-ext`), if you wanted special Markdown handling for other extensions or all files you would use `--markdown-linebreak-ext=md,txt` or `--markdown-linebreak-ext=*`.

**Comment by asottile** [comment]
One interesting (maybe not well documented?) feature of the config file format is repositories can override any of the values in the original configuration.  Don't like the file regex? You can override it with your own regex.  But perhaps better aimed at excluding thing is the `exclude` key which takes a python regex to exclude filenames.  This helps a bit for the "excluding" part of the issue, but not of the markdown-special-cases part of the ticket.

**Comment by dupuy** [comment]
Yep, I'm aware of the override feature and use it extensively to exclude specific files (e.g. don't run autopep8 on setup.py).  I edited my previous comment to suggest a flag for trailing-whitespace-fixer - it has the disadvantage that filename extensions now need to be consistently specified in the files and flags of a hook, but I think it might still be the best option (with the reasonable and safe default, few people would need to configure it explicitly anyhow).

**Comment by asottile** [comment]
The plan in your edit seems acceptable +1

**Comment by dupuy** [comment]
Closed by merge of #58
