### ISSUE TITLE
Allow merges into branches when using the no-commit-to-branch hook

### ISSUE THREAD

**Issue by revolter** [pre-commit/pre-commit-hooks#574]
I tried using the `no-commit-to-branch` hook to prevent direct commits on the main branch, but I noticed that merging branches into it doesn't work either.

Knowing these, I don't understand what is the scope of this hook. Because I see no reason to have a branch with no commits whatsoever on it.

**Comment by asottile** [comment]
I believe the intention is that you'd use an external tool to perform merges (such as github)

**Comment by IngoMeyer441** [comment]
I also tried to use the `no-commit-to-branch` branch hook to allow only merge commits on the main branch. It is true, an external tool can be used to circumvent this check but if you run pre-commit checks also as part of your CI pipeline (for example with GitHub actions), this check can fail later after merging commits. Perhaps it would be better to detect if the latest commit has only one ancestor?
