### ISSUE TITLE
`check-shebang-scripts-are-executable` is not present

### ISSUE THREAD

**Issue by agelter** [pre-commit/pre-commit-hooks#598]
The other hooks work fine, it's just `check-shebang-scripts-are-executable` that isn't resolving.

"[ERROR] `check-shebang-scripts-are-executable` is not present in repository https://github.com/pre-commit/pre-commit-hooks.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this."

Here's my config:

```
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
```

**Comment by asottile** [comment]
it's not released yet

**Comment by agelter** [comment]
That's good to know.  I'm guessing that the docs are just based on the latest in the master branch, then.  Is it possible to add some kind of note to that doc (e.g. 'new in 3.5.0' or similar) so that it's more obvious what hooks are available?  Especially since earlier in that same doc it has version 3.4.0 listed explicitly, and then goes right into the available hooks.

**Comment by asottile** [comment]
not sure what you're suggesting -- it's clearly not there in [v3.4.0](https://github.com/pre-commit/pre-commit-hooks/tree/v3.4.0)'s README

**Comment by asottile** [comment]
the error message also told you exactly what the problem was:

> Perhaps it is introduced in a newer version?

**Comment by agelter** [comment]
I'm saying that most people go directly to the homepage, which is the latest (unreleased) version.  So that's what most people are going to read. Especially when the tip of master's README still references 3.4.0.  Either the reference to 3.4.0 on the readme should be updated to "unreleased", or it would be good to document which features currently aren't released.  Or final option, maybe just a disclaimer at the start of the readme saying "this is for the unreleased version.  For the latest official release documentation, go to <link here>"

**Comment by Kurt-von-Laven** [comment]
@agelter, FWIW this is a widespread convention that pre-commit and many other open-source repositories follow. Not saying there is no way to make this clearer, but it doesn't seem practical to have to constantly change the README back and forth between referring to a version and specifying unreleased or between including a disclaimer and not including said disclaimer?

**Comment by asottile** [comment]
@Kurt-von-Laven I know you think you're being helpful but please stop bumping closed issues or I will have to limit your ability to interact with the project
