### ISSUE TITLE
Add hook for appending newline to end of files

### ISSUE THREAD

**Issue by anderslindho** [pre-commit/pre-commit-hooks#605]
A hook I have use for, and which I've mostly already written (should write up some more tests), is to ensure that files end with a blank newline - i.e. a `add-trailing-newline` hook. This is necessary for certain shells where there are issues reading the last line of includes.

I can't see any material here about contribution, but I did have a brief look through older closed MRs and found that you appreciated issues before opening any MRs.

**Comment by asottile** [comment]
[it already exists!](https://github.com/pre-commit/pre-commit-hooks#end-of-file-fixer)

**Comment by anderslindho** [comment]
I mean as in one additional newline - I am aware of `end-of-file-fixer`. But I realise I may have been a bit stupid; how about adding an option to define the file-endings to `end-of-file-fixer`?

**Comment by asottile** [comment]
I think you're confused, there's no reason to end a file with `\n\n`

**Comment by asottile** [comment]
by the way, your repo violates the LICENSE of this repository -- it must include our LICENSE verbatim because it is a derivative work: https://github.com/anderslindho/pre-commit-hooks (I'd also recommend not using the name `pre-commit-hooks` as it is easily confused with this repository)

**Comment by anderslindho** [comment]
That's a strange statement, I'm not sure what to tell you here exactly. There is a reason, and we run into this in reviews constantly, which is why I thought I just as well may automate the checks.

It does however sound like you quite simply don't believe in this change request, so closing it sounds good.

I'll fix the license.

**Comment by asottile** [comment]
can you demonstrate an actual usecase?  I think you're confusing "ending in a newline `\n`" with "ending with a blank line `\n\n`" -- the latter is a misunderstanding of the former

**Comment by anderslindho** [comment]
You're right - I mean an empty blank line, as in `\n\n`. That was what I was trying to communicate by saying "blank newline", but I should probably not have used the term newline in the first place.

**Comment by asottile** [comment]
can you show what you're actually trying to solve? "This is necessary for certain shells where there are issues reading the last line of includes." is vague and as far as I understand false

**Comment by anderslindho** [comment]
I'm not sure how well this will be formatted.

In a file like:
```
foo()
bar()
```
the function `bar` is not guaranteed to be parsed - it would need to be written as
```
foo()
bar()

```
or optionally
```
foo()
bar()
# ignore
```

**Comment by asottile** [comment]
what shell ?

**Comment by anderslindho** [comment]
IOC shell

**Comment by asottile** [comment]
can you show example code?

**Comment by anderslindho** [comment]
https://github.com/paulscherrerinstitute/StreamDevice/blob/master/streamApp/example.cmd
https://gitlab.esss.lu.se/e3/wrappers/communication/e3-opcua/-/blob/master/iocsh/opcua.iocsh
https://github.com/areaDetector/ADCore/blob/master/iocBoot/EXAMPLE_commonPlugins.cmd

**Comment by asottile** [comment]
2 of those 3 files have a command on the last line (only end in `\n\n`) and the other one ends in a comment -- are you sure?

**Comment by anderslindho** [comment]
I promise you that this is an issue for us
