### ISSUE TITLE
forbid-new-submodules is broken

### ISSUE THREAD

**Issue by m-khvoinitsky** [pre-commit/pre-commit-hooks#609]
The hook does not have an explicit `types` section.
Default `types: [file]` does not match submodules (which are directories). It works only if you commit some regular file together with committing new submodule.
Specifying `types: [directory]` helps but not much: it works as a pre-commit but doesn't as pre-push or any other way when you specify `--from-ref` and `--to-ref`.
I'd suggest stopping [ignoring provided by pre-commit list of files](https://github.com/pre-commit/pre-commit-hooks/blob/f5c42a050bf7deef0d3fa7fde327c1ae3fd4bed1/pre_commit_hooks/forbid_new_submodules.py#L8) and check `git status` for provided files instead of diff.

**Comment by asottile** [comment]
@m-khvoinitsky in order to add a submodule `.gitmodules` needs to be edited -- are you sure about your assertions?  can you describe what you're seeing instead of prescribing a solution?  I suspect you've got an XY problem

**Comment by m-khvoinitsky** [comment]
> in order to add a submodule .gitmodules needs to be edited

That's correct if you're adding submodules intentionally. But if user tries to commit some another git repository inside current one by accident, git complains but obediently adds a "commit" (type 160000) entry in the tree. I was hoping that this hook would prevent such situations too.

> I suspect you've got an XY problem

May be it is. If so, a separate hook which rejects type 160000 entries without corresponding records in .gitmodules suits my needs better. However, implementing proposed chages would make this hook useful in both usecases (which makes sense because rejecting "incomplete" submodule is still rejecting a submodule).
And the (separate) problem with `--from-ref` and `--to-ref` is still a problem — current hook is useless in CI.

**Comment by asottile** [comment]
feel free to take a stab if you think it's worth it, I'm just not sure you're solving something that's actually a problem
