### ISSUE TITLE
end-of-file-fixer should run on all text files

### ISSUE THREAD

**Issue by guykisel** [pre-commit/pre-commit-hooks#61]
Currently end-of-file-fixer is limited to a certain set of file extensions. I have a `.version` file in one of my projects that was created by the pre-commit mirror maker script that doesn't have a newline at the end of the file but isn't fixed by end-of-file-fixer. Is there a reasonable way that end-of-file-fixer could run on any file that appears to be all plaintext without having to specify specific extensions to support?

**Comment by asottile** [comment]
This is planned as part of https://github.com/pre-commit/pre-commit/issues/220

**Comment by guykisel** [comment]
Oh, I totally forgot about that. Should I close this since it's redundant?

**Comment by asottile** [comment]
Eh, this is a good reminder when I get around to the other one
