### ISSUE TITLE
No hook to check for version bump?

### ISSUE THREAD

**Issue by metov** [pre-commit/pre-commit-hooks#615]
Forgetting to bump the package version is an easy and common mistakes for many developers. For this reason I often use a hook that compares the current version to that on the main (or whichever) branch and warns me if they match. This does result in all my PRs starting with a version bump commit, but I consider that a beneficial side effect.

Is there such a thing, or anything similar, for pre-commit? Searching for `version` through this repo and https://pre-commit.com/hooks.html I couldn't find anything relevant. If it doesn't exist, I'm happy to contribute one :)

**Comment by asottile** [comment]
you could write one, but I personally think such a hook is a bad idea.  bumping versions in feature branches is a conflict-ridden workflow

**Comment by metov** [comment]
@asottile That's quite a bit more negative a response than I was expecting for an offer to contribute. But I guess it does settle my main question of whether this already exists.
