### ISSUE TITLE
Add an “exclude folder” option to check-yaml hook.

### ISSUE THREAD

**Issue by jenstroeger** [pre-commit/pre-commit-hooks#616]
(This _may_ be useful for other checkers too?)

So, the problem is that [Helm Chart templates](https://helm.sh/docs/chart_template_guide/getting_started/#a-quick-glimpse-of-mycharttemplates) have the filename extension `.yaml` although the files are [Go templates](https://golang.org/pkg/text/template/)<sup>*</sup> and _not_ YAML files. Even the Helm documentation states:

> **TIP**: Template names do not follow a rigid naming pattern. However, we recommend using the suffix `.yaml` for YAML files and `.tpl` for helpers.

which to me is a disagreeable statement.

And because these template files have the `.yaml` filename suffix, the [check-yaml.py](https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_yaml.py) hook picks them up and then fails:
```
Check Yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

while parsing a flow node
did not find expected node content
  in "deployment/helm/chart/templates/serviceaccount.yaml", line 1, column 3
while parsing a block mapping
...
```
Unfortunately, I don’t own these files and Helm Charts so renaming them is a bit of an ordeal (if at all doable).

If you’re open to a new command-line argument `--exclude` to exclude files/folders that match a given [glob pattern](https://docs.python.org/3/library/glob.html), then I’m happy to provide a PR.

—————
<sup>*</sup> Helm is written in Go ([repo](https://github.com/helm/helm/tree/main/cmd/helm)).

**Comment by asottile** [comment]
there's no reason to do that because pre-commit provides [`exclude`](https://pre-commit.com/#config-exclude)

**Comment by jenstroeger** [comment]
I didn’t catch that, thanks @asottile!
