### ISSUE TITLE
ERROR: No matching distribution found for ruamel.yaml>=0.15

### ISSUE THREAD

**Issue by ShaunMendes** [pre-commit/pre-commit-hooks#617]
![image](https://user-images.githubusercontent.com/32037980/122684020-b4db7600-d220-11eb-9152-435b498e15ac.png)

**Comment by asottile** [comment]
1. don't ever post images of text, they're inaccessible, unreadable, and worst of all unsearchable
2. your python installation is broken "Can't connect to HTTPS URL because the SSL module is not available."

**Comment by ShaunMendes** [comment]
Thanks! Reinstalling the environment worked and apologies for the image.
