### ISSUE TITLE
hook to sort hooks in .pre-commit-config.yaml

### ISSUE THREAD

**Issue by guykisel** [pre-commit/pre-commit-hooks#62]
This might sound a little meta but it would be nice to have a hook that alphabetically sorts the hooks in the .pre-commit-config.yaml in my repo.

**Comment by asottile** [comment]
Would be pretty easy.  The problem with yaml rewriting is it's hard to make it retain the formatting as seen in https://github.com/pre-commit/pre-commit/issues/210 and https://github.com/pre-commit/pre-commit/pull/211

The runtime order is also sometimes important (like I'd rather run autopep8 before flake8, whitespace fixers before anything else, etc. etc.).  But yeah I could see some people wanting alphabetized so it seems like a good idea for a hook.

**Comment by guykisel** [comment]
My main motivation in wanting alphabetized hooks is to make it easy to compare the hooks I'm using vs the hooks that are available to see if there are any I've forgotten to add or added twice.

**Comment by asottile** [comment]
ooh I think we could do that better in the parent project.  I've wanted to make a `pre-commit list-hooks` which shows what's installed / what's not and probably `pre-commit search ...` as well since we have data on http://pre-commit.com/all-hooks.json

How does that sound?

**Comment by guykisel** [comment]
Sounds good to me.

**Comment by asottile** [comment]
closing since this hasn't really moved forward in years
