### ISSUE TITLE
check-yaml: duplicated yaml keys cause unhandled exception

### ISSUE THREAD

**Issue by rogalski** [pre-commit/pre-commit-hooks#632]
FYI
https://sourceforge.net/p/ruamel-yaml/tickets/389/

Steps to reproduce:
- create yaml with duplicated keys
- create pre-commit environment with recent runamel.yaml (0.17.+)
- run `check-yaml` hook

Encounter failure **which includes stack trace** (expected behavior: exception message being written to stdout, without stack trace).

Most likely this ticket will be marked as invalid with link to sourceforge issue in dependency package, but maybe maintainers of pre-commit want to mitigate that in this repository.

**Comment by asottile** [comment]
the stack trace is intended -- the tool is aimed at programmers

**Comment by asottile** [comment]
oh actually it's not, but if it doesn't extend `YAMLError` that's an upstream problem

**Comment by rogalski** [comment]
@asottile  As suspected, thanks :)
