### ISSUE TITLE
question: check-ast with a specific Python version

### ISSUE THREAD

**Issue by neutrinoceros** [pre-commit/pre-commit-hooks#635]
Quick question, feel free to close promptly:
is there any mechanism I can leverage to force pre-commit to install the check-ast hook with a specific version of Python ?
I realised that it could be of great help to prevent myself from committing too modern Python idioms (e.g. debug f-strings in a project that still supports Python 3.6), but I'm not sure how. Thanks !

**Comment by asottile** [comment]
language_version (would like but on my phone)

**Comment by asottile** [comment]
here we go: https://pre-commit.com/#config-language_version

**Comment by neutrinoceros** [comment]
Thank you, this rocks !
