### ISSUE TITLE
hook id: debug-statements - ignores pdb.set_trace()

### ISSUE THREAD

**Issue by 1Mark** [pre-commit/pre-commit-hooks#636]
Should `debug-statements` notify you what line `pdb.set_trace()` is found on rather than the import? Isn't it possible a user removes the import but then has a syntax error? Isn't it better to either notify what line `pdb.set_trace()` is on OR mention both? Not sure if I'm being pedantic.

**Comment by asottile** [comment]
how would the code get checked in with `pdb` being undefined? sounds like you need `flake8`
