### ISSUE TITLE
pretty_format_yaml hook

### ISSUE THREAD

**Issue by abersnaze** [pre-commit/pre-commit-hooks#640]
specifically looking for control of `default_flow_style` on commit.

**Comment by asottile** [comment]
unfortunately there is not a way to machine-write yaml that is style and comment preserving

**Comment by abersnaze** [comment]
from https://sourceforge.net/projects/ruamel-yaml/
 
> ruamel.yaml is a YAML parser/emitter that supports roundtrip preservation of comments, seq/map flow style, and map key order

**Comment by asottile** [comment]
trust me, it does not preserve everything (my name is even on their docs)

**Comment by abersnaze** [comment]
😞
