### ISSUE TITLE
Add support for Duplicate keys for `check_yaml` hook

### ISSUE THREAD

**Issue by ljmf00** [pre-commit/pre-commit-hooks#642]
According to the YAML specification, keys must be unique:

> **3.2.1.1. Nodes:** The content of a mapping node is an unordered set of key: value node pairs, with the restriction that each of the keys is unique.

Although, unfortunately, some real-world YAML configurations may not be conformant with this point and duplicate keys may appear. A clear example of this is the Cirrus CI configuration file, which can define multiple `task` fields.

PyYAML enforces this option by default, which I totally agree with, but would be cool to specifically allow it. This is fairly simple to implement:

```python
yaml = ruamel.yaml.YAML()
yaml.allow_duplicate_keys = True
yaml.load(stream)
```

https://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

**Comment by asottile** [comment]
[--unsafe](https://github.com/pre-commit/pre-commit-hooks#check-yaml)

**Comment by asottile** [comment]
also for cirrus you should use `{uninquename}_task` for naming your keys to conform with yaml specification

**Comment by ljmf00** [comment]
> [--unsafe](https://github.com/pre-commit/pre-commit-hooks#check-yaml)

The `--unsafe` argument is different in the sense that will silently skip some other YAML checks such as undefined or malformed tag properties:

```yaml
foo:
  - !oof

foo:
  - fine
```

This example shows duplicate keys but also a malformed tag property on the second line. I've seen this occur frequently because people want a string typed field instead of a YAML tag.

**Comment by asottile** [comment]
indeed, `--unsafe` is a blanket flag to disable all of the strict checking.  if you're going to violate the specification then all bets are off

**Comment by ljmf00** [comment]
Sure, since there is support for multiple configs of the same hook I see a rare use-case for this. Thanks for your clarification.

**Comment by faizan002** [comment]
I came across this problem and this will kinda force me not to use pre-commit :( 
I have a jenkins configuration yaml file. 
It has several agents sharing many keys :(

**Comment by asottile** [comment]
there's pretty clear instructions how to allow duplicate keys if you scroll up
