### ISSUE TITLE
check-byte-order-marker deprecation

### ISSUE THREAD

**Issue by Dunedan** [pre-commit/pre-commit-hooks#645]
As part of #522 the `check-byte-order-marker` hook got deprecated. If I'm not mistaken there is no replacement hook for the same functionality (checking for BOMs, but not removing them automatically). Am I missing something or why did the `check-byte-order-marker` hook get deprecated?

For our use case we never want pre-commit hooks to change files automatically, but only act as a way to detect violations.

**Comment by asottile** [comment]
yeah it has been moved to fixer only

**Comment by Dunedan** [comment]
> yeah it has been moved to fixer only

Well yes, that's what I also mentioned in my question. I'm still trying to understand why change was made. Can you please elaborate on that?

**Comment by asottile** [comment]
fixers are significantly less toilsome than checkers

**Comment by Dunedan** [comment]
In which regard are they less toilsome? To develop or to use?

For usage I believe it's important to have hooks which only report issues, but don't attempt to fix them. Actually that's how I (and I believe other users as well) use pre-commit exclusively.

Hooks which try to automatically fix something are undesirable in situations where users want to be in control what gets committed and want to review all changes prior to committing.

**Comment by asottile** [comment]
I think you misunderstand how pre-commit works.  hooks may change files but they never are automatically committed in that way (the commit is aborted)

**Comment by Dunedan** [comment]
I was indeed ignorant about what pre-commit exactly does when modifying files. That doesn't however change my preference that I don't want pre-commit to modify files at all.

I still don't understand if hooks are more toilsome to develop or to use. I'd be grateful if you could elaborate on that.

Also what's the strategy for this repository? Remove all check-only hooks eventually? Replace check-only hooks with fixer hooks once a fixer hook becomes available? Something different?

Would you be open for PRs adding check-only functionality to hooks which currently only support fixing?

**Comment by asottile** [comment]
I'm more interested in maintaining fixers than checkers and where possible will be replacing them and not maintaining checkers

checkers are a worse experience for users.  computers are really good at fixing things so just let them do it

I will not be accepting PRs to add check-only modes

**Comment by Dunedan** [comment]
Thanks for your explanations. Much appreciated. :slightly_smiling_face:
