### ISSUE TITLE
Exclude files for end-of-file-fixer

### ISSUE THREAD

**Issue by tlkiong** [pre-commit/pre-commit-hooks#646]
Is it possible to exclude certain files for `end-of-file-fixer` hook?
eg: for generated files that every byte counts, I don't want an extra `\n` just on that file (or file types)

**Comment by MarcoGorelli** [comment]
hey @tlkiong - have you had a look at [exclude](https://pre-commit.com/#hooks-exclude) and all the other ways to filter files?

**Comment by tlkiong** [comment]
Not yet. I did a search site wide and repo wide but couldn't find any. I guess my search-fu wasn't good enough. Let me take a look.
