### ISSUE TITLE
Extending file_contents_sorter.py to sort only part of the file?

### ISSUE THREAD

**Issue by peterjc** [pre-commit/pre-commit-hooks#647]
Re: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/file_contents_sorter.py

I typically write my ``requirements.txt`` files and other data files with a header using ``#`` prefixed lines, which I would want to be left untouched if sorting the rest of the file. e.g. https://github.com/peterjc/thapbi-pict/blob/v0.10.1/requirements.txt

A more complicated example is https://github.com/biopython/biopython/blob/master/CONTRIB.rst with a header where later lines are checked for sort order with ``grep "^- " CONTRIB.rst | LC_ALL=C sort -u -c -f`` (cross reference example on https://github.com/pre-commit/pre-commit/issues/2042 where I can do this with a system hook).

Does it make sense to extend ``file_contents_sorter.py`` to optionally skip a header (e.g. defined by number of lines like ``12``, or a prefix character like ``#``) and then sort the rest of the file, or something more complicated with a regex defining lines to (not) be sorted? The later gets tricky if sort and no-sort lines are intermixed, e.g. a ``requirements.txt`` with comments part way through a file, akin to the difficulties in sorting Python import lines).

I think the first idea (defining a header which should not be sorted) is simplest, and to cover my simple use cases the argument could be an integer (number of lines) or a single character prefix (other than the digits 1 to 9). I could implement that as a PR.

**Comment by asottile** [comment]
I believe you're looking for [requirements-txt-fixer](https://github.com/pre-commit/pre-commit-hooks#requirements-txt-fixer)

**Comment by peterjc** [comment]
Yes requirements-txt-fixer covers part of this, but not my other example which is admittedly perhaps too niche.

I guess if anyone wants to sort things like CSV or TSV data files with a header, and they find this issue, they'll comment here.

For now, I will make do. Thanks.
