### ISSUE TITLE
Skip `no-commit-to-branch` When `CI` Is Defined

### ISSUE THREAD

**Issue by Kurt-von-Laven** [pre-commit/pre-commit-hooks#653]
Many continuous integration platforms set the `CI` environment variable since it's fairly common for tools to need slightly different settings when running in CI. Presently, one can set the `SKIP` environment variable to `no-commit-to-branch`, but it would be ideal for `no-commit-to-branch` to effectively skip itself in CI. It would probably be necessary to offer an option to disable this behavior (e.g., `--enforce-in-ci`).

**Comment by asottile** [comment]
duplicate: https://github.com/pre-commit/pre-commit-hooks/issues/265#issuecomment-792805360

**Comment by Kurt-von-Laven** [comment]
This is not a duplicate. #265 makes no mention of the `CI` environment variable.

**Comment by asottile** [comment]
I carefully linked to a specific comment with the duplicate resolution

**Comment by Kurt-von-Laven** [comment]
Yes, I saw. I had already read that entire thread before posting this issue and paraphrased the exact comment you linked me to in this issue. Do you have an objection to `no-commit-to-branch` succeeding when `CI` is defined? I am happy to implement this change if not, but I don't understand why it wouldn't be a desirable enhancement.

**Comment by asottile** [comment]
I do have an objection -- there is already a designed methodology for skipping which is the `SKIP` argument
