### ISSUE TITLE
check-added-large-files does not run correctly in parallel, needs require_serial to work correctly

### ISSUE THREAD

**Issue by robert914** [pre-commit/pre-commit-hooks#656]
`check-added-large-files` hook does not work properly when multiple large files are present to be staged. It will randomly fail on some of the files each time you run it depending on how it groups the files for parallel execution:

```
❯ git commit
Check for added large files..............................................Failed
- hook id: check-added-large-files
- exit code: 1

x/a/bigfile (10726 KB) exceeds 10000 KB.
x/c/bigfile (10726 KB) exceeds 10000 KB.
x/b/bigfile (10726 KB) exceeds 10000 KB.
❯ git commit
Check for added large files..............................................Failed
- hook id: check-added-large-files
- exit code: 1

x/c/bigfile (10726 KB) exceeds 10000 KB.
x/a/bigfile (10726 KB) exceeds 10000 KB.
❯ git commit
Check for added large files..............................................Failed
- hook id: check-added-large-files
- exit code: 1

x/b/bigfile (10726 KB) exceeds 10000 KB.
x/a/bigfile (10726 KB) exceeds 10000 KB.
```

We had to enable `require_serial: true` in our hook config to get it to work properly. We suspect that the call in the hook to `git lfs status --json` is not working properly when run multiple times in parallel in the same repo. After adding `require_serial: true` to our hook config, the commit/check works correctly:
```
❯ git commit
Check for added large files..............................................Passed
```

Maybe `require_serial: true` should be set by default in the `pre-commit-hooks` repo definition in `.pre-commit-hooks.yaml`?

**Comment by asottile** [comment]
sounds like a bug in lfs -- I'd recommend debugging further on that and opening an upstream issue in that case

there isn't anything specific to how `check-added-large-files` works that wouldn't be parallel safe so I'm inclined to believe the bug is not here but there

**Comment by robert914** [comment]
Wrong, I just ran `git lfs status --json` multiple times like `pre-commit` would do, and it errors out: ```

**Comment by robert914** [comment]
You need to fix this, your hook runs `git lfs status --json` multiple times in the same repo simultaneously due to parallel execution by `pre-commit`, and that's not allowed for `git lfs` commands.

**Comment by asottile** [comment]
> Wrong, I just ran git lfs status --json multiple times like pre-commit would do, and it errors out:

just as I suspected -- this is a bug with `lfs` -- please take it to their tracker
