### ISSUE TITLE
check-added-large-files does not run correctly in parallel, needs require_serial to work correctly (con'd)

### ISSUE THREAD

**Issue by robert914** [pre-commit/pre-commit-hooks#657]
I added a print statement to `CalledProcessError` that you have in the code: 

```
❯ pre-commit run
Check for added large files..............................................Failed
* hook id: check-added-large-files
* exit code: 1

CalledProcessError happened
CalledProcessError happened
x/a/bigfile (10726 KB) exceeds 10000 KB.
x/c/bigfile (10726 KB) exceeds 10000 KB.
CalledProcessError happened
x/b/bigfile (10726 KB) exceeds 10000 KB.
CalledProcessError happened

```

You aren't handling errors properly, so I don't know how you can blame `git lfs` on this. You just return an empty file list, and then the code continues without any indication of an error occurring. It took us an hour just to figure out the hook wasn't running properly even though our file was properly added to LFS. You should at least report that `git lfs` is erroring out for some reason, not just assume no files were returned.

**Comment by asottile** [comment]
dupe #656
