### ISSUE TITLE
Hook to prevent commits to master

### ISSUE THREAD

**Issue by guykisel** [pre-commit/pre-commit-hooks#67]
In many workflows, you almost never want to commit to master. A lot of common workflows are based around committing to feature branches, then opening pull requests. For these workflows, it would be handy to have a hook that warns you if you accidentally try to commit to master and suggests switching to a branch (I know I've done this by accident before).

**Comment by asottile** [comment]
++ it'd be nice to also permit merge commits to master (since that's a common workflow as well when pushing)

**Comment by asottile** [comment]
https://github.com/pre-commit/pre-commit-hooks/blob/16879bcf16f65e354af40bf3c7f13c0308f52a6d/.pre-commit-hooks.yaml#L200-L207 seems to satisfy this
