### ISSUE TITLE
Hook to delete branches that have already been merged into master

### ISSUE THREAD

**Issue by guykisel** [pre-commit/pre-commit-hooks#68]
Not sure if this sort of functionality makes sense to have in a hook, but I figured I'd suggest it and see what people think. I like to clean up my local repo now and then so that I don't have a ton of obsolete branches lying around. There are some scripts and tools people have written that do this, but you still have to remember to actually run them. Could be nice to just have it happen automatically when you're committing.

**Comment by asottile** [comment]
Hrm, not sure if this is in scope of committing, might make sense more for pushing though

**Comment by guykisel** [comment]
Turns out you can `git fetch --prune`, so having a hook for this would probably be redundant. http://stackoverflow.com/questions/18308535/automatic-prune-with-git-fetch-or-pull
