### ISSUE TITLE
Bug: Sorts requirements.txt badly

### ISSUE THREAD

**Issue by ErikPGJ** [pre-commit/pre-commit-hooks#684]
I have a requirements.txt-like file which pre-commit requirements-txt-fixer sorts badly.

Annoyingly, it sorts this

#
${EXT_GIT_REPOS_DIR}/rpwi_pipeline_l0tol1a_lp
${EXT_GIT_REPOS_DIR}/rpwi_pipeline_l0tol1a_mime
${EXT_GIT_REPOS_DIR}/rpwi_pipeline_l0tol1a_hf
${EXT_GIT_REPOS_DIR}/rpwi_pipeline_l0tol1a_lf

to become this

${EXT_GIT_REPOS_DIR}/rpwi_pipeline_l0tol1a_hf
${EXT_GIT_REPOS_DIR}/rpwi_pipeline_l0tol1a_lf
#
${EXT_GIT_REPOS_DIR}/rpwi_pipeline_l0tol1a_lp
${EXT_GIT_REPOS_DIR}/rpwi_pipeline_l0tol1a_mime

(But thanks for the software anyway... :-) )

**Comment by asottile** [comment]
I can't reproduce, this is what it does for me:

```diff
$ diff -u t.txt.before t.txt
--- t.txt.before	2021-11-11 07:38:45.867694177 -0800
+++ t.txt	2021-11-11 07:38:53.091700391 -0800
@@ -1,4 +1,4 @@
-${EXT_GIT_REPOS_DIR}/rpwi_pipeline_l0tol1a_lp
-${EXT_GIT_REPOS_DIR}/rpwi_pipeline_l0tol1a_mime
 ${EXT_GIT_REPOS_DIR}/rpwi_pipeline_l0tol1a_hf
 ${EXT_GIT_REPOS_DIR}/rpwi_pipeline_l0tol1a_lf
+${EXT_GIT_REPOS_DIR}/rpwi_pipeline_l0tol1a_lp
+${EXT_GIT_REPOS_DIR}/rpwi_pipeline_l0tol1a_mime
```
