### ISSUE TITLE
Add support for allow duplicate keys for check-yaml hook

### ISSUE THREAD

**Issue by peitili** [pre-commit/pre-commit-hooks#688]
I tried to introduce pre-commit to our open source project https://github.com/tilezen/vector-datasource

But the check-yaml hook complains about duplicate keys, I think the project uses a different standard of yaml that allows duplicate keys. 

So we hope that the check-yaml hook can support duplicate keys as an option. 

```
while constructing a mapping
  in "yaml/places.yaml", line 147, column 7
found duplicate key "<<"
  in "yaml/places.yaml", line 148, column 7

To suppress this check see:
   http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

while constructing a mapping
  in "yaml/pois.yaml", line 6, column 5
found duplicate key "source" with value "{}" (original value: "{}")
  in "yaml/pois.yaml", line 14, column 5
```

**Comment by asottile** [comment]
dupe #468 #681

please search the issue tracker next time!
