### ISSUE TITLE
Hook to compare local branch to same branch in remotes

### ISSUE THREAD

**Issue by guykisel** [pre-commit/pre-commit-hooks#69]
Sometimes if I'm collaborating with someone on a branch in a remote repo, it's easy for branches to get out of sync when they push commits that conflict with my local commits. This can lead to messy conflict resolution. Could be nice to have a hook that checks to see if my local branch is up to date with the remote versions of the same branch, or even checks to see if my local branch could be in conflict with the remote master that it would eventually need to be merged into.

**Comment by asottile** [comment]
this would probably require a full git fetch which would be kinda slow for commit time -- going to close this for now since we haven't made any progress on this -- thanks for the issue though!
