### ISSUE TITLE
Provide a multi-purpose generic config example file

### ISSUE THREAD

**Issue by davidferlay** [pre-commit/pre-commit-hooks#694]
# Context

- _pre-commit-hooks_ includes a lot of hooks that could be useful to any project, regardless of  it's tools and languages used

# Current

- The repo does not offer any example file at the moment

# Proposed

- The repo could propose an example file with sane default that could apply to any project, either as a file (like [`example.pre-commit-config.yaml`](https://github.com/davidferlay/pre-commit-hooks/commit/671b9c6a10efa0b4b8e6434ea5546c96129e8f19) either as a code block in readme

**Comment by asottile** [comment]
there's already `pre-commit sample-config`
