### ISSUE TITLE
trailing_whitespace_fixer: Ignores Unicode `U+200B﻿`

### ISSUE THREAD

**Issue by Casey-Kiewit** [pre-commit/pre-commit-hooks#700]
I recently ran into several files with zero-width spaces at the end of empty lines. `trailing_whitespace_fixer` ignores any whitespace before the invisible `U+200B` character, presumably because it regards it as a non-whitespace character.

Example text that results in this behavior:
```python
class Test:
    def test(self) -> None:
        """Test.
                ​
        Testing...
        """
```
hook won't trim the empty space between the lines of the docstring.

**Comment by asottile** [comment]
yeah that character isn't considered a whitespace character, but you can use the [--chars](https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace) option to customize the behavior
