### ISSUE TITLE
Support GitLab's "!reference tags"

### ISSUE THREAD

**Issue by k-bu** [pre-commit/pre-commit-hooks#701]
If I use GitLab's custom _!reference tags_ in a YAML (see https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#reference-tags), then I get following error:
```
Check Yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

could not determine a constructor for the tag '!reference'
  in ".gitlab-ci.yml", line 263, column 7
```

Or is there a way to ignore specific lines in a .yml file for the YAML checker?

**Comment by asottile** [comment]
please check the docs: https://github.com/pre-commit/pre-commit-hooks#check-yaml

you're looking for the unsafe option

**Comment by k-bu** [comment]
Thank your very much!

**Comment by tspearconquest** [comment]
Hi, I wanted to ask about using the `--unsafe` option. Could this accidentally lead to a developer system being compromised by inadvertently running untrusted code through the yaml parser?

This being open source, I think it could happen to anyone contributing to any project in a hostile territory and lead to larger complications across the ecosystem.

I saw a blog post a few mins ago that covered some examples of how to accomplish loading untrusted arbitrary tags safely using PyYAML. I'm not sure if it would be possible to implement here as I'm fairly beginner level with Python and I know this uses ruamel.yaml which was forked from PyYAML, but I would be willing to share the post and try to take a stab at an implementation if an issue would be accepted considering how to properly accomplish the ask of this issue in a more general-but-secure way.

Please let me know.

**Comment by asottile** [comment]
there's nothing to implement here -- `--unsafe` allows non-portable and potentially arbitrary code execution constructs in your yaml file -- it does not trigger arbitrary code execution in the linter however

**Comment by asottile** [comment]
you can also read exactly what the argument does in the README: https://github.com/pre-commit/pre-commit-hooks#check-yaml

**Comment by tspearconquest** [comment]
Thanks. I see now it was my not understanding how `pass` operates in the code. Thanks for clarifying.
