### ISSUE TITLE
Proposal: docstring-quote-fixer

### ISSUE THREAD

**Issue by radoering** [pre-commit/pre-commit-hooks#705]
There is already a double-quote-string-fixer hook. Would you consider adding a similar hook for fixing the quotes of docstrings (which  should always be triple double quoted according to PEP 257)? In detail, the hook should replace single/double and triple single quoted docstrings with triple double quoted docstrings. (If such a hook had a chance of being added, I am inclined to make a corresponding PR.)

I know there is an overlap with [docformatter](https://github.com/myint/docformatter). However, it is difficult (probably not even possible) to configure docformatter in a way that it only fixes the quotes and leaves line breaks in each docstring alone. Thus, a simpler and  more narrow hook might be useful in some cases.

**Comment by asottile** [comment]
I'm planning to split out python specific things and not add more here
