### ISSUE TITLE
Add option to check YAML with tags

### ISSUE THREAD

**Issue by AvdN** [pre-commit/pre-commit-hooks#708]
Currently `ruamel.yaml.YAML()` is instantiated with `typ='safe' as argument, this gets you the faster C loader, but this only supports (part of) YAML 1.1. 

When instantiated as `YAML(typ='rt')`, YAML files that contain tags can be loaded as well. This is a safe load, like the safe loader it will not allow executing arbitrary code. The tag is not interpreted in any way, it is just attached as an attribute to the internal representation of the map/sequence/scalar that is constructed during construction (i.e. `CommentedMap`, `CommentedSeq`, `TaggedScalar`, etc)

This is slower than the `typ='safe'` loading, but it seems some people want to use it, so an option for this would nice.

https://stackoverflow.com/q/70495348/1307905

**Comment by asottile** [comment]
please read [the readme](https://github.com/pre-commit/pre-commit-hooks#check-yaml) it's short and addresses this

**Comment by mlisovyi** [comment]
Could you please comment on how does the documentation address this question?

`--unsafe` seems not to be equivalent to the proposal of @AvdN , as he proposes a variant of the **safe** load (to my very limited understanding of YAML)

**Comment by asottile** [comment]
`--unsafe` is the designed mechanism to support unsafe and non portable extensions such as `!reference` (a non-standard tag)
