### ISSUE TITLE
Change directoy where hook is executed

### ISSUE THREAD

**Issue by ce-tcholewik** [pre-commit/pre-commit-hooks#709]
Sorry if that has been answered already but I just can't seem to find it.
I am trying to use a hook `sqlfluff` which assumes that at executed directory certain files exist(like `.sqlfluff` or more importantly in my case that `dbt_project.yml`). However my team follows convention where needed file is not in git root directory but in a nested one(we create dedicated directory for `dbt` to keep them separated from other component of the project).

I can't tell if or how would `pre-commit` execute a hook in directory other than git root, is that even possible to do right now?

I know that this technically could be implemented for each hook but this seems to me like a quite general use case that should not be specific of each hook.

**Comment by asottile** [comment]
I suspect part of the reason for not finding the duplicates is looking in the wrong repo!  this one is for a few tools which play nicely with the framework but you're looking for the framework: https://github.com/pre-commit/pre-commit

there's a lot of discussion here: https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+is%3Aclosed+monorepo

the tl;dr is: this isn't supported, git runs hooks from the root of the repository.  usually your particular tool will support `--config` or some such to find configuration and not be working-directory sensitive
