### ISSUE TITLE
Add `--pytest` argument to name-tests-test hook.

### ISSUE THREAD

**Issue by jenstroeger** [pre-commit/pre-commit-hooks#712]
Considering that [`pytest`’s test discovery](https://docs.pytest.org/en/6.2.x/goodpractices.html#conventions-for-python-test-discovery) uses “`test_*.py` or `*_test.py`” file names, I think it makes sense to make this hook a bit more [flexible](https://github.com/pre-commit/pre-commit-hooks/blob/fe7a5361087093b5184460da13e0c56cf37154f4/pre_commit_hooks/tests_should_end_in_test.py#L18) — e.g. by adding a dedicated arg.

Happy to provide PR.

**Comment by asottile** [comment]
the default mode *is* pytest mode -- allowing both is not desirable (pick one and stick with it for consistency)

**Comment by jenstroeger** [comment]
Looking at this line of code:

https://github.com/pre-commit/pre-commit-hooks/blob/fe7a5361087093b5184460da13e0c56cf37154f4/pre_commit_hooks/tests_should_end_in_test.py#L18

File names like `test_foo.py` (an [acceptable PyTest filename](https://docs.pytest.org/en/6.2.x/goodpractices.html#conventions-for-python-test-discovery)) fail for the hook:
```
> pre-commit run name-tests-test --all-files
Tests should end in _test.py.............................................Failed
- hook id: name-tests-test
- exit code: 1

tests/test_something.py does not match pattern ".*_test\.py"
```
unless I allow them with the `--django` option — although my project doesn’t use Django at all (thus expecting that option is a bit misleading).

So, if we were picky then the above line should change to
```python
test_name_pattern = r'test.*\.py' if args.django else r'test_.*\.py|.*_test\.py'
```
which is actually correct considering PyTest’s documented file name patterns.

Furthermore, I’d consider changing `Tests should end in _test.py` message

https://github.com/pre-commit/pre-commit-hooks/blob/8559bc59363e88f06689882997655cff7dd24803/.pre-commit-hooks.yaml#L165

because it’s incorrect when using the `--django` option.

**Comment by asottile** [comment]
yes of course I understand that, I am a pytest core maintainer

the tool chooses instead to enforce a _convention_ rather than letting you loosely use multiple naming ideas -- but it gives you the freedom to choose which convention you prefer

if you don't want to pick a convention them simply don't use the tool

note also that the tool's existence predates pytest's change in convention (allowing both names)

while we're being pedantic, note also that pytest is not spelled "PyTest" but is stylized "pytest"

**Comment by jenstroeger** [comment]
Thank you for the context! 

> note also that the tool's existence predates pytest's change in convention (allowing both names)

Alrighty, time to update the tool/hook then 😉

Alternatively, how about adding a `--pattern` option where folks can specify a custom file name patterns? The `--django` option could stay for back-compat. I can provide a PR, if that helps.

> Furthermore, I’d consider changing `Tests should end in _test.py` message
> 
> https://github.com/pre-commit/pre-commit-hooks/blob/8559bc59363e88f06689882997655cff7dd24803/.pre-commit-hooks.yaml#L165
> 
> because it’s incorrect when using the `--django` option.

Would you like a PR for that change?

**Comment by asottile** [comment]
I'm sorry but you're not listening, I'm not going to continue this discussion
