### ISSUE TITLE
Write hook that guards against blank `except:`

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit-hooks#72]
Should include some description of why this is potentially bad in the error message.

Something like:

'except: will also catch intentionally fatal exceptions such as `KeyboardInterrupt` and `SystemExit`.  You probably want `except Exception:`, if  you actually want to grab all exceptions including fatal ones, use `except BaseException:`'

**Comment by guykisel** [comment]
Wouldn't that be caught by the flake8 hook?

**Comment by asottile** [comment]
No but pylint will

**Comment by asottile** [comment]
Here's a quick local hook I threw together which does this:

https://github.com/Yelp/paasta/blob/68b19b28767b172d8faf88ebf60136b48bf63e01/.pre-commit-config.yaml#L42-L46

**Comment by asottile** [comment]
pep8 added this: https://github.com/PyCQA/pycodestyle/commit/543f12b06592c53e2e60edc4846ee02ab9550e8b
