### ISSUE TITLE
Add flag to disallow new line on JSON format.

### ISSUE THREAD

**Issue by Victorsitou** [pre-commit/pre-commit-hooks#720]
I guess the title is really self-descriptive, the implementation should be easy (I'll probably submit a PR later),

The idea would be to not add `\n` when `--new-line` flag is set to `False` (Default to `True`?)
https://github.com/pre-commit/pre-commit-hooks/blob/77dcefca9578ec751f9b4add8b79381f831dccbb/pre_commit_hooks/pretty_format_json.py#L30

I've tried some online JSON formatters, and all of them don't add a new line at the end of the file. So, in my opinion, is fine.

**Comment by asottile** [comment]
I suspect you're confused between ending in a newline (`contents\n`) and ending with a blank line (`contents\n\n`) -- the latter is also undesirable but is not what is happening here

the generally agreed-upon standard is that [files end in a newline](https://youtu.be/r5nWtfwK_dk)

even git will complain if you don't:

```diff
$ git diff --staged
diff --git a/f b/f
new file mode 100644
index 0000000..f3cb29b
--- /dev/null
+++ b/f
@@ -0,0 +1 @@
+wat
\ No newline at end of file
```

and this would directly contradict our own hook [`end-of-file-fixer`](https://github.com/pre-commit/pre-commit-hooks#end-of-file-fixer)

so I will not be accepting this additional complexity and maintenance

fortunately, pre-commit makes it trivial to use a forked repository if you think this behaviour is desirable for some reason

**Comment by Victorsitou** [comment]
Oh I see, thanks for your response.
