### ISSUE TITLE
FileNotFoundError due to ill-formatted args in .pre-commit-config.yaml (user error due to confusing documentation)

### ISSUE THREAD

**Issue by jonancm** [pre-commit/pre-commit-hooks#731]
I'm using `pre-commit` 2.17.0 to format JSON files with the `pretty-format-json` hook ([pre-commit-hooks v4.1.0](https://github.com/pre-commit/pre-commit-hooks/tree/v4.1.0)).

```shell
$ python -V
Python 3.9.10
$ mkdir test
$ cd test/
$ python -m venv env
$ . env/bin/activate
$ pip install pre-commit==2.17.0
$ git init .
```

My `.pre-commit-config.yaml` looks like this:

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: pretty-format-json
        args:
        -   --indent "\t"
```

Here's a sample JSON file `sample.json` to reproduce the issue:

```json
{
   "key": "value"
}
```

When I run `pre-commit`:

```shell
$ git add sample.json
$ pre-commit run --all-files
```

I get the following traceback:

```shell
→ pre-commit run --all-files
pretty format json.......................................................Failed
- hook id: pretty-format-json
- exit code: 1

Traceback (most recent call last):
  File "/Users/jonancm/.cache/pre-commit/repootfswouu/py_env-python3.9/bin/pretty-format-json", line 8, in <module>
    sys.exit(main())
  File "/Users/jonancm/.cache/pre-commit/repootfswouu/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/pretty_format_json.py", line 107, in main
    with open(json_file, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '--indent "\\t"'
```

After doing some research on the internet, I came across the code example in [this tutorial](https://gdevops.gitlab.io/tuto_git/tools/pre-commit/repos_hooks/repo_pre_commit_hooks/pretty-format-json/pretty-format-json.html) that uses an equal sign, so I changed my `.pre-commit-config.yaml` to look like this:

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: pretty-format-json
        args:
        -   --indent="\t"
```

and everything works now.

I had a quick look at the relevant code in [pre_commit_hooks/pretty_format_json.py#L58-100](https://github.com/pre-commit/pre-commit-hooks/blob/40cc31b02ceb72045509576e51d9c82503751422/pre_commit_hooks/pretty_format_json.py#L58-100), but found no issue in the code.

My only guess so far would be that `pre-commit` is passing the arguments from the YAML `args` field after passing the file paths, so `argparse` mistakes the `args` for instances of the `filenames` parameter:

https://github.com/pre-commit/pre-commit-hooks/blob/8fe62d14e0b4d7d845a7022c5c2c3ae41bdd3f26/pre_commit_hooks/pretty_format_json.py#L101

What confused me in the first place is that `README.md` showcases this option without `=`:

https://github.com/pre-commit/pre-commit-hooks/blob/40cc31b02ceb72045509576e51d9c82503751422/README.md?plain=1#L164

so I was trying to use it without `=` sign,

whereas other options are indeed documented correctly:

https://github.com/pre-commit/pre-commit-hooks/blob/40cc31b02ceb72045509576e51d9c82503751422/README.md?plain=1#L133

I would suggest that this line:

https://github.com/pre-commit/pre-commit-hooks/blob/40cc31b02ceb72045509576e51d9c82503751422/README.md?plain=1#L164

be changed to:

```markdown
  - `--indent=...` - Control the indentation (either a number for a number of spaces or a string of whitespace, e.g. `--indent=4`).  Defaults to 2 spaces.
```

to avoid confusing the end-user.

I don't know if a fix in `pre-commit` would be possible, e.g. by passing `args` before `filenames`.

If you think I should report this in the pre-commit repository, please let me know.

**Comment by asottile** [comment]
do you run things on the commandline like `git commit '--message foo'` or do you run them like `git commit --message foo` ?

args is an array of strings, passed literally as arguments (there are no shell injection splicing bugs here!)

**Comment by asottile** [comment]
fwiw, the thing that works fine is `args: [--indent, '\t']`
