### ISSUE TITLE
Proposal: add contribution guidelines

### ISSUE THREAD

**Issue by noahp** [pre-commit/pre-commit-hooks#735]
It might be helpful to maintainers and external contributors to have contribution guidelines to the repo.

For example, a `CONTRIBUTING.md` or section in the `README.md`.

Some reasoning here:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

Could be very simple, such as:

```markdown
# Contributing to this repository

Please first search for related existing or closed Issues and Pull Requests.

All contributions, whether new features or bug fixes, should first be filed as
an Issue before opening a Pull Request. This enables the maintainers to discuss
and agree on the change before investing time in it.
```

**Comment by asottile** [comment]
[CONTRIBUTING.md](https://github.com/pre-commit/pre-commit/blob/master/CONTRIBUTING.md)

**Comment by noahp** [comment]
> [CONTRIBUTING.md](https://github.com/pre-commit/pre-commit/blob/master/CONTRIBUTING.md)

Thanks! Would it be worth adding a section about contribution requirements for new checks (i.e., open an Issue first)?

**Comment by asottile** [comment]
> > [CONTRIBUTING.md](https://github.com/pre-commit/pre-commit/blob/master/CONTRIBUTING.md)
> 
> Thanks! Would it be worth adding a section about contribution requirements for new checks (i.e., open an Issue first)?

maybe, but admittedly that should be the default operating mode anyway and those that aren't doing that are unlikely to read the contributing file

**Comment by noahp** [comment]
Ok, appreciate the attention 👍
