### ISSUE TITLE
safelist fake aws-creds in detect-aws-credentials

### ISSUE THREAD

**Issue by jstoebel** [pre-commit/pre-commit-hooks#738]
I'm not sure if there's a way to do this but I thought I would ask just in case:

I have a yaml file that contains fake aws credentials. they look like this:

```
env:
    AWS_ACCESS_KEY_ID: fake
    AWS_SECRET_ACCESS_KEY: fake
```

I would love to be able to safe list the value `fake` so that the hook can pass. Yes, I could exclude this file for this hook but then it wouldn't catch someone accidentally trying to commit real credentials.

If there's not a way, would you welcome a PR to add that feature?

**Comment by asottile** [comment]
[`exclude`](https://pre-commit.com/#config-exclude) is the intended mechanism for this
