### ISSUE TITLE
Proposal: Run hooks in parallel using multiprocessing?

### ISSUE THREAD

**Issue by cgebbe** [pre-commit/pre-commit-hooks#756]
If I understand the source code correctly, one hook is applied on multiple files using the `ThreadPoolExecutor`. However, the hooks run sequentially. Would it be possible / make sense to run the hooks in parallel?

**Comment by asottile** [comment]
(1) this is the wrong repo (this is a few out-of-the-box tools), you want pre-commit/pre-commit (the framework) (2) there are several duplicates explaining why this is unsafe / not possible -- notably multiple concurrent formatters will corrupt files
