### ISSUE TITLE
Files getting flagged as executables without having execution permissions

### ISSUE THREAD

**Issue by jarkenau** [pre-commit/pre-commit-hooks#762]
I'm currently using the `check-executables-have-shebangs` hook inside a vs-code devcontainer. If I run the pre-commit checks with `pre-commit run -a` the hook tells me that some files are _marked executable but has no (or invalid) shebang_. The problem is that these files don't have execution permission. As an example, look at the `.proto` files. I couldn't find any information regarding this issue with a Google search.

![Screenshot 2022-05-05 at 01 09 29](https://user-images.githubusercontent.com/49768113/166839822-42213360-750b-4423-a000-2260512e70cb.png)
.

**Comment by asottile** [comment]
dupe https://github.com/pre-commit/pre-commit-hooks/issues/528 https://github.com/docker/for-mac/issues/5029
