### ISSUE TITLE
end-of-file-fixer -- "nul" at the and of txt file

### ISSUE THREAD

**Issue by Egoart** [pre-commit/pre-commit-hooks#763]
On modifying automatically generated requirements.txt, end-of-file-fixer adds 'nul' symbol at the end of the file. Is it possible to avoid this?

**Comment by asottile** [comment]
please show an example input and output

**Comment by Egoart** [comment]
I use PowerShell, Win10
Examples attached.
![output](https://user-images.githubusercontent.com/82019192/167312365-3228eba0-aacd-4ba6-bce8-61d24ab594b0.png)
![input](https://user-images.githubusercontent.com/82019192/167312377-733cb2ae-a593-43f4-878e-a61c11caa984.png)
.

**Comment by asottile** [comment]
can you attach the actual files? I suspect they are poorly encoded (utf16?)

**Comment by Egoart** [comment]
Yes, it may be the case... UTF-16LE 
This file is generated automatically by "pip freeze" command. No setup was performed.
[requirements.txt](https://github.com/pre-commit/pre-commit-hooks/files/8647665/requirements.txt)
This file is generated automatically by "pip freeze" command in the environment mentioned above. No setup was performed.

**Comment by asottile** [comment]
you'll want to convert it to utf8, there's some mechanism to make PowerShell do this by default but I do not recall. there's a few other issues in the tracker that can probably be found with a search

**Comment by Egoart** [comment]
I think this mechanism is described here https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_character_encoding?view=powershell-7.2
Thanks for your help!
