### ISSUE TITLE
Feature: Add commit-to-branch hook to whitelist allowed branches

### ISSUE THREAD

**Issue by nantiferov** [pre-commit/pre-commit-hooks#765]
Hello,

I'm aware that it could be achieved with negative matching, like described here https://github.com/pre-commit/pre-commit/issues/1034#issuecomment-493040454

But:
* it's quite complicated and not clear
* impossible to define couple of pattern to cover multiple cases. Have to create even more complicated regex to cover all

My proposal is to add `commit-to-branch` hook, which will whitelist branches instead based on https://github.com/pre-commit/pre-commit-hooks/blob/main/pre_commit_hooks/no_commit_to_branch.py. Protection for main/master branch could be done on GitHub side, so I need only whitelist mostly.
I can create PR if no objections.

**Comment by asottile** [comment]
please use the word "allowlist" instead

___

as decided in #1034 , there's already a way to do this without needing additional maintenance

**Comment by nantiferov** [comment]
Thank you,

Though I cannot see any reference to `allowlist` neither in this code https://github.com/pre-commit/pre-commit-hooks/blob/main/pre_commit_hooks/no_commit_to_branch.py or https://github.com/pre-commit/pre-commit/issues/1034

**Comment by asottile** [comment]
the comment you linked

**Comment by nantiferov** [comment]
Ah, ok, I see, your comment was not about actual option in pre-commit hook.
