### ISSUE TITLE
Improve message on setting exe bit for check-shebang-scripts-are-executable

### ISSUE THREAD

**Issue by mdeweerd** [pre-commit/pre-commit-hooks#770]
Regarding `check-shebang-scripts-are-executable`

The suggestion when a file is not executable and it is supposed to be is:
```
 FILE: has a shebang but is not marked executable!
  If it is supposed to be executable, try: `chmod +x FILE`
```

But `chmod +x FILE` is not enough in my setup, I have to do `git update-index --chmod=+x FILE` .

I propose to add that suggestion to output.

**Comment by asottile** [comment]
please send a patch, there's an equivalent message for the other executable check that you can copy

**Comment by mdeweerd** [comment]
Ok, make PR #773 where I updated both messages.
