### ISSUE TITLE
check-toml to use tomllib builtin for python 3.11

### ISSUE THREAD

**Issue by ericeschmidt** [pre-commit/pre-commit-hooks#772]
When Python 3.11 will be release, would you consider update check-toml to use the native [tomllib](https://docs.python.org/3.11/library/tomllib.html)?

https://github.com/pre-commit/pre-commit-hooks/blob/974bb4de56a6f5da690a64709a864a7d554b7c14/pre_commit_hooks/check_toml.py#L6

**Comment by asottile** [comment]
search the tracker for duplicates
