### ISSUE TITLE
Check for conventional commits and branch names

### ISSUE THREAD

**Issue by Gornoka** [pre-commit/pre-commit-hooks#775]
Hi,
Adding validation for conventional commits and branch name validation to the set of Pre commit hooks would be useful for me and probably others as well, I will be implementing both of them I am just wondering whether you would want to have them as part of this Repo.

With kind regards
Lukas

**Comment by asottile** [comment]
I think conventional commits are a waste of time so I won't be implementing that here

that said, there are a dozen other tools which implement checks for conventional commits if you want to subject your contributors to that -- https://pre-commit.com/hooks.html

**Comment by Gornoka** [comment]
I did not see anything that allowed arbitrary branch name validation with regex yet, if you are aware of something like that i would be pleased to hear about it, but searching in that list did not yield any result for me.

**Comment by asottile** [comment]
you can do that with https://github.com/pre-commit/pre-commit-hooks#no-commit-to-branch

**Comment by Gornoka** [comment]
thanks
