### ISSUE TITLE
Remove UTF16 BOM as well 

### ISSUE THREAD

**Issue by fmms** [pre-commit/pre-commit-hooks#786]
Looking at https://github.com/pre-commit/pre-commit-hooks/blob/main/pre_commit_hooks/fix_byte_order_marker.py just UTF8 BOMs are removed.

Looking at my repository there are many UTF16 BOMs as well.

The logic for removing them can be found in https://gist.github.com/rlee287/e6026243dedc38398298 .

**Comment by fmms** [comment]
I guess removing UTF16 BOM is not a valid option.
However, I had quiet a few files in my repo that where just UTF16 by accident and should have stored as UTF8.

Post processing them with sqlfluff lead to issues.

Thus , I added the following code:
![image](https://user-images.githubusercontent.com/908734/178139509-43e56f46-18b2-4547-bdee-75bf8a64d72d.png)

This solved my problem, not sure if that is desirable, or if there should be another hook, that converts all files to UTF8...

**Comment by asottile** [comment]
yeah the utf16 byte order marker is not redundant like the ut8 one so nothing to do here
