### ISSUE TITLE
Help with prepare-commit-msg hook

### ISSUE THREAD

**Issue by davidmpaz** [pre-commit/pre-commit-hooks#788]
Hi,

thanks for this project. May I ask you some help on some custom **prepare-commit-msg** hook I would like to implement?

Right now I did add some tests which looks promising and I even tested a simplified version of the script from local repo. Still when trying to test that from package I can not manage to make it work or test it effectively. Since I am not an expert, I did already ran out of ideas :)

The WIP is here: https://github.com/davidmpaz/pre-commit-hooks/tree/prepare-commit

The problem I would like to solve is to have more flexibility when it comes to templating the prepared message.

Thank you very much in advance for any hint or advice,
David

**Comment by asottile** [comment]
my message is gone here too!

hi, this isn't the right place for this (this is a few hooks, you probably want the framework itself) and I don't know what you're stuck on to help you.

try asking specifically what you need and name sure to review the docs on https://pre-commit.com -- specifically the ones about writing new hooks and the ones for the hook type you're targeting

if you're looking for tutoring or other 1:1 help I can provide that as well but note that my time is not cheap

**Comment by davidmpaz** [comment]
Everything got settle on the PR thread. 

I did ask help on the assumption that this could be useful. Since it is not, we don't need to spend time on it anymore.

thanks.
