### ISSUE TITLE
detect-private-key should ignore in comments

### ISSUE THREAD

**Issue by curtisforrester** [pre-commit/pre-commit-hooks#795]
I think this hook is far too strict and naive in how it checks for private keys. For me, it fails for a module where we do similar filtering for logging. It fails due to a docstring that contains a note on the types of messages it will mask content for, and fails in the implementation on a variable similar to the `BLACKLIST` variable in this hook module.

* It should attempt to determine if there is an actual key/data that follows the BLACKLIST pattern
* It could also search for a closing pattern with "END <pattern>"

The module in this repo "pre_commit_hooks/detect_private_key.py" would fail for this hook - even though there is _no_ private key in the module.

**Comment by asottile** [comment]
please prefer more inclusive language such as "blocklist"

this hook does not know anything about the language of the file is is parsing (intentionally) -- you can use `exclude` to allowlist files
