### ISSUE TITLE
Feature: "merge-request-max-size" or "forbid-large-commits" 

### ISSUE THREAD

**Issue by AIGeneratedUsername** [pre-commit/pre-commit-hooks#796]
# Possible duplicate or related pull requests and issues 

https://github.com/pre-commit/pre-commit-hooks/pull/665/files

#  "merge-request-max-size"

## Hook description
Give a hint to a developer that it may be better to split a Merge Request into multiple smaller Merge Requests.

## Rationale

Huge Merge Requests are
- very hard to review
- easy to overlook a mistake

## Example error message
```
Your merge request includes 30 files with 1234 lines of the code total.
Such merge requests are hard to review. Consider breaking your changes 
into multiple logical parts within multiple merge requests.
```

## Args

`max_files_in_merge_request = 15`
`max_total_lines_in_merge_request = 400`

## Use cases

Only in Continuous integration, e.g. via `pre-commit run --all-file`.

I think this hook is either useless, or impossible to run during local development. May be it is possible to run this check if we can compare diff size between "main" and the current branch.

# "forbid-large-commits"

## Hook description

Forbid giant commits.

## Rationale 

If a commit includes dozens of files and lines of the code, then most likely a lazy developer wants to commit a bunch of changes that (ideally) could be committed via multiple commits.
I omit here an obvious explanation why frequent committing is (in most cases) helpful both for a developer and a reviewer.

## Example error message
```
Your commit includes 15 files with 882 lines of the code total.
Are you trying to commit huge loosely connected changes with a single commit? 
Consider logically grouping your changes and making multiple commits, or
run SKIP=ignore-large-commits git commit -m "foo"
```

## Args

`max_files_in_commit = 15`
`max_total_lines_in_commit = 400`

## Use cases

I have doubts about this hook. If there are already lots of non-committed changes, then it is hard to make multiple commits. Someone will need to select files and lines of the code manually. But the the advantage of the hook is that this developer will start commit more frequently next time.

**Comment by asottile** [comment]
I think you should pursue this in your own repository first, I don't think it's a valuable check and going to be ignored / skipped any time it is triggered.  it's also very very difficult to get correct (what to do for merge commits? rebases? how do you find what's being merged into?  the concept of a "pull request" is a github thing so it can't be that)
