### ISSUE TITLE
Sort more complex yaml?

### ISSUE THREAD

**Issue by tspearconquest** [pre-commit/pre-commit-hooks#799]
Hi,

I'd like to see if I could feature request a more complex yaml sorter?

The use case is for sorting kubernetes manifests. Thank you in advance.

**Comment by tspearconquest** [comment]
One issue I thought of just now is on manifests with comments there may be a problem sorting those because the comments may no longer align with the keys that they were intended to after sorting, so if it can generate an error when a comment is detected, that would avoid those issues.

**Comment by asottile** [comment]
seems impossible, but feel free to try but it probably won't be accepted here and you should make your own repository
