### ISSUE TITLE
How do we check whether a commit message contains a given string which is not on first line

### ISSUE THREAD

**Issue by RobinMaub** [pre-commit/pre-commit-hooks#802]
Hi everyone,

I would know how to check if my commit message contains the Gitlab changelog tag (Changelog:).

Commit message are used to be:
```
Commit message

Changelog: other
```

I wrote the following:

```
repo: local
hooks:
id: changelog-check
name: Check for changelog entry presence
language: python
entry: '(?!Changelog:)'
args: [--multiline]
stages: [commit-msg]
```

But this never raises a fail when missing or a passed when fine, it is always failing.
Thanks for your help

**Comment by asottile** [comment]
this is not the right place, `pre-commit/pre-commit-hooks` provides some out-of-the box hooks for `pre-commit`
