### ISSUE TITLE
pre-commit fails on "AttributeError: module 'sqlite3' has no attribute 'connect'"

### ISSUE THREAD

**Issue by Deydra71** [pre-commit/pre-commit-hooks#806]
Firstly, thanks for doing great work.
An error occurs while running tox with pre-commit with the usage of sqlite3 module.

Environment
-----------------
RHEL 8.6 up to date
Python3.8

Log trace in verbose mode:
https://pastebin.com/iaL4kpBc

Content of .pre-commit-config.yaml
https://pastebin.com/bK33Ac6A

**Comment by asottile** [comment]
for RHEL support contact your os vendor

and don't paste things off site. then people can't search for the issue
