### ISSUE TITLE
missing shebang

### ISSUE THREAD

**Issue by wwalker** [pre-commit/pre-commit-hooks#808]
`SHEBANG_REGEX` doesn't work with this options on the shebang line:

* `#!/bin/bash -e`

`shellcheck` considers it a valid shebang line.

**Comment by asottile** [comment]
your princess is in another castle?

```console
$ git grep SHEBANG_REGEX
$
```

**Comment by wwalker** [comment]
My sincere apologies.  Yes, the princess is in https://github.com/gruntwork-io/pre-commit.
