### ISSUE TITLE
Feature Request: `check-json` allow terraform interpolation

### ISSUE THREAD

**Issue by timothyclarke** [pre-commit/pre-commit-hooks#811]
I'm running pre-commit against a terraform modules repo that includes an [ECR lifecycle policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_lifecycle_policy)

We try to avoid `<<EOF` syntax where ever possible and this one doesn't have a `data` type :( so I moved the content to a `.json` file however when when I create this as a json file it fails. The content is
```
{
    "rules": [
        {
            "action": {
                "type": "expire"
            },
            "description": "Keep last ${max_tags} images",
            "rulePriority": ${rule_priority},
            "selection": {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": ${max_tags}
            }
        }
    ]
}
```
terraform will substitute `${max_tags}` and `${rule_priority}`. If I quote them then they are typed as strings rather than as integers and so fail AWS validation. Changing the file name so `check-json` doesn't pick it up defeats the purpose of the validation. 

Is there a way we can supply sample values that can be substituted prior to validation eg `.pre-commit.values.<file.json>` ?

Note this is running via a Github action so I think a file in the same or a `.pre-commit` directory is the most practical solution

**Comment by asottile** [comment]
that's not json so `check-json` is correct to flag it

**Comment by timothyclarke** [comment]
@asottile I appreciate that as provided this is invalid json, however when rendered it IS valid json. 
The request was to provide a mechanism to render the template as part of the check.

A response of "no we don't want to do that" or "we'll look the ability to render files to types" was what I was after by including **Feature Request** rather than **Bug** in the title

**Comment by asottile** [comment]
ah your report read to me as "I'm trying to validate something which is not json with check-json" which yeah not surprising that it doesn't work

and yeah what you're doing isn't standard or common in any way so this very simple tool should not grow complexity to support your use case.  your file is not json so a json validator should not accept it
