### ISSUE TITLE
`check-yaml` treats multiple anchors as multiple keys

### ISSUE THREAD

**Issue by W1ndst0rm** [pre-commit/pre-commit-hooks#814]
When using multiple yaml anchors at the same level the check-yaml check treats `<<:` as a duplicate key.

The following snippet is an example will fail when it shouldn't. 

```yaml
test-something:
  stage: testing
  <<: *when_testing
  <<: *check_config_base
  ...
```

**Comment by asottile** [comment]
please search the tracker, there are at least 2 duplicates https://github.com/pre-commit/pre-commit-hooks/issues?q=is%3Aissue+duplicate+keys+is%3Aclosed
