### ISSUE TITLE
forbid-submodules is not present

### ISSUE THREAD

**Issue by ipinak** [pre-commit/pre-commit-hooks#816]
I've tried to use `forbid-submodules`, but I got this error. 

> [ERROR] `forbid-submodules` is not present in repository https://github.com/pre-commit/pre-commit-hooks.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.

I substituted it with `forbid-new-submodules` which worked. 

Checking this https://github.com/pre-commit/pre-commit-hooks/tree/main/pre_commit_hooks I couldn't find anything, so I assume that it's either not implemented or in another repo?

Can I get some help with this?

**Comment by asottile** [comment]
it's not released yet, you can use the latest sha instead for rev or --bleeding-edge if you're using autoupdate

**Comment by asottile** [comment]
@jason-harrison-weir I don't know have you updated?
