### ISSUE TITLE
check-large-files-added doesn't work with LFS

### ISSUE THREAD

**Issue by JannKleen** [pre-commit/pre-commit-hooks#82]
when adding large files to git LFS, the check-large-files-added hook still complains. I think it would be best to add a flag to ignore LFS files, because this plugin is specifically used to solve the problem of adding large files to a git repo

**Comment by asottile** [comment]
Is there an easy way to detect this?  I don't know much about LFS :)

**Comment by JannKleen** [comment]
i think ```git lfs status --porcelain``` should give back all the information needed

**Comment by asottile** [comment]
via #96
