### ISSUE TITLE
Work around upstream bug in ruamel-yaml

### ISSUE THREAD

**Issue by hut8** [pre-commit/pre-commit-hooks#827]
When adding a local tarball with PNPM, the YAML file `pnpm-lock.yaml` cannot be parsed with pre-commit-hook's YAML parser (ruamel) as it is currently instantiated by pre-commit.

```
  file:vendor/my-package.tgz:
    resolution: {integrity: sha512-pDhbxDJeZreZORpBacsEwMkJZtmnqwxDU5knDfLIf1l3YIzUggiIe1P2bz5QHu2mK5giSE3qgoZl28JHBoogTQ==, tarball: file:vendor/my-package.tgz}
    name: my-package
    version: 1.3.37
    dev: false
```

See https://sourceforge.net/p/ruamel-yaml/tickets/391/

The fix is simple; I will open a PR shortly.

**Comment by asottile** [comment]
this isn't our problem, upstream should fix it or quote the values
