### ISSUE TITLE
Documentation and example on autopep8-wrapper doesn't match

### ISSUE THREAD

**Issue by tjwudi** [pre-commit/pre-commit-hooks#83]
As **README.md** says

> Ignore PEP 8 violation types with args: ['-i', '--ignore=E000,...'], see .pre-commit-config.yaml in this repository for an example.

But I don't see this example in <https://github.com/pre-commit/pre-commit-hooks/blob/master/.pre-commit-config.yaml>.

**Comment by asottile** [comment]
Ah right, it was changed at some point when autopep8 started supporting the `[pep8]` section in tox.ini / setup.cfg, I'll update the texts :)
