### ISSUE TITLE
Published documentation inaccurate

### ISSUE THREAD

**Issue by joshriverscambia2019** [pre-commit/pre-commit-hooks#837]
The published documentation at https://pre-commit.com/hooks.html and https://github.com/pre-commit/pre-commit-hooks/blob/main/README.md appear to reflect the state of the production version of these hooks (v4.3.0), but contains references to `forbid-submodules` and perhaps other hooks that have been added but are only available in development builds.

This issue was reported in #835 and #816 and workarounds suggested, but discussion of the documentation issue is off topic on those issues.

If the documentation published on pre-commit.com and the main branch cannot reflect the current release state, it may be worth annotating the documentation pages or specific hooks with information about the supported version of the hook.

**Comment by asottile** [comment]
dupe #835 #816
