### ISSUE TITLE
Feature Request: deadfixtures pre-commit hook

### ISSUE THREAD

**Issue by jgarte** [pre-commit/pre-commit-hooks#839]
I feel like this should be a pre-commit hook:

https://github.com/jllorencetti/pytest-deadfixtures

WDYT

**Comment by asottile** [comment]
it isn't a good candidate:

1. it needs your dependencies installed
2. it needs to do a full discovery of your tests (slow)
3. this repo going forward is for language-agnostic hooks

**Comment by jgarte** [comment]
Thanks for the explanations as to why this would be a bad idea. Makes sense :) 

@asottile 

A different request: can you make a youtube video on pytest-deadfixtures? ;()

**Comment by asottile** [comment]
hmmm I could have sworn I already talked about deadfixtures in a video -- but I can't find any mentions of it -- I've used it pretty successfully a few times now though I tend to prefer `coverage` for finding dead code

**Comment by jgarte** [comment]
@asottile Can `coverage` help with finding unused fixtures though? I'm guessing maybe... but not sure...

**Comment by asottile** [comment]
yep!  they'll show as uncovered code

**Comment by jgarte** [comment]
@asottile Why not [vulture](https://github.com/jendrikseipp/vulture)? because [dead](https://github.com/asottile/dead)?

Are you planning a video on `dead` or was that already done in [this video](https://www.youtube.com/watch?v=dcQZBCDpApc)?
