### ISSUE TITLE
`check-docstring-first` raises false positives on attribute docstrings

### ISSUE THREAD

**Issue by perobertson** [pre-commit/pre-commit-hooks#854]
hen running the `check-docstrings-first` hook on the file `hello_world.py`
```python
#!/usr/bin/env python3
"""Hello world from python."""

MSG = "Hello World"
"""The message to display."""


def main() -> None:
    """Entrypoint for the app."""
    print(MSG)


if __name__ == "__main__":
    main()

```

I get this error message
```
check docstring is first.................................................Failed
- hook id: check-docstring-first
- exit code: 1

hello_world.py:5: Multiple module docstrings (first docstring on line 2).
```

The second string literal at the top level is actually an attribute docstring and can be helpful for editors that display information about the variables.

https://peps.python.org/pep-0257/

From the section on "What is a docstring"

> 1. String literals occurring immediately after a simple assignment at the top level of a module, class, or __init__ method are called “attribute docstrings”.

**Comment by asottile** [comment]
please search the issue tracker next time

**Comment by perobertson** [comment]
> please search the issue tracker next time

I did check the open issues for this and didnt see one. Ill remember to check the closed issues next time.

I did try this workaround https://github.com/pre-commit/pre-commit-hooks/issues/159#issuecomment-559886109 but it doesnt seem to work.

**Comment by twm** [comment]
I did the same &mdash; didn't see an open issue.

Perhaps adjust the description of the check? Right now it is:

> Checks for a common error of placing code before the docstring.

I expected that the check looked for a docstring after top-of-module import blocks.  I wouldn't have been surprised (and filed #1076) if it said what it actually does:

> Only permit module-level docstrings at the top of the file. Forbid attribute docstrings.

**Comment by asottile** [comment]
> I did the same — didn't see an open issue.

be a good citizen and search closed ones too
