### ISSUE TITLE
`pretty-format-json` skip specific file?

### ISSUE THREAD

**Issue by mecampbellsoup** [pre-commit/pre-commit-hooks#858]
I see there is a `filenames` argument: https://github.com/pre-commit/pre-commit-hooks/blob/main/pre_commit_hooks/pretty_format_json.py#L99

Is there any easy way to pass a specific JSON file name we do NOT want to be pretty formatted?

**Comment by asottile** [comment]
the whole point of pre-commit is individual tools don't need to implement complex include / exclude -- please [read the docs](https://pre-commit.com/#config-exclude)

**Comment by jason-harrison-novarc** [comment]
Example of how to ignore Pipfile.lock:

```
        - id: pretty-format-json
          args: [--autofix, --indent, '4']
          exclude: |
            (?x)^(
                Pipfile.lock\
            )$
```
