### ISSUE TITLE
detect-aws-credentials should be configurable to ignore test credentials

### ISSUE THREAD

**Issue by skypanther** [pre-commit/pre-commit-hooks#859]
We are attempting to use [LocalStack](https://localstack.cloud/) in our development stack. It is preconfigured to support some mock AWS credentials. We'd like to be able to reference those in our docker-compose, documentation, etc. However, the detect-aws-credentials hook catches those.

The credentials are:

```
AWS_ACCESS_KEY="test"
AWS_SECRET_ACCESS_KEY="test"
```

Both specifically use (and accept only) the value of `test`

It would be great if we could configure the hook to ignore credentials with this specific value. We don't want to ignore entire files since that would defeat the purpose of the hook.

**Comment by asottile** [comment]
I would recommend using more specific fake credentials

**Comment by skypanther** [comment]
Those are chosen by LocalStack (and used to check [presigned URLs](https://docs.localstack.cloud/user-guide/integrations/aws-cli/#setting-up-local-region-and-credentials-to-run-localstack). So we have no real control over the values.

Also, I'm not sure how using more specific fake credentials would help us exclude them from the detect-aws-credentials hook. Am I missing some functionality that already exists?

**Comment by asottile** [comment]
seems like a poor choice on their part -- maybe suggest a feature request there?  I don't really want to make this more complicated than it already is

**Comment by skypanther** [comment]
How would having a different value for the secrets make any difference in excluding them from checking with the detect-aws-credentials hook? The hook is super simple, just looking for the key names, actually, anything beginning with `AWS_`.

**Comment by asottile** [comment]
well `test` is a super generic string which is likely to show up everywhere -- if it were `AKIA-localstack-test` or something specific it wouldn't show up in the code at all

**Comment by skypanther** [comment]
We submitted a PR to add this functionality to the hook. It is looked specifically at the `AWS_` keys found and then excludes them if they're set to a configurable value. We'd use "test" for that. Someone else would use whatever value they want.

**Comment by asottile** [comment]
yeah and that doesn't seem like a good solution, more a hack to the root problem which is a poor choice by localstack.  you're essentially playing whackamole and poking holes in the validation tool (what if someone put an _actual_ credential for that parameter?)

**Comment by skypanther** [comment]
An actual credential would still be caught.

**Comment by asottile** [comment]
no it wouldn't, you've added a backdoor: `--exclude-values=AKIA` would make the tool completely useless

**Comment by asottile** [comment]
anyway -- the nice thing about the design of pre-commit is I don't need to accept your PR -- you're completely free to maintain use your fork which adds the functionality you want that I don't want to support

**Comment by skypanther** [comment]
> you've added a backdoor: --exclude-values=AKIA would make the tool completely useless

I have no idea what you're talking about. If someone puts and exclude-values string that matches their actual AWS secrets, well, they're dumb and deserve the pain they create for themselves. We want to be able to use --exclude-values=test. Any changes to our precommit config go through the same code reviews we'd do with any other PRs. If someone is dumb enough to pass review on a PR that excludes an actual live key of ours, well, then we're dumb and deserve all the pain we cause ourselves.

I don't see how adding configurability ruins your project.

**Comment by asottile** [comment]
> If someone is dumb enough to pass review on a PR that excludes an actual live key of ours, well, then we're dumb and deserve all the pain we cause ourselves

if that were true you wouldn't need the tool at all
