### ISSUE TITLE
Proposal: Check Only setting

### ISSUE THREAD

**Issue by GadgetSteve** [pre-commit/pre-commit-hooks#861]
Some of the developers that I work with object to any automatic process "fixing" their code, others _myself included_ love to avoid having to do a pile of manual fix-ups.

My suggestion is that all pre-commit filters that **can** fix the issue for you should have an option to toggle between just checking the file _and blocking the commit if the check fails_ **or** checking and fixing the problem for you, _(but still with the need to add the modified file(s) into the commit)_.

What I would like to see is a either a `--fix` or a `check-only` flag ideally with the default being determined by an environmental variable so that individual users can both set their preference and use the pre-commit hooks in `pre-commit run` mode to fix problems if they have the automatic fix disabled.

**Comment by asottile** [comment]
please search the issue tracker, there are many duplicates
