### ISSUE TITLE
How can I use pre-commit-hooks as a standalone package installed by pip?

### ISSUE THREAD

**Issue by PaveTranquil** [pre-commit/pre-commit-hooks#866]
I know how I should use pre-commit-hooks with git using pre-commit, but how should I use these hooks locally when they installed as a standalone package? And why does that need, actually?

**Comment by MarcoGorelli** [comment]
You can run `python -m pre_commit_hooks.check_ast <your file name(s) go here>` (and similarly for the other hooks)
