### ISSUE TITLE
Add a customizable pattern option `name-tests-test`

### ISSUE THREAD

**Issue by hofbi** [pre-commit/pre-commit-hooks#870]
I really like the `name-tests-test` hook and would like to use this for other languages that Python, e.g. C++. My idea would be to extend `pre_commit_hooks/tests_should_end_in_test.py` with an additional mode in the CLI to provide a costom regex pattern for the tests:

```python
    mutex.add_argument(
        '--custom',
        dest='pattern',
        type=str,
        help='ensure tests match the pattern provided',
    )
```

Then, the user could provide for instance `--custom ".*_test\.cpp"`.

The concern I have is, does this cause a potential security issue if something from the CLI is directly passed into the `re.compile`?

**Comment by asottile** [comment]
this has been suggested before. the hook is intended to enforce a specific convention for python tests. perhaps you want to set up a `language: fail` hook?

**Comment by hofbi** [comment]
Sound good, thanks for the hint!

Could you link the previous issue here? I checked existing issues before but didn't found it.

**Comment by asottile** [comment]
you can search "name-tests-test" just as easily as I can, I don't have time to be a high latency search engine
