### ISSUE TITLE
Suggestion for "no_commit_to_branch": Resolve detached HEAD to "HEAD" and continue

### ISSUE THREAD

**Issue by t4n0** [pre-commit/pre-commit-hooks#875]
1. Resolving the branch name is done [here](https://github.com/pre-commit/pre-commit-hooks/blob/7e7049a0bf27cc7b9deb622ba37c2ac1682ed265/pre_commit_hooks/no_commit_to_branch.py#L17) via `git symbolic-ref HEAD`.
2. Given the HEAD is detached commits are unconditionally allowed, see [here](https://github.com/pre-commit/pre-commit-hooks/blob/7e7049a0bf27cc7b9deb622ba37c2ac1682ed265/pre_commit_hooks/no_commit_to_branch.py#L19).

2 is undesired behavior in my use case. I use [giticket](https://github.com/milin/giticket) to automatically add the ticket number from the branch name to all commit messages. Hence I would like to prevent commits to branch names that do not comply with the required naming convention. This works like a charm for almost all cases using "no_commit_to_branch" with a negative lookahead regex - except for a detached HEAD.

Is `git rev-parse --abbrev-ref HEAD` an alternative for 1? It would resolve a detached HEAD to "HEAD". This would allow the user to handle that case in any way they wish.
Is there a good reason for 2 that I am missing?
Would this break existing usages somehow?

Would you consider a PR (fully tested, etc.)?

**Comment by asottile** [comment]
what you're describing would be a breaking change -- arguably for a use case the tool was not designed for

you can pretty trivially write a hook which runs `git rev-parse HEAD` to forbid your special case I imagine without pre-commit-hooks needing to carry this

**Comment by t4n0** [comment]
I see. Thanks for the prompt reply. Will resolve locally.
