### ISSUE TITLE
Proposal: hook to replace http:// with https://

### ISSUE THREAD

**Issue by GideonBear** [pre-commit/pre-commit-hooks#876]
I'm looking for a pre-commit hook that replaces any instance of `http://` with `https://`.
Feel free to close this issue if this doesn't fit this repo.
I can make a PR for this if needed.

**Comment by asottile** [comment]
it's not safe to do wholesale

**Comment by GideonBear** [comment]
> it's not safe to do wholesale

I understand it's not always safe, but for some projects it is. I'll make a hook for it myself.
