### ISSUE TITLE
Feature-request: Check `.gitignore` files

### ISSUE THREAD

**Issue by LecrisUT** [pre-commit/pre-commit-hooks#878]
This would check:
- If a path is added to `.gitignore`, but there is already a file/folder defined there
- If you are forcefully adding a file that is supposed to be in `.gitignore` (maybe staged file before editing `.gitignore`)

**Comment by asottile** [comment]
I don't think this really makes sense as a common hook.  both of those sound rare and rarer than the cases where you'd intentionally do that
