### ISSUE TITLE
Django test file names don't work with directory path

### ISSUE THREAD

**Issue by phoxelua** [pre-commit/pre-commit-hooks#88]
For Django tests file names, **tests_should_end_in_test.py** will mistakenly think file names such as 'app/blah/tests/bad_django_test_fname.py' as valid django test names since the regex ` test_name_pattern = 'test.*.py'` matches anything between between 'test' and '.py'- even '/' and other unintended characters.

**Comment by asottile** [comment]
Closed via #89
