### ISSUE TITLE
Proposal: Check csv file integrity

### ISSUE THREAD

**Issue by DamianBarabonkovQC** [pre-commit/pre-commit-hooks#880]
I propose to create a pre-commit hook that checks that a `.csv` is correctly formatted. Namely, that the number of columns is equal for each row and that the deliminator is all the same.

**Comment by asottile** [comment]
feel free to write your own hook!  this is too specific to be accepted here however

**Comment by jenstroeger** [comment]
@DamianBarabonkovQC if it helps issue https://github.com/pre-commit/pre-commit-hooks/issues/1063 contains a simple CSV check without getting into the specific content of the CSV files.
