### ISSUE TITLE
Proposal: Check gitmodules branch contains submodule commit

### ISSUE THREAD

**Issue by truh** [pre-commit/pre-commit-hooks#894]
`git` doesn't make sure that the commit of a git submodule is on the branch specified in the `.gitmodules`. This makes it easier to overlook accidental submodule changes to a different  branch during review.
A pre-commit hook run on changes to `.gitmodules` and submodule objects could detect such inconsistencies and prevent them from being committed by either returning a non zero exit code or updating the branch in `.gitmodules`.

Would you be interested in making such a hook part of the collection of core hooks or would you prefer it be an external hook?

### Options

- `--allow-unset` - Allow submodules without a branch property in `.gitmodules`. `branch` is an optional property in `.gitmodules` so this option would be useful for compatibility with repos where not all submodules have branch properties. 
- `--update-gitmodules-file` - Update the branch property in .gitmodules if a submodule has a different branch checked out.

For our internal use I've already developed such a hook which you can find here https://github.com/MoonVision/pre-commit-hooks.

**Comment by asottile** [comment]
seems not universally useful, especially because branch seems to be ignored in gitmodules and is not part of git
