### ISSUE TITLE
What if I want to add some test password or private keys in purpose, thanks.

### ISSUE THREAD

**Issue by edwardTianY** [pre-commit/pre-commit-hooks#895]
I am not sure if there is a way to add the test keys in purpose when I enable the ID: detect-private-key in the .pre-commit-config file, thanks.

**Comment by asottile** [comment]
have you read the pre-commit docs?

**Comment by edwardTianY** [comment]
I thinks yes, I read the following link, only get how to use the hooks, did not get the answer of my question, could you pls guide me a litter bit, thanks. https://github.com/pre-commit/pre-commit-hooks/blob/main/README.md

**Comment by asottile** [comment]
like on https://pre-commit.com ?
