### ISSUE TITLE
trailing-whitespace hook is matching on a multiline (""") python string

### ISSUE THREAD

**Issue by ggiesen** [pre-commit/pre-commit-hooks#898]
A fellow contributor to a project has written a unit test that uses a multiline string:

```
    assert (
        rendered
        == """
#beware of the whitespace

  
0

  
1337
  
1

  
2

"""
    )
```

The function the test is testing against is a whitespace control function, and unfortunately the trailing whitespace is the point of the test. I'm a bit surprised that the `trailing-whitespace` hook is mucking about with actual strings, but I'm told it's a very simple regex-based test so likely is not smart enough to deal with multiline strings. My questions are:

1.  It it possible to add an option to have the `trailing-whitespace` hook ignore (multiline) python strings?
2. Is it possible to exclude a portion of a file (as opposed to the whole file)?
3. All of the above?

**Comment by asottile** [comment]
you should refactor your source to not have trailing whitespace
