### ISSUE TITLE
Windows file verification

### ISSUE THREAD

**Issue by sfc-gh-mkeller** [pre-commit/pre-commit-hooks#899]
Windows has a bunch of restrictions on file names which can really easily affect repositories that use mainly Posix for development, but have to build some artifacts on Windows. As an example take a Python project where a wheel needs to be able to be compiled on Windows, but someone checked in a file with the name `2023_04_19-13:56:08.json`.

My proposal is to add a hook that simply verifies file paths are valid on Windows according to [the Windows docs](https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-shares--directories--files--and-metadata#directory-and-file-names).

Maybe the opposite is also true, devs on Windows could create a file that is invalid on OSX. So this hook should maybe verify for all file path pitfalls of Linux, BSD, OSX, and Windows.

For now I'm just looking for some comments and consideration. Our team could look into contributing this, if people think that this would be useful.

**Comment by asottile** [comment]
dupe #589
