### ISSUE TITLE
Repository for community hooks

### ISSUE THREAD

**Issue by pawamoy** [pre-commit/pre-commit-hooks#904]
I was wondering if you'd find value in hosting a repository under the pre-commit organization for community-maintained hooks. It would act as some kind of central repository for community hooks. Some projects do not want to maintain a `.pre-commit-hooks.yml` file themselves, in their repository, but pre-commit users would still prefer the convenience of using a hook with proper default values, defined and maintained somewhere, so that each user does not have to reinvent the wheel. Or maybe that's not at all how it works, and by design the hook *must* be stored in the related project itself? (I'm not a pre-commit user myself)

Ideally there would be no additional maintenance work for pre-commit maintainers, but I think that won't happen and they'll still have to approve and merge pull requests? Maybe you can think of a way to have the community fully responsible of the repository or something?

Sorry if this has been asked before, I couldn't find a similar issue in this repo or the pre-commit one.

Have a nice day!

**Comment by asottile** [comment]
https://pre-commit.com/hooks

**Comment by pawamoy** [comment]
Or maybe you were trying to point me at the mirrors? They're like forks with a hook? Would you setup, say, a MkDocs mirror with a hook for example?

**Comment by pawamoy** [comment]
OK, I take it as a no :slightly_smiling_face: Thanks
