### ISSUE TITLE
'check-ast' hook is failed on a syntax supported by python3.10 and after

### ISSUE THREAD

**Issue by YuXia-SR** [pre-commit/pre-commit-hooks#908]
I tried the "match..case.." syntax supported after python v3.10 ([sample usage here](https://realpython.com/python-enum/#using-enumerations-in-if-and-match-statements)), and the 'check-ast' cannot recognize it as a valid syntax with error message "SyntaxError: invalid syntax".

**Comment by chriskuehl** [comment]
You probably have the hook running using an old Python version, but it's impossible to say unless you provide your pre-commit config and full failure output.

**Comment by YuXia-SR** [comment]
Thanks! It turns out I have poetry env (python 3.10) open on top of conda env (python 3.9)
