### ISSUE TITLE
`double-quote-string-fixer` should not replace double quotes with single quotes for continuation strings

### ISSUE THREAD

**Issue by alex-feel** [pre-commit/pre-commit-hooks#909]
For this code:

```python
    if missing_values_columns:
        error_message += f"The following columns have missing values: {', '.join(missing_values_columns)}. If you " \
                         f"have applied binning, you can change the method to 'equal_number_of_bins'. This will " \
                         f"allow you to create bins that include values from the test dataset without data leakage."
```

`double-quote-string-fixer` will replace double quotes with single quotes in the last f-string, but it should not do so because in this case, you should use double quotes for continuation strings to match ([LIT015](https://pypi.org/project/flake8-literal/#:~:text=LIT015,strings%20to%20match)).

**Comment by asottile** [comment]
our tool predates theirs

**Comment by alex-feel** [comment]
Could you please explain what exactly this means?
