### ISSUE TITLE
Feature: allow lines to be escaped

### ISSUE THREAD

**Issue by shaunc** [pre-commit/pre-commit-hooks#911]
I would like to import pdb to allow optional post-mortem debugging in a script, which is included in a package. In other places, I would like to make sure `breakpoint()` hasn't be forgotten in code.

I'm sure similar escapes would be useful in other places. Perhaps something like `#pragma: ignore` or `#pre-commit: ignore` could be used as a blanket escape for lines to mark as exception?

**Comment by asottile** [comment]
search the pre-commit docs for the standard mechanism for this
