### ISSUE TITLE
proposal: `pretty-format-po` hook

### ISSUE THREAD

**Issue by antonag32** [pre-commit/pre-commit-hooks#914]
Analogous to `pretty-format-json` this hook would:

- sort translation terms alphabetically
- wrap  columns automatically (length is user settable -- defaults to something like 80)

This hook should be very useful to any repository working with translations. I have the implementation ready for it, but thought this repository could be a better home for it.

What  do you think?

**Comment by asottile** [comment]
seems a little too specific and not generically applicable.  also I'm pretty sure po files need a special library to read / write them so it probably wouldn't make sense here.  but it sounds like a fine idea to write as your own open source tool!
