### ISSUE TITLE
Support for .gitattributes to exclude files?

### ISSUE THREAD

**Issue by paulo-raca** [pre-commit/pre-commit-hooks#915]
Hello, and thank you for this great tool :)

I'm adopting pre-commit to verify/prettify source code in my current project, however we have a lot of generate files in the repository (stubs and documentation generated from OpenAPI specs, mocks, etc)

Of course, a lot of the generated code doesn't comply with my desired pre-commit hooks and I need to skip them from being processed with pre-commit.

I can, of course, use `[exclude](https://pre-commit.com/#top_level-exclude)` config, but I've already configured the list of generated files using `.gitattributes`:

```
*_gen.* -diff -merge linguist-generated=true
**/mocks/* -diff -merge linguist-generated=true
...
```

Would it be possible for pre-commit to use that instead of requiring a separate exclude list?

**Comment by asottile** [comment]
no, sorry there's already a way to do this in a file that pre-commit controls and owns
