### ISSUE TITLE
YAML check: false positive for unexpected ":"

### ISSUE THREAD

**Issue by Alexander-Serov** [pre-commit/pre-commit-hooks#918]
In my `.gitlab-ci.yml`, I have the following block:
```
docker-build-deploy:
  stage: build
  services: [docker:dind]
````

This block is correctly parsed by gitlab and by other yaml checkers (such as [yamllint](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.quoted_strings)), but the `check-yaml` hook from this repository fails with:
```
Check Yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

while scanning a plain scalar
  in ".gitlab-ci.yml", line 292, column 14
found unexpected ':'
  in ".gitlab-ci.yml", line 292, column 20
```

It seems like this is a false positive, and quoting the value of the string "docker:dind" which contains a colon is not necessary in this context. According to [YAML specifications](https://yaml.org/spec/1.2.2/#21-collections) a collection is defined by `: ` with space and not by a single colon.

I suggest making sure the code block above correctly passes the check.

(I prefer not to quote this string because it clashes with the default settings of `yamllint`.)

**Comment by asottile** [comment]
we're just a wrapper, report it to the parser

there's also several duplicates and if you're using yamllint there's zero value to check-yaml
