### ISSUE TITLE
End-of-file-fixer breaks markdown-files for sphinx

### ISSUE THREAD

**Issue by aecorn** [pre-commit/pre-commit-hooks#921]
I have two files with very simple content in /docs

**index.md**
`../README.md`

**contributing.md**
`../CONTRIBUTING.md`

When running the pre-commit it runs "end-of-file-fixer".
This "fixes" these two files.
![image](https://github.com/pre-commit/pre-commit-hooks/assets/20161657/16619b1d-2c19-4f41-b60e-eadc0652106c)

When the github-action later tries to run for building with sphinx, it fails because index.md is not a valid file anymore.

![image](https://github.com/pre-commit/pre-commit-hooks/assets/20161657/5f15e022-2136-497a-b154-790e337fe311)
![image](https://github.com/pre-commit/pre-commit-hooks/assets/20161657/899ceb85-4996-457b-9c77-0b83d4fe0ec8)

Currently just excluding the folder in .pre-commit-config.yaml:
![image](https://github.com/pre-commit/pre-commit-hooks/assets/20161657/16a77239-c980-47c9-9746-6a2619bff54d)

**Comment by asottile** [comment]
are you sure those aren't symlinks and you're on windows but did not enable symlinks support?

**Comment by aecorn** [comment]
I made the .md files myself as .md files in VSCode, so if they are symlinks, there must be some Magic that Im not aware of. Is it their content which are making them into symlinks? The pre-commit hooks seem to operate on them as files, both prettier and end-of-file-fixer.

**Comment by asottile** [comment]
I don't think this has anything to do with pre-commit-hooks then -- if they're symlinks yeah I could see that messing them up on windows but a file that just has a path in it doesn't seem like useful markdown

**Comment by asottile** [comment]
yeah they're symlinks as I suspected -- you should enable symlink support on windows https://github.com/statisticsnorway/ssb-project-cli/tree/main/docs
