### ISSUE TITLE
prettier hook (pre-commit/mirrors-prettier) installation hangs forever on node installation

### ISSUE THREAD

**Issue by anjos** [pre-commit/pre-commit-hooks#938]
> N.B.: I'm reporting this here since the mirror itself does not allow one to open issues there.

I created the following section on my `pre-commit-config.yaml` file:

```yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
    - id: prettier
      types_or: [json]
```

to check JSON files and re-format those if need be.  I managed to run `pre-commit autoupdate`, which brought the revision to the shown number.

Upon first run (I'm on macOS if that counts), installation doesn't go through, and hangs forever.  I used a debugger and pin-pointed the location:

```
  File "/Users/andre/mamba/envs/ptbench/lib/python3.11/site-packages/pre_commit/languages/node.py", line 89, in install_environment
    cmd_output_b(*cmd)
    ^^^^^^^^^^^^
```

It seems to hang forever when executing the following `cmd`:

```python
['/Users/andre/mamba/envs/ptbench/bin/python3.11', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/andre/.cache/pre-commit/repoffu6brbv/node_env-default']
```

If I execute this command manually, on the shell, it also blocks forever:

```sh
$ /Users/andre/mamba/envs/ptbench/bin/python3.11 -mnodeenv --prebuilt --clean-src /Users/andre/.cache/pre-commit/repoffu6brbv/node_env-default
/Users/andre/mamba/envs/ptbench/lib/python3.11/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
/Users/andre/mamba/envs/ptbench/lib/python3.11/site-packages/nodeenv.py:48: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
 * Install prebuilt node (20.5.0) .
```

Any ideas on how to fix this?  Thanks!

**Comment by asottile** [comment]
issues are temporarily disabled intentionally. please respect boundaries

**Comment by anjos** [comment]
I thought that was done so issues are reported here instead.  You quickly dismissed it, but the problem reported here seems related to a function in this package!  Before posting, I checked both repos.  If you know of any information, I’d be glad if you can share it.

**Comment by asottile** [comment]
this is clearly not the right place to report issues with nodeenv. it's also not the place to report issues with pre-commit (this is a particular set of tools for pre-commit and it's not a pre-commit problem as you've determined) and it's definitely not a place to report things for prettier.  so you're 0 for 3

**Comment by anjos** [comment]
Thank you for taking the time to point me in the right direction, and apologies for the noise
