### ISSUE TITLE
Hook to add license comments

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit-hooks#94]

**Comment by asottile** [comment]
I'm not sure it would need to be, depending on the scope here. for instance I would probably see this configured as:

```yaml
    -   id: add-license
        args: [--license, apache, --owner, 'Anthony Sottile', --copyright-year, '2018']
```

and then it would ensure comments at the top of files like [this](https://github.com/Yelp/paasta/blob/ea5c03be3382f762503381410890e76e03a4c916/paasta_tools/drain_lib.py#L1-L13)

**Comment by jcpunk** [comment]
Personally, I'd love something that checks for `SPDX` tags.

**Comment by asottile** [comment]
there are existing hooks for this in https://pre-commit.com/hooks.html
