### ISSUE TITLE
Bug: `pretty-format-json` formats Jupyter Notebooks inconsistently

### ISSUE THREAD

**Issue by Zeitsperre** [pre-commit/pre-commit-hooks#943]
I've been trying to reproduce a strange behaviour locally that I'm experiencing on GitHub CI with regard to the `pretty-format-json` hook.

I have a repository that contains Jupyter Notebooks and is configured to use pre-commit.
 * When running `pre-commit run -a` locally, no hooks fail (tested with Python3.8 and Python3.11). 
 * When running on GitHub CI (either running it via the Action or by installing and running it explicitly), the `pre-commit` hook for `pretty-format-json` catches formatting errors with my Jupyter Notebooks. Oddly enough, this hook doesn't fail from the `pre-commit.ci` integration.

My workaround is to mark `pretty-format-json` to ignore `.ipynb` files, but this is strange behaviour and has caught of my colleagues by surprise.

Affected run: https://github.com/Ouranosinc/raven/actions/runs/5723437100/job/15556513354

**Comment by asottile** [comment]
it's consistent if you have the same `identify` version -- that's how file identification works

**Comment by Zeitsperre** [comment]
I don't often dive into the internals of pre-commit, so I wasn't aware of that. Thanks for identifying the cause.

If one were to fix this across multiple pre-commit environments, I imagine that I could manually set the minimum `identify` version within the hook itself? (e.g. `additional_dependencies: ['identify>=maj.min.patch']`)

**Comment by asottile** [comment]
no, identify is a dependency of _pre-commit_ not of the hooks

**Comment by amarvin** [comment]
The same issue is happening for me, but reversed -- locally `pretty-format-json` is fixing notebooks, yet pre-commit ci on GitHub isn't. @Zeitsperre, how is your workaround to exclude `.ipynb` files defined in `.pre-commit-config.yaml`? I tried `exclude_types: [ipynb]` but it says it's not a known type in latest `identify==2.5.35`.

**Comment by amarvin** [comment]
> The same issue is happening for me, but reversed -- locally `pretty-format-json` is fixing notebooks, yet pre-commit ci on GitHub isn't. @Zeitsperre, how is your workaround to exclude `.ipynb` files defined in `.pre-commit-config.yaml`? I tried `exclude_types: [ipynb]` but it says it's not a known type in latest `identify==2.5.35`.

This works `exclude_types [jupyter]`

**Comment by Zeitsperre** [comment]
@amarvin Sorry, I was on vacation for a few weeks. My workaround was to exclude files with a `.ipynb` suffix, but your workaround is much more elegant. I may just adopt yours instead!
