### ISSUE TITLE
Feature request discussion - Shopify compatible formatting for json files

### ISSUE THREAD

**Issue by ascheucher-shopify-partner** [pre-commit/pre-commit-hooks#946]
Hi,
obviously I was over motivated :)

I needed a solution to format my Shopify theme .json files in a compatible way to not run into Shopify formatting them again after every commit.

As Shopify suggests to use [prettier with pre-commit in it's documentation](https://shopify.dev/docs/themes/tools/liquid-prettier-plugin#use-the-plugin-as-a-pre-commit-hook), but prettier formats it wrong I thought extending the pretty-format-json hook would be a good move.

Obviously it's to specific. How could I add the functionality? Just host it on my own repo and always merge in updates from the pre-commit repo? Doesn't sound very attractive to me.

I am happy for other suggestions.
Thanks,
Andreas

**Comment by asottile** [comment]
you have several solutions that sounds fine to me.  though I would probably just do what the tool you're using suggests
