### ISSUE TITLE
mixed-line-ending modifies UTF-16LE BOM characters

### ISSUE THREAD

**Issue by kvalkhof75** [pre-commit/pre-commit-hooks#948]
We have some files saved with`UTL16LE BOM` encoding.
After running pre-commit with mixed-line-ending, we see that the following characters are changed:

(0x010D) `č` -> `Ċ` (0x010A)
(0x4E0D) `不` ->`上` (0x4E0A)
(0xBC0D) `밍` -> `밊` (0xBC0A)

(There are probably a lot more characters affected.)

There is no issue if I change the encoding of the files to `UTF-8` before running pre-commit.

**Comment by asottile** [comment]
it only supports utf8, correct

**Comment by kvalkhof75** [comment]
I looked at the code and it indeed will not support other encodings.
I am more surprised that only this part of our build actually fails. But I guess that my people should not use 'UTF-16LE BOM' in source files anyway.
Unless you want to support more encodings (I could check to find a solution), consider the issue closed.
