### ISSUE TITLE
Pretty format json optional new line

### ISSUE THREAD

**Issue by dale-vendia** [pre-commit/pre-commit-hooks#949]
We use the `vscode.json-language-features` and that formatter can be configured the same way as pretty format json. The issue is that `vscode.json-language-features` removes the trailing new line whereas this hook always adds one.

This bouncing between tailing end of lines is annoying when you safe the a JSON file the pre-commit hook always detects a change

https://github.com/pre-commit/pre-commit-hooks/blob/main/pre_commit_hooks/pretty_format_json.py#L30C30-L30C30

Appreciate you work! Let me know if you want me to submit a PR I'd be happy to have a go

**Comment by asottile** [comment]
pick one or the other then -- if you have two conflicting things that do the same thing you don't want both of them
