### ISSUE TITLE
Improved experience for check-merge-conflict

### ISSUE THREAD

**Issue by acdha** [pre-commit/pre-commit-hooks#951]
I recently encountered a failure where someone committed code with an unresolved merge conflict. This was a bit of a surprise because we have `check-merge-conflict` enabled and that hook reported its status as “pass”.  

Reading #660 and #881 revealed that this is fairly common because you need to set `--assume-in-merge` to have it actually check the files any time [you're not running in the middle of a merge/rebase](https://github.com/pre-commit/pre-commit-hooks/blob/e35ba8d463d783ad7d8189213b5426c0a2c9de3b/pre_commit_hooks/check_merge_conflict.py#L15-L23) and that won't happen normally in situations such as when GitLab/GitHub have done the merge for you and are running the pre-commit CI check afterwards.

I think this could be less confusing in two ways:

1. When the hook doesn't run, display the status as “skipped”
2. The name `--assume-in-merge` is a bit counterintuitive – I think most pre-commit users would assume that the hook is intended to always run by default simply by enabling it. A name like `--always-run` or a description explaining that the hook by default only runs when making a merge commit could make it clear that at other times it will not run at all.
3. It's not clear why you would ever want to have the hook installed but not running on most commits but based on #300 it's situations where the `=======` pattern would match on things like ReST files which use that for unrelated reasons. It seems like one way to fix this would be to either remove that pattern from this hook or change the logic to require at least _two_ of the patterns to match in a given file. To catch cases where someone manually edited a merge conflict and missed one of the marks, perhaps that's changing the default logic to require 1 match when in a merge and 2+ otherwise, optionally with an argument to force the current behaviour. It could further reduce the noise level by requiring them to match in order (i.e. `<<<<<<< ` must occur before `=======` or `>>>>>>> ` after).

**Comment by asottile** [comment]
I suspect you're trusting the "someone" actually ran the hooks -- it's working as intended as far as I know

**Comment by acdha** [comment]
I have proof that they were run - the problem is that the hook silently did not run.

**Comment by asottile** [comment]
were they run while resolving a merge conflict?

**Comment by asottile** [comment]
aka: come up with a reproducible case and then maybe something will change -- otherwise we're both guessing at a problem that might not exist

**Comment by asottile** [comment]
ok then this is an exact duplicate of #660

**Comment by acdha** [comment]
It's the same problem, yes. I was trying to help make the experience better for pre-commit users since what happens currently is that you think you're protected against this problem but are in fact still vulnerable. The three suggestions would make it easier to see that (point one) and reduce the number of cases where you'd be exposed (points two and three).

**Comment by asottile** [comment]
ok I'll address your suggestions -- but they're not going to help

(1) the hook has no control over the messaging there
(2) I'm not going to change the name
(3) this would allow partial resolves to slip through the cracks so it makes the hook worse

**Comment by acdha** [comment]
> (2) I'm not going to change the name

Could the documentation be clarified, then? It would be nice to avoid this recurring again.

> (3) this would allow partial resolves to slip through the cracks so it makes the hook worse

My proposed implementation was designed to preserve the current behaviour when the `is_in_merge()` check passes so this wouldn't allow any partial resolve which is currently being caught to slip through but it would catch many of the conflicts which are currently slipping through.
