### ISSUE TITLE
‎check-yaml` is not present in repository https://github.com/pre-commit/pre-commit-hooks. 

### ISSUE THREAD

**Issue by lalits4** [pre-commit/pre-commit-hooks#956]
name: iops-server-workflow

on:
  push:
    branches:
    - develop
jobs:
  iops-server:
    if: github.ref == 'refs/heads/develop'
    uses: user/repo1-workflows/.github/workflows/services-workflow.yml@main
    with:
      runPreCommit: true
      runPytest: true
      runCheckAlembic: false
      runVeracode: false
      appServiceName: ${{ vars.DEV_IOPS_SERVICE_NAME }}
      imageName: ${{ vars.IOPS_SERVICE_IMAGE_NAME }}
      pythonVersion: 3.8

**Comment by lalits4** [comment]
name: services_workflow

on:
  push:
    branches:
    - main
    workflow_call:
    inputs:
      runPreCommit:
        description: 'runPreCommit'
        required: false
        default: false
        type: string
      runPytest:
        description: 'runPytest'
        required: false
        default: false
        type: string
      runCheckAlembic:
        description: 'runCheckAlembic'
        required: false
        default: false
        type: string
      appServiceName:
        description: 'appServiceName'
        required: false
        default: ''
        type: string
      imageName:
        description: 'imageName'
        required: false
        default: ''
        type: string
      pythonVersion:
        description: 'pythonVersion'
        required: false
        default: '3.8'
        type: string
      runVeracode:
        description: 'runVeracode'
        required: false
        default: ''
        type: string
env:
  PIP_CACHE_DIR: ${{ github.workspace }}/.pip
  PRE_COMMIT_HOME: ${{ github.workspace }}/pre-commit-cache
  AZURE_SUBSCRIBPTION: ${{ github.ref == 'refs/heads/develop' && vars.DEV_SUBSCRIPTION  || github.ref == 'refs/heads/qa' && vars.QA_SUBSCRIPTION || github.ref == 'refs/heads/prod' && vars.PROD_SUBSCRIPTION || '' }}
  CONTAINER_REPOSITORY: ${{ github.ref == 'refs/heads/develop' && vars.DEV_CONTAINER_REPOSITORY || github.ref == 'refs/heads/qa' && vars.QA_CONTAINER_REPOSITORY || github.ref == 'refs/heads/prod' && vars.PROD_CONTAINER_REPOSITORY || '' }}
  DEPLOY: ${{ github.ref == 'refs/heads/develop' && 'false' || github.ref == 'refs/heads/qa' && 'false' || github.ref == 'refs/heads/prod' && 'false' || 'false' }}
  VERACODE: ${{ github.ref == 'refs/heads/develop' && 'false' || github.ref == 'refs/heads/qa' && 'false' || github.ref == 'refs/heads/prod' && 'false' || 'false' }}
  
  TAG: ${{ github.run_id }}
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Repo' 
      uses: actions/checkout@v2

    - name: '[Python] Set Python version to ${{ inputs.pythonVersion }}'
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.pythonVersion }}
        
    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('./requirements.txt') }}
   
    - name: '[Python] Install Python requirements'
      run: |
        pip install -r requirements.txt
        pip install omniblu-backend-common -U
        
    - name: '[Python] Install Pre commits '
      run: |
       pip install pre-commit
       pre-commit run autopep8 --all-files

      
    - name: Cache Pre Commit
      if: (success() && (${{ inputs.runPreCommit }} == true))
      uses: actions/cache@v3
      with:
        key:  pre-commit | .pre-commit-config.yaml
        restore-keys:
        path: ${{ env.PRE_COMMIT_HOME }}
    
    - name: '[Python] Run pre-commit'
      if: (success() && (${{ inputs.runPreCommit }} == true))
      run: pre-commit run -a

    - name: '[Python] Run pytest with coverage'
      if: (success() && (${{ inputs.runPytest }} == true))
      run: |
        python -m pytest tests/ \
              --doctest-modules \
              --junitxml=junit/test-results.xml \
              --cov=. \
              --cov-report=xml

    - name: Publish Test Report
      if: success() || failure() # always run even if the previous step fails
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: '**/test-*.xml'

    - name: Publish code coverage results
      if: success() || failure()
      uses: 5monkeys/cobertura-action@master
      with:
        path: ${{ github.workspace }}/**/coverage.xml
        minimum_coverage: 75

    - name: '[Python] Check Alembic Multi Head'
      if: (success() && (${{ inputs.runCheckAlembic }} == true))
      run: python cicd/check_alembic_rev.py

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
      
    - name: 'Azure Container Registry Login'
      if: (success() && (${{ inputs.DEPLOY }} == true))
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REPOSITORY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Build and Push image to Container registry' 
      if: (success() && (${{ inputs.DEPLOY }} == true))
      run: |
        docker build . -t ${{ env.CONTAINER_REPOSITORY }}/${{ inputs.imageName }}:${{ github.sha }}
        docker push ${{ env.CONTAINER_REPOSITORY }}/${{ inputs.imageName }}:${{ github.sha }}   
    
    - name: Deploy app service ${{ inputs.appServiceName }}
      if: (success() && (${{ inputs.DEPLOY }} == true))
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.appServiceName }}
        images: ${{ env.CONTAINER_REPOSITORY }}/${{ inputs.imageName }}:${{ github.sha }}

  Veracode:
    runs-on: ubuntu-latest
    if: ((${{ inputs.runVeracode }} == true) && (env.VERACODE == 'true'))
    steps:
    - name: 'Create zip for Veracode'
      run: |
        git archive --format=zip -o ${{ github.sha }}-veracode-zip.zip

    - name: 'Run Veracode Scan'
      uses: veracode/veracode-uploadandscan-action@0.2.4
      with:
        appname: 'Project Extend'
        filepath: ${{ github.workspace }}/${{ github.sha }}-veracode-zip.zip
        vid: ${{ secrets.VERACODE_API_ID }}
        vkey: ${{ secrets.VERACODE_API_KEY }}



Note: this is the workflow called by above workflow it placed in another repo

**Comment by lalits4** [comment]
Run pre-commit run -a
  pre-commit run -a
  shell: /usr/bin/bash -e {0}
  env:
    PIP_CACHE_DIR: /home/runner/work/azure-reusable-workflows/azure-reusable-workflows/.pip
    PRE_COMMIT_HOME: /home/runner/work/azure-reusable-workflows/azure-reusable-workflows/pre-commit-cache
    AZURE_SUBSCRIBPTION: 
    CONTAINER_REPOSITORY: 
    DEPLOY: false
    VERACODE: false
    TAG: 6086006[4](https://github.com/jbt-omniblu/azure-reusable-workflows/actions/runs/6086006447/job/16511377998#step:8:4)4[7](https://github.com/jbt-omniblu/azure-reusable-workflows/actions/runs/6086006447/job/16511377998#step:8:7)
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
Error:  `‎check-yaml` is not present in repository https://github.com/pre-commit/pre-commit-hooks.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.
Error: Process completed with exit code 1.

**Comment by asottile** [comment]
please continue in #955 

I need your pre-commit configuration, not any of the other stuff.  it should be in `.pre-commit-config.yaml`

**Comment by lalits4** [comment]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: ‎check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: double-quote-string-fixer

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0  # Use the sha / tag you want to point at
    hooks:
      - id: autopep8

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake

**Comment by asottile** [comment]
looks like you have a weird non-printing space right before `check-yaml`:

```pycon
>>> '''\
... 
...       - id: ‎check-yaml
... '''
'\n      - id: \u200echeck-yaml\n'
>>> unicodedata.name('\u200e')
'LEFT-TO-RIGHT MARK'
```

try rewriting that line manually but without the invisible character

**Comment by lalits4** [comment]
provide me proper so that i could paste to avoid space issue

**Comment by asottile** [comment]
if you put your cursor after the `c`, press backspace a few times, then press space and c you should be good

**Comment by lalits4** [comment]
thank you

**Comment by lalits4** [comment]
done the same and got below error

Run pre-commit run -a
  pre-commit run -a
  shell: /usr/bin/bash -e {0}
  env:
    PIP_CACHE_DIR: /home/runner/work/azure-reusable-workflows/azure-reusable-workflows/.pip
    PRE_COMMIT_HOME: /home/runner/work/azure-reusable-workflows/azure-reusable-workflows/pre-commit-cache
    AZURE_SUBSCRIBPTION: 
    CONTAINER_REPOSITORY: 
    DEPLOY: false
    VERACODE: false
    TAG: 60876[2](https://github.com/jbt-omniblu/azure-reusable-workflows/actions/runs/6087621483/job/16516572703#step:7:2)148[3](https://github.com/jbt-omniblu/azure-reusable-workflows/actions/runs/6087621483/job/16516572703#step:7:3)
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-autopep8.
[INFO] Initializing environment for https://github.com/PyCQA/autoflake.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-autopep8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/autoflake.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

while parsing a block mapping
  in "services/services-workflow.yml", line 1[4](https://github.com/jbt-omniblu/azure-reusable-workflows/actions/runs/6087621483/job/16516572703#step:7:4)[7](https://github.com/jbt-omniblu/azure-reusable-workflows/actions/runs/6087621483/job/16516572703#step:7:7), column 7
did not find expected key
  in "services/services-workflow.yml", line 14[8](https://github.com/jbt-omniblu/azure-reusable-workflows/actions/runs/6087621483/job/16516572703#step:7:8), column [9](https://github.com/jbt-omniblu/azure-reusable-workflows/actions/runs/6087621483/job/16516572703#step:7:9)

fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing README.md
Fixing .github/workflows/services-workflow.yml

trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing .github/workflows/services-workflow.yml
Fixing databricks/jobs/databricks-workflow.yml
Fixing services/services-workflow.yml

fix requirements.txt.....................................................Passed
check docstring is first.............................(no files to check)Skipped
debug statements (python)............................(no files to check)Skipped
fix double quoted strings............................(no files to check)Skipped
autopep8.............................................(no files to check)Skipped
autoflake............................................(no files to check)Skipped
Error: Process completed with exit code 1.

**Comment by asottile** [comment]
great, looks like it's working as intended now and it's pointing out problems in your code that you need to fix now
