### ISSUE TITLE
‎check-yaml` is not present in repository https://github.com/pre-commit/pre-commit-hooks. 

### ISSUE THREAD

**Issue by lalits4** [pre-commit/pre-commit-hooks#957]
same issues occured after done the same

Run pre-commit run -a
  pre-commit run -a
  shell: /usr/bin/bash -e {0}
  env:
    PIP_CACHE_DIR: /home/runner/work/azure-reusable-workflows/azure-reusable-workflows/.pip
    PRE_COMMIT_HOME: /home/runner/work/azure-reusable-workflows/azure-reusable-workflows/pre-commit-cache
    AZURE_SUBSCRIBPTION: 
    CONTAINER_REPOSITORY: 
    DEPLOY: false
    VERACODE: false
    TAG: 60876[2](https://github.com/jbt-omniblu/azure-reusable-workflows/actions/runs/6087621483/job/16516572703#step:7:2)148[3](https://github.com/jbt-omniblu/azure-reusable-workflows/actions/runs/6087621483/job/16516572703#step:7:3)
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-autopep8.
[INFO] Initializing environment for https://github.com/PyCQA/autoflake.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-autopep8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/autoflake.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

while parsing a block mapping
  in "services/services-workflow.yml", line 1[4](https://github.com/jbt-omniblu/azure-reusable-workflows/actions/runs/6087621483/job/16516572703#step:7:4)[7](https://github.com/jbt-omniblu/azure-reusable-workflows/actions/runs/6087621483/job/16516572703#step:7:7), column 7
did not find expected key
  in "services/services-workflow.yml", line 14[8](https://github.com/jbt-omniblu/azure-reusable-workflows/actions/runs/6087621483/job/16516572703#step:7:8), column [9](https://github.com/jbt-omniblu/azure-reusable-workflows/actions/runs/6087621483/job/16516572703#step:7:9)

fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing README.md
Fixing .github/workflows/services-workflow.yml

trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing .github/workflows/services-workflow.yml
Fixing databricks/jobs/databricks-workflow.yml
Fixing services/services-workflow.yml

fix requirements.txt.....................................................Passed
check docstring is first.............................(no files to check)Skipped
debug statements (python)............................(no files to check)Skipped
fix double quoted strings............................(no files to check)Skipped
autopep8.............................................(no files to check)Skipped
autoflake............................................(no files to check)Skipped
Error: Process completed with exit code 1.

**Comment by asottile** [comment]
please stop -- these are no longer issues I can help you with.  you need to fix your own things
