### ISSUE TITLE
`requirements-txt-fixer` does not remove duplicated elements

### ISSUE THREAD

**Issue by csibe17** [pre-commit/pre-commit-hooks#960]
In `requirements-txt-fixer` if there are more than 1 requirement with the same params, the duplicates are not removed.

**Comment by asottile** [comment]
can you show an example?

**Comment by csibe17** [comment]
```
dependency1==1.0.0
dependency2==1.0.0
dependency3==1.0.0
dependency1==1.0.0
```

will end up as

```
dependency1==1.0.0
dependency1==1.0.0
dependency2==1.0.0
dependency3==1.0.0
```

**Comment by JaySharmaSdsu** [comment]
I am totally new to contributing on open source. If this is indeed an issue. Can I work on it?'

**Comment by asottile** [comment]
sure go for it, let me know if you need any help

**Comment by JaySharmaSdsu** [comment]
Sick! Excited!! Let me get back if I need any help.
