### ISSUE TITLE
`double-string-fixer` will introduce syntax errors for nested f-strings for Python pre-3.12 versions when `pre-commit` is run by Python 3.12

### ISSUE THREAD

**Issue by XuehaiPan** [pre-commit/pre-commit-hooks#971]
Thanks for the great tool! It is really convenient to maintain a consistent code style among contributors. I use the `double-string-fixer` to keep Python strings in a single-quoted format cooperating with `black`, which prefers double-quoted strings.

Python 3.12 was just released several days ago. It allows users to write arbitrary nested f-strings without changing the quote styles ([PEP 701 – Syntactic formalization of f-strings](https://peps.python.org/pep-0701)).

```python
# Python 3.11
f'-DPYTHON_INCLUDE_DIR={sysconfig.get_path("platinclude")}'

# Python 3.12
f'-DPYTHON_INCLUDE_DIR={sysconfig.get_path('platinclude')}'  # syntax error in Python 3.11
```

The `pre-commit-hooks` are invoked by the Python interpreter which runs `pre-commit`. When the `pre-commit` command is installed with Python 3.12, it enables PEP 701 and will introduce syntax errors for Python pre-3.12 versions.

```diff
- f'-DPYTHON_INCLUDE_DIR={sysconfig.get_path("platinclude")}'
+ f'-DPYTHON_INCLUDE_DIR={sysconfig.get_path('platinclude')}'
```

This maybe a problem for a project that supports multiple Python versions.

**Comment by asottile** [comment]
yeah for now I would recommend running it in the oldest python version you support

**Comment by XuehaiPan** [comment]
Thanks for the advice. I have pinned the Python version in our CI.

I'm also looking forward to the `double-string-fixer` can work as expected for a better local development experience. Maybe we can add an extra argument, e.g., `--target-version=py311`.

**Comment by asottile** [comment]
personally I think the nested fstrings stuff is bad so I'll be making it just ignore the stuff inside there (like it always did)
