### ISSUE TITLE
Add GitHub issue presence pre-commit-check 

### ISSUE THREAD

**Issue by rantoniuk** [pre-commit/pre-commit-hooks#978]
It would be really useful to have an out-of-the-box pre-commit-hook for GitHub issues, based on branch name or commit message, something [like this](https://serebrov.github.io/html/2019-06-16-git-hook-to-add-issue-number-to-commit-message.html).

Would this make sense to for you to add this into this repo? I can create the necessary PR.

**Comment by asottile** [comment]
you can easily implement this with `pygrep` so no need for a dedicated hook here

**Comment by rantoniuk** [comment]
Of course I can. I can implement all of the hooks that are present here. Wasn't the purpose of this project to have an out-of-the-box solution that can be easily used without needed to use my hand-crafted solution?
In other words, what's the point of having things like [detect_aws_credentials.py](https://github.com/pre-commit/pre-commit-hooks/blob/main/pre_commit_hooks/detect_aws_credentials.py) here if I can just use pygrep as well?
