### ISSUE TITLE
How to rubustify symlink checks

### ISSUE THREAD

**Issue by hofbi** [pre-commit/pre-commit-hooks#980]
I checked for existing issues but was not able to find a suitable one, hence raising this new one.

## Problem

Assume the following situation

```
foo.txt  # This is a file
foo.lnk  # This points to foo.txt
```

`check-symlinks` detects the broken symlink if I change `foo.lnk`, however if I change `foo.txt`, the hook passes unless I run pre-commit on all files. This allows broken symlinks to sneak in.

## Expected Behavior

I found `check-symlinks` only runs on type `symlink` while `destroyed-symlinks` runs on files. I would have expected that one of these detects the broken symlink when renaming the file symlinks are pointing to.

## Workaround

One solution to prevent broken symlinks sneak in, is to run `pre-commit run check-symlinks -a` in CI after running `pre-commit` only on the changeset.

Is there a way we could make the symlink checks more robust to detect this kind of issue?

**Comment by asottile** [comment]
this is one of the reasons why I recommend running on all files in CI
