### ISSUE TITLE
Ruamel no longer works in Azure devops

### ISSUE THREAD

**Issue by dguidara** [pre-commit/pre-commit-hooks#982]
As of version 0.17.39, the readme was switched to CommonMark, which is not supported in Azure Devops.  Any python user in Azure devops who tries to use Precommit-hooks will get an error like this:
 Bad Request - Markdown variant 'CommonMark' is unsupported. Supported variants are: GFM. (DevOps Activity ID:

**Comment by asottile** [comment]
as I told you in the other report there is a built in way to select a dependency. please search the pre-commit documentation and if you can't figure it out then I can help you

**Comment by dguidara** [comment]
Thanks for your patience and guidance.  I am new to open source and github.  I thought a pull request might be beneficial to all other azure devops python users.    This is my first time doing this.

**Comment by asottile** [comment]
a code change here is not necessary, you can override the options in your config directly
