### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by msu11y** [pre-commit/pre-commit-hooks#989]
I pip installed pre-commit into my virtual environment (3.5), ran 'pre-commit install', and setup a very basic YAML file. When I do a test to see if it works (pre-commit run) I get the below error:

![image](https://github.com/pre-commit/pre-commit-hooks/assets/34222674/859a81e5-495e-4c80-ae11-5bb815905cfd)

I don't know if this is a bug or I am doing something wrong. Appreciate any feedback!

**Comment by asottile** [comment]
your git can't make ssl requests to github.  probably you have some sort of firewall or otherwise blocking your access

this isn't a pre-commit problem

**Comment by msu11y** [comment]
Yes, I just figured it out. I ran: 

git config --global http.sslbackend schannel

and it fixed it.

Thank you
