### ISSUE TITLE
Hook idea: executable files should have a shebang or not be executable

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit-hooks#99]
Alternatively, files with a shebang should be executable

**Comment by webknjaz** [comment]
...but only if they are text files

**Comment by asottile** [comment]
This becomes much easier with `types` implemented in 0.15.0

**Comment by chriskuehl** [comment]
@asottile this is actually a good example where AND behavior in types makes sense, we want `types: [text, executable]` here. I'll take a crack at this.

**Comment by asottile** [comment]
Sweet, I'm rewriting the metadata right now so we'll likely conflict hard there -- I'm almost done but it's tedious :D
