### ISSUE TITLE
`pre-commit` in a CI as a checker only?

### ISSUE THREAD

**Issue by niccolomineo** [pre-commit/pre-commit-hooks#994]
Hi there, what suggestions do you have should I want to run pre-commit in a CI pipeline without committing anything, thus basically having pre-commit run as a checker rather than a fixer? Is this possible somehow, even with a workaround?

Please note that what's giving me headaches are those hooks that do not have a check counterpart (e.g. `fix-byte-order-marker`).

Thank you.

**Comment by asottile** [comment]
this is not the right place -- this is a repo containing some out of the box tools

there's recommendations in the docs on the website -- check through those
